### ISSUE TITLE
mezz.jei.util.BrokenCraftingRecipeException on SkyFactory 3 (Version 3.0.14)

### ISSUE THREAD

**Issue by guninvalid** [mezz/JustEnoughItems#1009]
I need to know for the sake of troubleshooting. I want to make sure my Minecraft isn't corrupted. As this is the last error on my list and the most likely to be the one causing my Minecraft to crash every time I open this, and only this, world. When I made a new world, it never crashed. The rest of the message in which I found this issue are as follows:

(Yes, this is the only message in which mezz.jei.util.BrokenCraftingRecipeException appears)

[17:26:02] [Server thread/ERROR]: Found a broken crafting recipe.
mezz.jei.util.BrokenCraftingRecipeException: net.minecraft.item.crafting.ShapedRecipes@5a8c1189
Outputs:
net.minecraft.item.ItemStack: [[1xtile.growth_upgrade@0 tp:growth_upgrade]]
Inputs:
net.minecraft.item.ItemStack: [[1xtile.ReinforcedObsidian@0 tp:ReinforcedObsidian], [1xitem.WateringCanUpgrade@0 tp:WateringCanUpgrade], [1xtile.ReinforcedObsidian@0 tp:ReinforcedObsidian], [1xitem.end_crystal@0 minecraft:end_crystal], [1xtile.growth_block@0 tp:growth_block], [1xitem.end_crystal@0 minecraft:end_crystal], [1xtile.ReinforcedObsidian@0 tp:ReinforcedObsidian], [1x (null)], [1xtile.ReinforcedObsidian@0 tp:ReinforcedObsidian]]
Caused by: java.lang.NullPointerException: Null item in itemStack
	at mezz.jei.util.StackHelper.getSubtypes(StackHelper.java:219) ~[StackHelper.class:?]
	at mezz.jei.util.StackHelper.getAllSubtypes(StackHelper.java:292) ~[StackHelper.class:?]
	at mezz.jei.util.StackHelper.getAllSubtypes(StackHelper.java:270) ~[StackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.expandSubtypes(ItemStackHelper.java:24) ~[ItemStackHelper.class:?]
	at mezz.jei.util.Ingredients.setInputs(Ingredients.java:48) ~[Ingredients.class:?]
	at mezz.jei.plugins.vanilla.crafting.ShapedRecipesWrapper.getIngredients(ShapedRecipesWrapper.java:33) ~[ShapedRecipesWrapper.class:?]
	at mezz.jei.RecipeRegistry.getIngredients(RecipeRegistry.java:288) ~[RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:272) ~[RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:242) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:201) [RecipeRegistry.class:?]
	at minetweaker.mods.jei.JEIRecipeRegistry.addRecipe(JEIRecipeRegistry.java:33) [JEIRecipeRegistry.class:?]
	at minetweaker.mc1102.recipes.MCRecipeManager$ActionRemoveRecipes.undo(MCRecipeManager.java:362) [MCRecipeManager$ActionRemoveRecipes.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:70) [MTTweaker.class:?]
	at minetweaker.mc1102.MineTweakerMod.onServerStopped(MineTweakerMod.java:180) [MineTweakerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:916) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:498) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:533) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by guninvalid** [comment]
oops

**Comment by mezz** [comment]
Broken recipes don't crash the game, they just don't work as intended. This one looks like a minetweaker recipe that has issues. It is supposed to output `tp:growth_upgrade` but has `null` as one of the ingredients.

**Comment by guninvalid** [comment]
So the issue would be something else? Ill look through the log and see what I can do. Thanks.
