### ISSUE TITLE
Crash caused by JEI?

### ISSUE THREAD

**Issue by DieselpunkCyborg** [mezz/JustEnoughItems#1029]
My Age of Engineering worlds crash shortly after startup, I think it might be JEI.

`[15:07:34] [Server thread/ERROR] [JEI]: Null stacks
java.lang.NullPointerException
	at mezz.jei.util.StackHelper.getAllSubtypes(StackHelper.java:265) [StackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.expandSubtypes(ItemStackHelper.java:24) [ItemStackHelper.class:?]
	at mezz.jei.util.Ingredients.setInputLists(Ingredients.java:32) [Ingredients.class:?]
	at aroma1997.core.integration.jei.recipe.ShapedAromicRecipeWrapper.getIngredients(ShapedAromicRecipeWrapper.java:43) [ShapedAromicRecipeWrapper.class:?]
	at mezz.jei.RecipeRegistry.getIngredients(RecipeRegistry.java:288) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:272) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:242) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:201) [RecipeRegistry.class:?]
	at minetweaker.mods.jei.JEIRecipeRegistry.addRecipe(JEIRecipeRegistry.java:33) [JEIRecipeRegistry.class:?]
	at minetweaker.mc1102.recipes.MCRecipeManager$ActionRemoveRecipes.undo(MCRecipeManager.java:362) [MCRecipeManager$ActionRemoveRecipes.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:70) [MTTweaker.class:?]
	at minetweaker.mc1102.MineTweakerMod.onServerStopped(MineTweakerMod.java:180) [MineTweakerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:916) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:498) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:533) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[15:07:34] [Server thread/ERROR] [JEI]: Null stacks
java.lang.NullPointerException
	at mezz.jei.util.StackHelper.getAllSubtypes(StackHelper.java:265) [StackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.expandSubtypes(ItemStackHelper.java:24) [ItemStackHelper.class:?]
	at mezz.jei.util.Ingredients.setInputLists(Ingredients.java:32) [Ingredients.class:?]
	at aroma1997.core.integration.jei.recipe.ShapedAromicRecipeWrapper.getIngredients(ShapedAromicRecipeWrapper.java:43) [ShapedAromicRecipeWrapper.class:?]
	at mezz.jei.RecipeRegistry.getIngredients(RecipeRegistry.java:288) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:272) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:242) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:201) [RecipeRegistry.class:?]
	at minetweaker.mods.jei.JEIRecipeRegistry.addRecipe(JEIRecipeRegistry.java:33) [JEIRecipeRegistry.class:?]
	at minetweaker.mc1102.recipes.MCRecipeManager$ActionRemoveRecipes.undo(MCRecipeManager.java:362) [MCRecipeManager$ActionRemoveRecipes.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:70) [MTTweaker.class:?]
	at minetweaker.mc1102.MineTweakerMod.onServerStopped(MineTweakerMod.java:180) [MineTweakerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:916) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:498) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:533) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[15:07:34] [Server thread/ERROR] [JEI]: Null stacks
java.lang.NullPointerException
	at mezz.jei.util.StackHelper.getAllSubtypes(StackHelper.java:265) [StackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.expandSubtypes(ItemStackHelper.java:24) [ItemStackHelper.class:?]
	at mezz.jei.util.Ingredients.setInputLists(Ingredients.java:32) [Ingredients.class:?]
	at aroma1997.core.integration.jei.recipe.ShapedAromicRecipeWrapper.getIngredients(ShapedAromicRecipeWrapper.java:43) [ShapedAromicRecipeWrapper.class:?]
	at mezz.jei.RecipeRegistry.getIngredients(RecipeRegistry.java:288) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:272) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:242) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:201) [RecipeRegistry.class:?]
	at minetweaker.mods.jei.JEIRecipeRegistry.addRecipe(JEIRecipeRegistry.java:33) [JEIRecipeRegistry.class:?]
	at minetweaker.mc1102.recipes.MCRecipeManager$ActionRemoveRecipes.undo(MCRecipeManager.java:362) [MCRecipeManager$ActionRemoveRecipes.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:70) [MTTweaker.class:?]
	at minetweaker.mc1102.MineTweakerMod.onServerStopped(MineTweakerMod.java:180) [MineTweakerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:916) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:498) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:533) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[15:07:34] [Server thread/ERROR] [JEI]: Null stacks
java.lang.NullPointerException
	at mezz.jei.util.StackHelper.getAllSubtypes(StackHelper.java:265) [StackHelper.class:?]
	at mezz.jei.plugins.vanilla.ingredients.ItemStackHelper.expandSubtypes(ItemStackHelper.java:24) [ItemStackHelper.class:?]
	at mezz.jei.util.Ingredients.setInputLists(Ingredients.java:32) [Ingredients.class:?]
	at aroma1997.core.integration.jei.recipe.ShapedAromicRecipeWrapper.getIngredients(ShapedAromicRecipeWrapper.java:43) [ShapedAromicRecipeWrapper.class:?]
	at mezz.jei.RecipeRegistry.getIngredients(RecipeRegistry.java:288) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:272) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:242) [RecipeRegistry.class:?]
	at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:201) [RecipeRegistry.class:?]
	at minetweaker.mods.jei.JEIRecipeRegistry.addRecipe(JEIRecipeRegistry.java:33) [JEIRecipeRegistry.class:?]
	at minetweaker.mc1102.recipes.MCRecipeManager$ActionRemoveRecipes.undo(MCRecipeManager.java:362) [MCRecipeManager$ActionRemoveRecipes.class:?]
	at minetweaker.runtime.MTTweaker.rollback(MTTweaker.java:70) [MTTweaker.class:?]
	at minetweaker.mc1102.MineTweakerMod.onServerStopped(MineTweakerMod.java:180) [MineTweakerMod.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverStopped(Loader.java:916) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:498) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:533) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[15:07:34] [Server thread/INFO] [mcjty.lib.varia.Logging]: Deep Resonance: server is stopping. Shutting down gracefully
[15:07:34] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[15:07:34] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[15:07:34] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up RFTools dimensions
[15:07:34] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:07:34] [Client thread/INFO] [FML]: Server terminated.
[15:07:34] [Client Shutdown Thread/INFO]: Stopping server
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.`

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.

**Comment by DieselpunkCyborg** [comment]
Doneski, thank you for your reply

https://gist.github.com/DieselpunkCyborg/a9cb2cad5c59a2efc0f32f879929f22d

**Comment by mezz** [comment]
Your crash log is unusually hard to figure out, I can see why you thought it was from JEI.
I have extracted the real cause of the crash, you can see it here:
https://gist.github.com/mezz/0d2df76537f265d44262dc5854ae8589
Please report this crash to the ZombieAwareness mod here: https://github.com/Corosauce/ZombieAwareness/issues

**Comment by DieselpunkCyborg** [comment]
Thank you, I removed ZA and Coroutil and the crashing stopped, sorry to assume it was JEI. Tanks for the replies, you rock (:
