### ISSUE TITLE
[1.12.2] [4.8.5.135] Rendering ingredient ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by katur239** [mezz/JustEnoughItems#1072]
I wasn't sure if this was a JEI issue but tterrag seems to think it is so posting it here.

Chisel : 0.1.0.23
CTM : 0.2.3.9
JEI : 4.8.5.135

```
Description: Rendering ingredient

java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.client.renderer.BufferBuilder.drawMultiTexture(BufferBuilder.java:821)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:72)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:22)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:161)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:132)
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:61)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:30)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:156)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:90)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:199)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1786_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:164)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:353)
	at sun.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:555)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

``` 
```
-- Ingredient being rendered --
Details:
	Ingredient Mod: Chisel
	Ingredient Info: 1xtile.chisel.basalt@0 chisel:basalt

``` 

Full Report https://gist.github.com/katur239/7bf3df2beac9bfe89ad9488a363a80cb

**Comment by mezz** [comment]
Sorry I missed this issue. It seems like a problem from Chisel but I am not sure.
Have you reported it to them?
