### ISSUE TITLE
Illegal Reference Count Exception Error

### ISSUE THREAD

**Issue by DAgility** [mezz/JustEnoughItems#1077]
Whenever i try to spawn in an item via cheat mode i get this in server console:

[01:33:27] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_144]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
        at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394) ~[AbstractByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[AbstractByteBuf.class:?]
        at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864) ~[gy.class:?]
        at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864) ~[gy.class:?]
        at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:303) ~[gy.class:?]
        at mezz.jei.network.packets.PacketGiveItemStack.readPacketData(PacketGiveItemStack.java:40) ~[PacketGiveItemStack.class:?]
        at mezz.jei.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:55) ~[PacketHandler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version of JEI.
