### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Kartoffelbrot** [mezz/JustEnoughItems#1147]
Hi,
if i want start minecraft it shows me this issue.What can i do to solve the problem?

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` to https://gist.github.com and link it here.

**Comment by Kartoffelbrot** [comment]
thx problem is fixed

**Comment by mezz** [comment]
What was the problem?

**Comment by LeonFulgor** [comment]
I also seem to be getting this crash error, I uploaded my crash log.
[crash-2018-03-12_00.16.22-client.txt](https://github.com/mezz/JustEnoughItems/files/1801727/crash-2018-03-12_00.16.22-client.txt)

**Comment by LeonFulgor** [comment]
https://gist.github.com/LeonFulgor/c599078066e23dc827f769be7f311a7e
Here is the gist of the client latest log too.

**Comment by mezz** [comment]
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`

`Memory: 483845504 bytes (461 MB) / 2863661056 bytes (2731 MB) up to 2863661056 bytes (2731 MB)`

Try allocating more ram to Java, or remove some mods.

**Comment by PayThePizzo** [comment]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 11/11/18 12:10 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:61)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:67)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1901303296 bytes (1813 MB) / 2415919104 bytes (2304 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 7 total; -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID             | Version      | Source                                        | Signature                                |
	|:------- |:-------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft      | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJA  | mcp            | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJA  | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge          | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | codechickenlib | 3.2.2.353    | CodeChickenLib.jar                            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | jei            | 4.12.0.216   | jei.jar                                       | None                                     |
	| UCHIJEE | nei            | 2.4.1        | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 

As you see I still a have a problem with NEI (1.12.2-2.4.1.233-universal).
I installed both Code Chicken Lib, JEI and they are updated to the right compatible version
I gave it 4G of ram instead of only 2G 
I do not have anymore mods installed apart from those who are required for Forge and JEI, CCL and NEI
I do not what I need to change in order to make it work

**Comment by mezz** [comment]
@PayThePizzo Please open a new issue instead of replying to a closed one.
You can report NEI issues here: 
https://github.com/TheCBProject/NotEnoughItems/issues

**Comment by AnEvasivePotato** [comment]
I am getting the same issue, but my computer has more RAM than recommended

**Comment by Sapphire-Star22** [comment]
i dont know anything about what goes on inside of mods but this is a random guess, maybe it's too many items for jei to handle?
