### ISSUE TITLE
Jei is crashing is there a way I could change fix the issue with jei and nei

### ISSUE THREAD

**Issue by TurtleTechv2** [mezz/JustEnoughItems#1183]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/8/18 12:54 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeWrapper.<init>(TransposerRecipeWrapper.java:67)
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeCategoryFill.addFillRecipe(TransposerRecipeCategoryFill.java:74)
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeCategoryFill.getRecipes(TransposerRecipeCategoryFill.java:53)
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeCategoryFill.initialize(TransposerRecipeCategoryFill.java:37)
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeCategory.initialize(TransposerRecipeCategory.java:40)
	at cofh.thermalexpansion.plugins.jei.JEIPluginTE.register(JEIPluginTE.java:110)
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:175)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:60)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:118)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 45487864 bytes (43 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2652 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version           | Source                                              | Signature                                |
	|:------ |:------------------- |:----------------- |:--------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2            | minecraft.jar                                       | None                                     |
	| UCHIJA | mcp                 | 9.42              | minecraft.jar                                       | None                                     |
	| UCHIJA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.2.2652.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.2.2652      | forge-1.12.2-14.23.2.2652.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | appliedenergistics2 | rv5-stable-11     | appliedenergistics2-rv5-stable-11.jar               | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2337        | BiomesOPlenty-1.12.2-7.0.1.2337-universal.jar       | None                                     |
	| UCHIJA | guideapi            | 1.12-2.1.5-60     | Guide-API-1.12-2.1.5-60 (1).jar                     | None                                     |
	| UCHIJA | bloodmagic          | 1.12.2-2.2.8-91   | BloodMagic-1.12.2-2.2.8-91.jar                      | None                                     |
	| UCHIJA | codechickenlib      | 3.1.6.339         | CodeChickenLib-1.12.2-3.1.6.339-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | redstoneflux        | 2.0.1             | RedstoneFlux-1.12-2.0.1.2-universal (3).jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJA | cofhcore            | 4.3.11            | CoFHCore-1.12.2-4.3.11.6-universal (1).jar          | None                                     |
	| UCHIJA | cofhworld           | 1.1.1             | CoFHWorld-1.12.2-1.1.1.12-universal (1).jar         | None                                     |
	| UCHIJA | customnpcs          | 1.12              | CustomNPCs_1.12.2(20jan18).jar                      | None                                     |
	| UCHIJA | lootablebodies      | 2.4.0             | DrCyanosLootableBodies_1.12-2.4.0.jar               | None                                     |
	| UCHIJE | jei                 | 4.8.5.159         | jei_1.12.2-4.8.5.159.jar                            | None                                     |
	| UCHIJA | mantle              | 1.12-1.3.1.21     | Mantle-1.12-1.3.1.21 (1).jar                        | None                                     |
	| UCHIJA | tconstruct          | 1.12.2-2.9.1.65   | TConstruct-1.12.2-2.9.1.65 (1).jar                  | None                                     |
	| UCHIJA | extrautils2         | 1.0               | extrautils2-1.12-1.7.5 (1).jar                      | None                                     |
	| UCHIJA | ic2                 | 2.8.73-ex112      | industrialcraft-2-2.8.73-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA | forestry            | 5.8.0.263         | forestry_1.12.2-5.8.0.263 (1).jar                   | None                                     |
	| UCHIJA | cfm                 | 4.2.0             | furniture-4.2.0-1.12.2.jar                          | None                                     |
	| UCHIJA | ironchest           | 1.12.2-7.0.40.824 | ironchest-1.12.2-7.0.40.824 (1).jar                 | None                                     |
	| UCHIJA | lootbags            | 2.5.4b            | LootBags-1.12.2-2.5.4b.jar                          | None                                     |
	| UCHIJA | radixcore           | 1.12.x-2.2.1      | RadixCore-1.12.x-2.2.1-universal.jar                | None                                     |
	| UCHIJA | mca                 | 1.12.2-5.3.1      | MCA-1.12.x-5.3.1-universal.jar                      | None                                     |
	| UCHIJE | nei                 | 2.4.1             | NotEnoughItems-1.12.2-2.4.1.233-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | harvestcraft        | 1.12.2t           | Pam's+HarvestCraft+1.12.2t (1).jar                  | None                                     |
	| UCHIJA | thermalfoundation   | 2.3.11            | ThermalFoundation-1.12.2-2.3.11.8-universal (1).jar | None                                     |
	| UCHIJA | thermalexpansion    | 5.3.11            | ThermalExpansion-1.12.2-5.3.11.14-universal.jar     | None                                     |
	| UCHIJA | twilightforest      | 3.6.345           | twilightforest-1.12.2-3.6.345-universal (1).jar     | None                                     |
	| UCHIJA | xaerominimap        | 1.14.9.1          | Xaeros_Minimap_1.14.9.1_Forge_1.12.jar              | None                                     |

	Loaded coremods (and transformers): 
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF

**Comment by TehNut** [comment]
>Memory: 45487864 bytes (43 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)

You are only allocating 1Gb of RAM so you are running out. You need to allocate more.

**Comment by TurtleTechv2** [comment]
how do i allocate more?

**Comment by BenjaminUrquhart** [comment]
https://www.wikihow.com/Allocate-More-RAM-to-Minecraft
