### ISSUE TITLE
Crash upon startup

### ISSUE THREAD

**Issue by Zenvioux** [mezz/JustEnoughItems#1259]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: mezz.jei.input.MouseHelper

Crashlog: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.7.1.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.3-universal.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 6/10/18 10:34 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: mezz.jei.input.MouseHelper
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:602)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:225)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mezz.jei.input.MouseHelper
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	... 36 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 69929240 bytes (66 MB) / 352321536 bytes (336 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_D3 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID               | Version          | Source                                         | Signature                                |
	|:----- |:---------------- |:---------------- |:---------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft        | 1.12.2           | minecraft.jar                                  | None                                     |
	| UC    | mcp              | 9.42             | minecraft.jar                                  | None                                     |
	| UC    | FML              | 8.0.99.99        | forge-1.12.2-14.23.4.2705.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge            | 14.23.4.2705     | forge-1.12.2-14.23.4.2705.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | bibliocraft      | 2.4.3            | BiblioCraft-Mod-1.12.jar                       | None                                     |
	| UC    | biomesoplenty    | 7.0.1.2297       | BiomesOPlenty-1.12.2-7.0.1.2297-universal.jar  | None                                     |
	| UC    | cavern           | 2.1.6            | Cavern-1.12.2.jar                              | None                                     |
	| UC    | codechickenlib   | 3.1.9.344        | CodeChickenLib-1.12.2-3.1.9.344-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | chickenchunks    | 2.4.0.70         | ChickenChunks-1.12-2.4.0.70-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | extendedrenderer | v1.0             | coroutil-1.12.1-1.1.20.jar                     | None                                     |
	| UC    | coroutil         | 1.12.1-1.1.20    | coroutil-1.12.1-1.1.20.jar                     | None                                     |
	| UC    | configmod        | v1.0             | coroutil-1.12.1-1.1.20.jar                     | None                                     |
	| UC    | craftstudioapi   | 1.0.0            | CraftStudio-1.0.0.93-mc1.12-alpha.jar          | None                                     |
	| UC    | customspawner    | 3.11.4           | CustomMobSpawner-3.11.4.jar.zip                | None                                     |
	| UC    | torohealthmod    | 1.12.2-11        | Damage-Indicators-1.12.2.jar                   | None                                     |
	| UC    | mocreatures      | 12.0.4           | DrZharks MoCreatures Mod-12.0.4.jar.zip        | None                                     |
	| UC    | gottschcore      | 1.3.5            | GottschCore-mc1.12-f14.21.1.2387-v1.3.5.jar    | None                                     |
	| UC    | dungeons2        | 1.3.2            | Dungeons2-mc1.12.2-f14.23.1.2555-v1.3.2.jar    | None                                     |
	| UC    | fastleafdecay    | v14              | FastLeafDecay-v14.jar                          | None                                     |
	| UC    | forgelin         | 1.7.1            | Forgelin-1.7.1.jar                             | None                                     |
	| UC    | harvestcraft     | 1.12.1c          | HarvestCraft-Mod-1.12.2.jar                    | None                                     |
	| UC    | ichunutil        | 7.1.4            | iChunUtil-1.12.2-7.1.4.jar                     | None                                     |
	| UC    | hats             | 7.0.0            | Hats-1.12.2-7.0.2.jar                          | None                                     |
	| UC    | hatstand         | 7.0.0            | HatStand-1.12.2-7.0.1.jar                      | None                                     |
	| UC    | ic2              | 2.8.16-ex112     | Industrial-Craft-2-Mod-Experimental-1.12.1.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| UE    | jei              | 4.9.2.196        | jei_1.12.2-4.9.2.196.jar                       | None                                     |
	| U     | journeymap       | 1.12.2-5.5.0rc1  | JourneyMap-Mod-1.12.2-Unlimited.jar            | None                                     |
	| U     | lostcities       | 2.0.5            | lostcities-1.12-2.0.5.jar                      | None                                     |
	| U     | mantle           | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24.jar                       | None                                     |
	| U     | radixcore        | 1.12.x-2.2.1     | RadixCore-1.12.2.jar                           | None                                     |
	| U     | mca              | 1.12.2-5.3.1     | MCA-1.12.x-5.3.1-universal.jar                 | None                                     |
	| U     | millenaire       | Millénaire 6.2.4 | millenaire-6.2.4.jar                           | None                                     |
	| U     | moarboats        | 1.2.1            | moarboats-1.12.2-1.2.1.jar                     | None                                     |
	| U     | mobultion        | 0.4.1            | mobultion-1.12.2.jar                           | None                                     |
	| U     | nei              | 2.4.1            | NotEnoughItems-1.12.2-2.4.1.233-universal.jar  | None                                     |
	| U     | sereneseasons    | 1.2.3            | SereneSeasons-1.12.2-1.2.3-universal.jar       | None                                     |
	| U     | tconstruct       | 1.12.2-2.10.1.84 | TConstruct-1.12.2-2.10.1.84.jar                | None                                     |
	| U     | toughasnails     | 3.1.0.115        | ToughAsNails-1.12.2-3.1.0.115-universal.jar    | None                                     |
	| U     | bspkrscore       | at_0.9           | TreeCapitator-Mod-1.12.jar                     | None                                     |
	| U     | treecapitator    | at_0.9           | TreeCapitator-Mod-1.12.jar                     | None                                     |
	| U     | weather2         | 1.12.1-2.5       | Weather-Storms-Tornadoes-Mod-1.12.2.jar        | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.7.1.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.3-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.41' Renderer: 'GeForce GTX 760/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.5.0 NVIDIA 385.41
	OpenGlRenderer: GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by TehNut** [comment]
#1258
