### ISSUE TITLE
CME when changing  GUI

### ISSUE THREAD

**Issue by raoulvdberge** [mezz/JustEnoughItems#1304]
This happens when changing a GUI with `FMLClientHandler.instance().showGuiScreen()` in a `Container`.

No clue why it happens :)

https://gist.github.com/raoulvdberge/9f871e5eb47921f4e25e32c7fd48d351

**Comment by mezz** [comment]
Hm this is probably not caused by the stack trace here (which is on the main thread).
Please try with this custom build of JEI that adds some more paranoid error checking, and report back the new stack trace you get:
[jei_1.12.2-4.11.0.jar.zip](https://github.com/mezz/JustEnoughItems/files/2217562/jei_1.12.2-4.11.0.jar.zip)

**Comment by raoulvdberge** [comment]
Ah, that error makes sense.
```
[12:16:57] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$InitGuiEvent$Post@879c601:
java.lang.IllegalStateException: A JEI API method is being called by another mod from the wrong thread. It must be called on the main thread.
	at mezz.jei.util.ErrorUtil.assertMainThread(ErrorUtil.java:229) ~[ErrorUtil.class:?]
	at mezz.jei.render.IngredientListBatchRenderer.clear(IngredientListBatchRenderer.java:35) ~[IngredientListBatchRenderer.class:?]
	at mezz.jei.gui.overlay.IngredientGrid.updateBounds(IngredientGrid.java:64) ~[IngredientGrid.class:?]
	at mezz.jei.gui.overlay.IngredientGridAll.updateBounds(IngredientGridAll.java:74) ~[IngredientGridAll.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.updateScreen(IngredientListOverlay.java:158) ~[IngredientListOverlay.class:?]
	at mezz.jei.gui.GuiEventHandler.onGuiInit(GuiEventHandler.java:36) ~[GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_93_GuiEventHandler_onGuiInit_Post.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:545) [GuiScreen.class:?]
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1096) [Minecraft.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:495) [FMLClientHandler.class:?]
	at com.raoulvdberge.refinedstorage.container.ContainerBase.slotClick(ContainerBase.java:95) [ContainerBase.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processClickWindow(NetHandlerPlayServer.java:1220) [NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:47) [CPacketClickWindow.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:12) [CPacketClickWindow.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) [PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_131]
	at net.minecraft.util.Util.runTask(Util.java:53) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[12:16:57] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[12:16:57] [Server thread/ERROR] [FML]: 0: NORMAL
[12:16:57] [Server thread/ERROR] [FML]: 1: ASM: class mezz.jei.input.MouseHelper onGuiInit(Lnet/minecraftforge/client/event/GuiScreenEvent$InitGuiEvent$Post;)V
[12:16:57] [Server thread/ERROR] [FML]: 2: ASM: mezz.jei.gui.GuiEventHandler@15b9b8e4 onGuiInit(Lnet/minecraftforge/client/event/GuiScreenEvent$InitGuiEvent$Post;)V
[12:16:57] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: A JEI API method is being called by another mod from the wrong thread. It must be called on the main thread.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalStateException: A JEI API method is being called by another mod from the wrong thread. It must be called on the main thread.
	at mezz.jei.util.ErrorUtil.assertMainThread(ErrorUtil.java:229) ~[ErrorUtil.class:?]
	at mezz.jei.render.IngredientListBatchRenderer.clear(IngredientListBatchRenderer.java:35) ~[IngredientListBatchRenderer.class:?]
	at mezz.jei.gui.overlay.IngredientGrid.updateBounds(IngredientGrid.java:64) ~[IngredientGrid.class:?]
	at mezz.jei.gui.overlay.IngredientGridAll.updateBounds(IngredientGridAll.java:74) ~[IngredientGridAll.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.updateScreen(IngredientListOverlay.java:158) ~[IngredientListOverlay.class:?]
	at mezz.jei.gui.GuiEventHandler.onGuiInit(GuiEventHandler.java:36) ~[GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_93_GuiEventHandler_onGuiInit_Post.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:545) ~[GuiScreen.class:?]
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1096) ~[Minecraft.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:495) ~[FMLClientHandler.class:?]
	at com.raoulvdberge.refinedstorage.container.ContainerBase.slotClick(ContainerBase.java:95) ~[ContainerBase.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processClickWindow(NetHandlerPlayServer.java:1220) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:47) ~[CPacketClickWindow.class:?]
	at net.minecraft.network.play.client.CPacketClickWindow.processPacket(CPacketClickWindow.java:12) ~[CPacketClickWindow.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_131]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more
```

**Comment by raoulvdberge** [comment]
Fixed by https://github.com/raoulvdberge/refinedstorage/commit/b3f4109ffa708f5303862a2de6bfc3eee0d6c3ea

Thank you for your time!

**Comment by mezz** [comment]
Any time man! 

`NetHandlerPlayServer#processClickWindow` starts with `PacketThreadUtil.checkThreadAndEnqueue` which should make it run on the main thread, right?
I guess the thread check there must be a bit different on an integrated server since there's a server thread and client thread kinda working together with blurry network boundaries... yikes.

**Comment by raoulvdberge** [comment]
After some testing, it appears my approach was wrong in the first place. Slotclick doesn't get called in multiplayer on the client, so I'm calling it now in Gui onSlotClicked or whatever it's called there :)

**Comment by mezz** [comment]
Ah ok, that makes more sense!
