### ISSUE TITLE
Crash when I search recipe (for steel bend and more)

### ISSUE THREAD

**Issue by N4TH4NOT** [mezz/JustEnoughItems#1334]
When I try to have the recipe of steel blend and some other item the game crash...

Description: 
CCL Has caught an exception whilst rendering an item.
  Item Class:     cofh.thermalfoundation.block.ItemBlockGlassAlloy
  Registry Name:  thermalfoundation:glass_alloy
  Metadata:       0
  NBT:            null
  Model Class:    class net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1
  Model Location: thermalfoundation:glass_alloy#type=steel
You can turn off player messages in the CCL config file.
If you want CCL to attempt to recover the game next time, enable it in the CCL config.

java.lang.ClassCastException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap cannot be cast to gnu.trove.map.hash.TIntObjectHashMap
	at team.chisel.ctm.client.model.ModelUtil.lambda$getMesh$0(ModelUtil.java:51)
	at team.chisel.ctm.client.model.ModelUtil$$Lambda$2213/1033715537.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at team.chisel.ctm.client.model.ModelUtil.getMesh(ModelUtil.java:51)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.handleItemState(AbstractCTMBakedModel.java:84)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:960)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:399)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:396)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:337)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:28)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21)
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:165)
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:154)
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:164)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:215)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:653)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at team.chisel.ctm.client.model.ModelUtil.lambda$getMesh$0(ModelUtil.java:51)
	at team.chisel.ctm.client.model.ModelUtil$$Lambda$2213/1033715537.apply(Unknown Source)
	at java.util.Optional.map(Optional.java:215)
	at team.chisel.ctm.client.model.ModelUtil.getMesh(ModelUtil.java:51)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel$Overrides.handleItemState(AbstractCTMBakedModel.java:84)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.call(Reflector.java:960)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:399)

-- Item being rendered --
Details:
	Item Type: cofh.thermalfoundation.block.ItemBlockGlassAlloy@2a8aabae
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:191)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:346)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:28)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21)
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:165)
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:154)
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:164)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:215)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:653)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Ingredient being rendered --
Details:
	Ingredient Mod: Thermal Foundation
	Ingredient Info: 1xtile.thermalfoundation.glass@0 thermalfoundation:glass_alloy

**Comment by TehNut** [comment]
This was an issue with CTM and it is fixed now.
