### ISSUE TITLE
Crashing when mod loads. URGENT!

### ISSUE THREAD

**Issue by rhysperry111** [mezz/JustEnoughItems#1341]
My game crashes when i click any button on the main menu.

Here is my crash report:
```
----  Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 8/23/18 5:47 PM
Description: Updating screen events

java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;
	at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:124)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_599_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:124)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_599_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 333026144 bytes (317 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2758 Optifine OptiFine_1.12.2_HD_U_C9 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version         | Source                                             | Signature                                |
	|:------ |:------------------- |:--------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2          | minecraft.jar                                      | None                                     |
	| UCHIJA | mcp                 | 9.42            | minecraft.jar                                      | None                                     |
	| UCHIJA | FML                 | 8.0.99.99       | forge-1.12.2-14.23.4.2758.jar                      | None                                     |
	| UCHIJA | forge               | 14.23.4.2758    | forge-1.12.2-14.23.4.2758.jar                      | None                                     |
	| UCHIJA | micdoodlecore       |                 | minecraft.jar                                      | None                                     |
	| UCHIJA | appliedenergistics2 | rv5-stable-11   | Applied-Energistics-2-Mod-1.12.2.jar               | None                                     |
	| UCHIJA | baubles             | 1.5.2           | Baubles-1.12-1.5.2.jar                             | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2399      | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar      | None                                     |
	| UCHIJA | guideapi            | 1.12-2.1.7-62   | Guide-API-1.12-2.1.7-62.jar                        | None                                     |
	| UCHIJA | bloodmagic          | 1.12.2-2.3.1-99 | BloodMagic-1.12.2-2.3.1-99.jar                     | None                                     |
	| UCHIJA | codechickenlib      | 3.2.1.351       | CodeChickenLib-1.12.2-3.2.1.351-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | redstoneflux        | 2.0.2           | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJA | brandonscore        | 2.4.4           | BrandonsCore-1.12.2-2.4.4.173-universal.jar        | None                                     |
	| UCHIJA | buildcraftlib       | 7.99.17         | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJA | buildcraftcore      | 7.99.17         | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJA | buildcraftbuilders  | 7.99.17         | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJA | buildcraftenergy    | 7.99.17         | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJA | buildcraftfactory   | 7.99.17         | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJA | buildcraftrobotics  | 7.99.17         | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJA | buildcrafttransport | 7.99.17         | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJA | buildcraftsilicon   | 7.99.17         | buildcraft-7.99.17.jar                             | None                                     |
	| UCHIJA | computercraft       | 1.80pr1         | ComputerCraft-Mod-1.12.1.jar                       | None                                     |
	| UCHIJA | ptrmodellib         | 1.0.0           | Decocraft-2.5.5_1.12.2.jar                         | None                                     |
	| UCHIJA | props               | 2.5.5           | Decocraft-2.5.5_1.12.2.jar                         | None                                     |
	| UCHIJA | draconicevolution   | 2.3.13          | Draconic-Evolution-1.12.2-2.3.13.306-universal.jar | None                                     |
	| UCHIJA | extremeanimals      | 1.0.2.1         | ExtremeAnimals-1.0.2.1-1.12.2.jar                  | None                                     |
	| UCHIJA | jei                 | 4.12.0.215      | jei_1.12.2-4.12.0.215.jar                          | None                                     |
	| UCHIJA | forestry            | 5.8.0.291       | forestry_1.12.2-5.8.0.291.jar                      | None                                     |
	| UCHIJA | galacticraftcore    | 4.0.1.181       | GalacticraftCore-1.12.2-4.0.1.181.jar              | None                                     |
	| UCHIJA | galacticraftplanets | 4.0.1.181       | Galacticraft-Planets-1.12.2-4.0.1.181.jar          | None                                     |
	| UCHIJA | waila               | 1.8.26          | Hwyla-Mod-1.12.2.jar                               | None                                     |
	| UCHIJA | ichunutil           | 7.1.4           | iChunUtil-1.12.2-7.1.4.jar                         | None                                     |
	| UCHIJA | hats                | 7.0.0           | iChuns-Hats-Mod-1.12.2.jar                         | None                                     |
	| UCHIJA | journeymap          | 1.12.2-5.5.2    | journeymap-1.12.2-5.5.2.jar                        | None                                     |
	| UCHIJA | mocreatures         | 12.0.5          | Mo-Creatures-Mod-1.12.2.jar                        | None                                     |
	| UCHIJA | morph               | 7.1.0           | Morphing-Mod-1.12.2.jar                            | None                                     |
	| UCHIJA | nei                 | 2.4.1           | Not-Enough-Items-1.12.2-Recommended.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | harvestcraft        | 1.12.2y         | Pam's+HarvestCraft+1.12.2y.jar                     | None                                     |
	| UCHIJA | thaumcraft          | 6.1.BETA21      | Thaumcraft-Mod-1.12.2.jar                          | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-1.68.20' Renderer: 'AMD Radeon HD 6770M OpenGL Engine'
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2758
	LWJGL: 2.9.2
	OpenGL: AMD Radeon HD 6770M OpenGL Engine GL version 2.1 ATI-1.68.20, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 ATI-1.68.20
	OpenGlRenderer: AMD Radeon HD 6770M OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```
I need this fixed as I need it ready for my pack-update in a week

**Comment by TehNut** [comment]
This is an NEI issue

**Comment by mezz** [comment]
See https://github.com/TheCBProject/NotEnoughItems/issues/170
