### ISSUE TITLE
JEI crashes when opening inventory

### ISSUE THREAD

**Issue by MIWAsan23** [mezz/JustEnoughItems#1360]
Hallo

my world was working fine, can't explain what happened or due to what change JEI started crashing. No changes in mods during this period. 

Each time i open a machines GUI or just the inventory, so each time JEI displays the game crashes. 

After removing JEI all works fine, but gaming without JEI isn't really fun....
Anybody a clue?

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  RandomPatches (randompatches-1.12.2-1.2.0.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.8.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CorePlugin (SmoothFont-1.12.2-1.15.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 9/10/18 10:25 PM
Description: Rendering ingredient

java.lang.ClassCastException: noppes.npcs.api.wrapper.ItemBlockWrapper cannot be cast to noppes.npcs.api.wrapper.ItemScriptedWrapper
	at noppes.npcs.items.ItemScripted.GetWrapper(ItemScripted.java:39)
	at noppes.npcs.items.ItemScripted.showDurabilityBar(ItemScripted.java:46)
	at net.minecraft.client.renderer.RenderItem.func_180453_a(RenderItem.java:406)
	at mezz.jei.render.ItemStackFastRenderer.renderOverlay(ItemStackFastRenderer.java:117)
	at mezz.jei.render.ItemStackFastRenderer.renderOverlay(ItemStackFastRenderer.java:108)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:181)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:94)
	at mezz.jei.gui.overlay.IngredientGridAll.draw(IngredientGridAll.java:89)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:176)
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:70)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1666_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:369)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at noppes.npcs.items.ItemScripted.GetWrapper(ItemScripted.java:39)
	at noppes.npcs.items.ItemScripted.showDurabilityBar(ItemScripted.java:46)
	at net.minecraft.client.renderer.RenderItem.func_180453_a(RenderItem.java:406)

-- Ingredient being rendered --
Details:
	Ingredient Mod: CustomNPCs
	Ingredient Info: 1xitem.scripted_item@0 customnpcs:scripted_item
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:241)
	at mezz.jei.render.ItemStackFastRenderer.renderOverlay(ItemStackFastRenderer.java:110)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:181)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:94)
	at mezz.jei.gui.overlay.IngredientGridAll.draw(IngredientGridAll.java:89)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:176)
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:70)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1666_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:369)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by mezz** [comment]
Thanks for the report!
This looks like an issue with CustomNPCs, please report to them on their Discord (I guess they have no real issue tracker): https://discord.gg/EjHKbVQ

**Comment by MIWAsan23** [comment]
tried a few things to fix this.  removed CustomNPCs but still the same issue. 
added NEI and it suddenly worked. no clue why, but maybe you would like to know :)
