### ISSUE TITLE
Crash: Updating screen events

### ISSUE THREAD

**Issue by TomberWolf** [mezz/JustEnoughItems#1372]
With the latest jei_1.12.2-4.12.1.217

```
Description: Updating screen events

java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;
	at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:125)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1237_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by temp1011** [comment]
https://github.com/TheCBProject/NotEnoughItems/issues/170
