### ISSUE TITLE
Crash on clicking singleplayer

### ISSUE THREAD

**Issue by JupiterYourHero** [mezz/JustEnoughItems#1375]
java.lang.NoSuchMethodError: mezz.jei.runtime.JeiRuntime.getItemListOverlay()Lmezz/jei/gui/overlay/IngredientListOverlay;
	at codechicken.nei.jei.JEIIntegrationManager.getTextFieldFilter(JEIIntegrationManager.java:124)
	at codechicken.nei.jei.gui.ContainerEventHandler.onGuiMouseEventpre(ContainerEventHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_736_ContainerEventHandler_onGuiMouseEventpre_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by mezz** [comment]
Thanks for the report!
Please update NEI, it is an issue with an old version: https://github.com/TheCBProject/NotEnoughItems/issues/170
