### ISSUE TITLE
JEI/NEI

### ISSUE THREAD

**Issue by KingFishy492** [mezz/JustEnoughItems#1378]
no clue if this is where i am meant to be putting this but as you can see JEI is crashing no matter what mods are in with it even if its jsut in with codechickenlib NEI JEI these are the items needed for it to run at all if any the way its "meant to" any suggestions on why this is happning?

---- Minecraft Crash Report ----
// There are four lights!

Time: 10/7/18 7:11 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.IllegalArgumentException: recipeCategories must not be empty.
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:206)
	at mezz.jei.gui.ingredients.IngredientLookupState.<init>(IngredientLookupState.java:23)
	at mezz.jei.gui.recipes.RecipeGuiLogic.<init>(RecipeGuiLogic.java:40)
	at mezz.jei.gui.recipes.RecipesGui.<init>(RecipesGui.java:86)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:86)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:120)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 159131104 bytes (151 MB) / 389283840 bytes (371 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID             | Version      | Source                                        | Signature                                |
	|:------- |:-------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft      | 1.12.2       | minecraft.jar                                 | None                                     |
	| UCHIJA  | mcp            | 9.42         | minecraft.jar                                 | None                                     |
	| UCHIJA  | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge          | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | codechickenlib | 3.2.2.353    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJEE | jei            | 4.13.1.220   | jei_1.12.2-4.13.1.220.jar                     | None                                     |
	| UCHIJ   | nei            | 2.4.1        | NotEnoughItems-1.12.2-2.4.1.239-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 411.63' Renderer: 'GeForce GTX 965M/PCIe/SSE2'

**Comment by way2muchnoise** [comment]
NEI and codecickenlib are not needed to run JEI. Does this happen with just JEI?

**Comment by KingFishy492** [comment]
> NEI and codecickenlib are not needed to run JEI. Does this happen with just JEI?

JEI works without them yes but to get NEI working it said i needed both of the other 2 items and JEI was the last thing i had to get but after i added JEI to the table it jsut crashes everytime i try and laod it up

**Comment by way2muchnoise** [comment]
Then it sounds like something you should report t https://github.com/TheCBProject/NotEnoughItems/issues

**Comment by mezz** [comment]
Thanks for the report!
Please report to NEI.
