### ISSUE TITLE
Minecraft is crashing when i load up chickencore and jei 

### ISSUE THREAD

**Issue by lewdxd** [mezz/JustEnoughItems#1403]
Minecraft crashes when i try to open minecraft with not enough items and just enough items

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Oops.

Time: 11/21/18 1:58 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:60)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:70)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 322579120 bytes (307 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                  | Version          | Source                                  | Signature                                |
	|:------- |:------------------- |:---------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft           | 1.12.2           | minecraft.jar                           | None                                     |
	| UCHIJA  | mcp                 | 9.42             | minecraft.jar                           | None                                     |
	| UCHIJA  | FML                 | 8.0.99.99        | forge-1.12.2-14.23.5.2768.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge               | 14.23.5.2768     | forge-1.12.2-14.23.5.2768.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | jei                 | 4.13.1.222       | jei_1.12.2-4.13.1.222.jar               | None                                     |
	| UCHIJA  | abyssalcraft        | 1.9.4.14         | AbyssalCraft-1.12.2-1.9.4.14.jar        | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJA  | advancedcombat      | 1.1.2            | advancedcombat-1.1.2-[1.12].jar         | None                                     |
	| UCHIJA  | aether_legacy       | 1.12.2-v3.2      | aether_legacy-1.12.2-v3.2.jar           | None                                     |
	| UCHIJA  | guideapi            | 1.12-2.1.7-62    | Guide-API-1.12-2.1.7-62.jar             | None                                     |
	| UCHIJA  | bloodmagic          | 1.12.2-2.3.3-101 | BloodMagic-1.12.2-2.3.3-101.jar         | None                                     |
	| UCHIJA  | classiccombat       | 1.0.0            | ClassicCombat-1.12-1.0.0.jar            | None                                     |
	| UCHIJA  | codechickenlib      | 3.2.2.353        | CodeChickenLib-1.12.2.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | eleccore            | 1.8.434          | ElecCore-1.12.2-1.8.434.jar             | None                                     |
	| UCHIJA  | mcjtylib_ng         | 3.0.7            | mcjtylib-1.12-3.0.7.jar                 | None                                     |
	| UCHIJA  | elementaldimensions | 0.3.1            | elementaldimensions-1.12-0.3.1.jar      | None                                     |
	| UCHIJEE | nei                 | 2.4.1            | Not-Enough-Items-1.12.2-Recommended.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.94' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.94
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by mezz** [comment]
Thanks for the report!
Please report NEI issues here: https://github.com/TheCBProject/NotEnoughItems/issues
