### ISSUE TITLE
#513 Regression; Shift-clicking into a Slice'N'Splice results in voided items

### ISSUE THREAD

**Issue by Vectrobe** [mezz/JustEnoughItems#1412]
EnderIO; 5.0.37
JEI; 1.5.1.36

Shift-clicking the recipe causes stacks of 2+ to be inserted instead of stacks of 1, the machine then proceeds to void the itemstacks completely with the below stacktrace;
```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Invalid stacksize. 2 is more than the allowed limit of 1. THIS IS NOT AN ERROR IN ENDER IO BUT THE CALLING MOD!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.RuntimeException: Invalid stacksize. 2 is more than the allowed limit of 1. THIS IS NOT AN ERROR IN ENDER IO BUT THE CALLING MOD!
	at crazypants.enderio.machines.machine.tank.InventorySlot.func_75215_d(InventorySlot.java:24) ~[InventorySlot.class:?]
	at mezz.jei.transfer.BasicRecipeTransferHandlerServer.setItems(BasicRecipeTransferHandlerServer.java:64) ~[BasicRecipeTransferHandlerServer.class:?]
	at mezz.jei.network.packets.PacketRecipeTransfer.readPacketData(PacketRecipeTransfer.java:81) ~[PacketRecipeTransfer.class:?]
	at mezz.jei.network.PacketHandler$$Lambda$416/744139883.readPacketData(Unknown Source) ~[?:?]
	at mezz.jei.network.PacketHandler.lambda$checkThreadAndEnqueue$0(PacketHandler.java:56) ~[PacketHandler.class:?]
	at mezz.jei.network.PacketHandler$$Lambda$4526/197295693.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by Vectrobe** [comment]
previous report; #513
