### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Crezey21** [mezz/JustEnoughItems#1457]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCore (MovingWorld-Mod-1.12.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 1/10/19 5:50 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:60)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:70)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 173386376 bytes (165 MB) / 494837760 bytes (471 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                                           | Version       | Source                         | Signature                                |
	|:------- |:-------------------------------------------- |:------------- |:------------------------------ |:---------------------------------------- |
	| UCHIJA  | minecraft                                    | 1.12.2        | minecraft.jar                  | None                                     |
	| UCHIJA  | mcp                                          | 9.42          | minecraft.jar                  | None                                     |
	| UCHIJA  | FML                                          | 8.0.99.99     | forge-1.12.2-14.23.5.2768.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge                                        | 14.23.5.2768  | forge-1.12.2-14.23.5.2768.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | com.elytradev.movingworld.common.asm.coremod |               | minecraft.jar                  | None                                     |
	| UCHIJA  | aether_legacy                                | 1.12.2-v3.2   | AetherLegacy-Mod-1.12.jar      | None                                     |
	| UCHIJA  | codechickenlib                               | 3.2.2.353     | CodeChickenLib-Mod-1.12.2.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | movingworld                                  | 1.12-6.342    | MovingWorld-Mod-1.12.jar       | None                                     |
	| UCHIJA  | davincisvessels                              | @DVESSELSVER@ | DavincisVessels-Mod-1.12.jar   | None                                     |
	| UCHIJA  | jei                                          | 4.12.0.214    | JustEnoughItems-Mod-1.12.2.jar | None                                     |
	| UCHIJEE | nei                                          | 2.4.1         | NotEnoughItems-Mod-1.12.2.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ   | orespawn                                     | 3.3.0         | OreSpawn-Mod-1.12.2.jar        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJ   | supertnt                                     | 1.0.1         | SuperTNT-Mod-1.12.2.jar        | None                                     |
	| UCHIJ   | twilightforest                               | 3.8.689       | TwilightForest-Mod-1.12.2.jar  | None                                     |
	| UCHIJ   | veinminer                                    | 0.38.2        | VeinMiner-Mod-1.12.jar         | None                                     |
	| UCHIJ   | veinminermodsupport                          | 0.38.2        | VeinMiner-Mod-1.12.jar         | None                                     |

	Loaded coremods (and transformers): 
MovingWorldCore (MovingWorld-Mod-1.12.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13543 Compatibility Profile Context 25.20.15002.58' Renderer: 'Radeon RX 580 Series'

**Comment by mezz** [comment]
Thanks for the report!
`Caught exception from Not Enough Items (nei)`
Please report this to NEI here: https://github.com/TheCBProject/NotEnoughItems/issues
