### ISSUE TITLE
1.13.2 Just Forge and New Mod

### ISSUE THREAD

**Issue by ketpain** [mezz/JustEnoughItems#1512]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 3/16/19 7:20 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer.texture.TextureMap.field_195427_i from class mezz.jei.gui.textures.JeiTextureMap
	at mezz.jei.gui.textures.JeiTextureMap.registerSprite(JeiTextureMap.java:52)
	at mezz.jei.gui.textures.Textures.registerSprite(Textures.java:70)
	at mezz.jei.gui.textures.Textures.<init>(Textures.java:39)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:99)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$1437/213502417.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:201)
	at net.minecraftforge.eventbus.EventBus$$Lambda$1343/674253597.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:257)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.texture.TextureMap.func_195426_a(TextureMap.java:47)
	at net.minecraft.client.renderer.model.ModelBakery.func_177570_a(ModelBakery.java:320)
	at net.minecraft.client.renderer.model.ModelManager.func_195410_a(ModelManager.java:25)
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199006_a(SimpleReloadableResourceManager.java:114)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:456)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:344)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$279/502848122.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:56)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:42)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.gui.textures.JeiTextureMap.registerSprite(JeiTextureMap.java:52)
	at mezz.jei.gui.textures.Textures.registerSprite(Textures.java:70)
	at mezz.jei.gui.textures.Textures.<init>(Textures.java:39)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:99)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$1437/213502417.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:201)
	at net.minecraftforge.eventbus.EventBus$$Lambda$1343/674253597.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:257)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.texture.TextureMap.func_195426_a(TextureMap.java:47)
	at net.minecraft.client.renderer.model.ModelBakery.func_177570_a(ModelBakery.java:320)
	at net.minecraft.client.renderer.model.ModelManager.func_195410_a(ModelManager.java:25)
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199006_a(SimpleReloadableResourceManager.java:114)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:456)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:344)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$279/502848122.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:56)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:42)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 762997688 bytes (727 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Launched Version: 1.13.2-forge-25.0.85
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce RTX 2080/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Faithful+1.13.2-rv2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by mezz** [comment]
Thanks for the report!
JEI uses access transformers to access some private values. If that is not being applied, it will crash like this.
I think this is a ForgeGradle issue, or something to do with the way you have set up the project.

**Comment by Gbergz** [comment]
Was about to report the same issue, glad it's being worked on. 👍

**Comment by Tamaized** [comment]
Having the same issue while adding jei via maven~

**Comment by Tamaized** [comment]
I dug real deep into this and it seems mod ATs do not get applied unless their AT file is named `accesstransformer.cfg`
https://github.com/MinecraftForge/MinecraftForge/blob/1e34f331da1cfee19341fa15ebb55560681a7c8e/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L131

Along with that, it seems ATs wont work in a deobf environment either.
https://github.com/MinecraftForge/AccessTransformers/blob/2b9c7950bfd2e6b654fde244b789727eefaa8bc1/src/main/java/net/minecraftforge/accesstransformer/AccessTransformerEngine.java#L34
`fn.name` here while in a deobf environment returns the mapped name but the `fieldTransformers` uses whatever is defined in each AT cfg file.

I used a test build of jei with the at file rename to get this far:
https://cdn.discordapp.com/attachments/418125698486632448/556912816930684932/unknown.png

I used another test build with both the rename and duplicating each entry with the mapped names and I managed to get passed loading without any issue:
https://cdn.discordapp.com/attachments/418125698486632448/556916074499670120/unknown.png
https://cdn.discordapp.com/attachments/418125698486632448/556915992664604743/unknown.png

**Comment by mezz** [comment]
Please try with JEI version 5.0.0.11, I think this has been fixed.

**Comment by mezz** [comment]
This has been confirmed fixed in the latest versions of Forge and JEI.
