### ISSUE TITLE
JEI plugin is crashing making Mod recipes not show in JEI

### ISSUE THREAD

**Issue by Saereth** [mezz/JustEnoughItems#1521]
This particular issue with with thermal but previously when we were hiding an invalid category crafttweaker it caused the entire crafttweaker plugin to fail as well. original issue reported to Crafttweaker: https://github.com/mezz/JustEnoughItems/issues/1521

https://github.com/CoFH/Feedback/issues/1469
cross posting from TE as I'm not sure which end is best suited to fix it...

JEI version: jei_1.12.2-4.15.0.269
ThermalExpansion-1.12.2-5.5.3.41
forge-14.23.5.2795

for reference;
https://github.com/mezz/JustEnoughItems/issues/1520 may be relevant

In development pack, FTB Interactions, we noticed some JEI recipes weren't showing up and after some digging we found this in the debug log:

```
[20:15:52] [Client thread/ERROR] [jei]: Failed to register mod plugin: class cofh.thermalexpansion.plugins.jei.JEIPluginTE
java.lang.IllegalArgumentException: Must have at least 1 tick per cycle.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-21.0.jar:?]
	at mezz.jei.gui.TickTimer.<init>(TickTimer.java:13) ~[TickTimer.class:?]
	at mezz.jei.gui.elements.DrawableAnimated.<init>(DrawableAnimated.java:36) ~[DrawableAnimated.class:?]
	at mezz.jei.gui.GuiHelper.createAnimatedDrawable(GuiHelper.java:87) ~[GuiHelper.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeWrapper.<init>(PulverizerRecipeWrapper.java:87) ~[PulverizerRecipeWrapper.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeWrapper.<init>(PulverizerRecipeWrapper.java:45) ~[PulverizerRecipeWrapper.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeCategory.getRecipes(PulverizerRecipeCategory.java:66) ~[PulverizerRecipeCategory.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.pulverizer.PulverizerRecipeCategory.initialize(PulverizerRecipeCategory.java:54) ~[PulverizerRecipeCategory.class:?]
	at cofh.thermalexpansion.plugins.jei.JEIPluginTE.register(JEIPluginTE.java:105) ~[JEIPluginTE.class:?]
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:202) [JeiStarter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

so particularly "Must have at least 1 tick per cycle." from the pulverizer recipe wrapper. Interestingly enough we have pulverizer turned off in the configs so I wouldnt assume it should even be registering any recipes for it. At anyrate when the jei plugin fails no thermal recipes show in jei. Since it doesnt give any indication as to what the actual recipe is im not sure if its even one of our recipes from the pack or an autogenerated one from TE that's just broken. I'm assuming its not one of our recipes since its not the Crafttweaker jei plugin failing.

**Comment by Saereth** [comment]
also not sure if its related but since this started happening any custom items we've added with
mods.jei.JEI.addItem() are no longer showing up in jei, we are adding about 30 items and confirmed none are showing up now.

**Comment by mezz** [comment]
Thanks for the report!
Looks like this has been resolved.
It is an issue with a TE recipe, something is trying to create a recipe animation that is so fast that they say it's going to take 0 ticks to animate. A 0 tick animation throws an exception, since there's no way to draw it.

Please open a new issue for any other issues you might be experiencing, I can look into them separately.
