### ISSUE TITLE
[1.13] Crash when reloading texture packs

### ISSUE THREAD

**Issue by SupinePandora43** [mezz/JustEnoughItems#1572]
```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 05.05.19 22:04
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at mezz.jei.plugins.vanilla.crafting.VanillaRecipeValidator.getValidRecipes(VanillaRecipeValidator.java:45)
	at mezz.jei.plugins.vanilla.VanillaPlugin.registerRecipes(VanillaPlugin.java:165)
	at mezz.jei.load.PluginLoader.lambda$new$4(PluginLoader.java:117)
	at mezz.jei.load.PluginLoader$$Lambda$2690/15429367.accept(Unknown Source)
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:29)
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:117)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:71)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$onRecipesLoaded$5(ClientLifecycleHandler.java:134)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$2672/6373588.func_195410_a(Unknown Source)
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199010_c(SimpleReloadableResourceManager.java:125)
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199005_a(SimpleReloadableResourceManager.java:101)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:644)
	at net.minecraft.client.gui.GuiScreenResourcePacks$2.func_194829_a(GuiScreenResourcePacks.java:58)
	at net.minecraft.client.gui.GuiButton.mouseClicked(GuiButton.java:100)
	at net.minecraft.client.gui.GuiEventHandler.mouseClicked(SourceFile:46)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper$$Lambda$1720/23732471.run(Unknown Source)
	at net.minecraft.client.gui.GuiScreen.func_195121_a(GuiScreen.java:418)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:78)
	at net.minecraft.client.MouseHelper$$Lambda$1232/1769754.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3108)
	at net.minecraft.client.MainWindow.func_198086_a(SourceFile:321)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:818)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$323/9091093.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:57)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:43)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.plugins.vanilla.crafting.VanillaRecipeValidator.getValidRecipes(VanillaRecipeValidator.java:45)
	at mezz.jei.plugins.vanilla.VanillaPlugin.registerRecipes(VanillaPlugin.java:165)
	at mezz.jei.load.PluginLoader.lambda$new$4(PluginLoader.java:117)
	at mezz.jei.load.PluginLoader$$Lambda$2690/15429367.accept(Unknown Source)
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:29)
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:117)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:71)
	at mezz.jei.startup.ClientLifecycleHandler.lambda$onRecipesLoaded$5(ClientLifecycleHandler.java:134)
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$2672/6373588.func_195410_a(Unknown Source)
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199010_c(SimpleReloadableResourceManager.java:125)
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199005_a(SimpleReloadableResourceManager.java:101)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:644)
	at net.minecraft.client.gui.GuiScreenResourcePacks$2.func_194829_a(GuiScreenResourcePacks.java:58)
	at net.minecraft.client.gui.GuiButton.mouseClicked(GuiButton.java:100)
	at net.minecraft.client.gui.GuiEventHandler.mouseClicked(SourceFile:46)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper$$Lambda$1720/23732471.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiScreenResourcePacks
Stacktrace:
	at net.minecraft.client.gui.GuiScreen.func_195121_a(GuiScreen.java:418)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:78)
	at net.minecraft.client.MouseHelper$$Lambda$1232/1769754.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3108)
	at net.minecraft.client.MainWindow.func_198086_a(SourceFile:321)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:818)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:359)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$323/9091093.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:57)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:43)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 345541776 bytes (329 MB) / 922746880 bytes (880 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Launched Version: 1.13.2-forge-25.0.191
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTS 250/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Rails 3D1
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Core(TM)2 Duo CPU E4500 @ 2.20GHz
```

**Comment by SupinePandora43** [comment]
error when reloading texture packs

**Comment by mezz** [comment]
Thanks for the report!

**Comment by SupinePandora43** [comment]
I'm just porting my texturepack to 1.13, and i reload texturepacks after every change. And i getting error

**Comment by ProsperCraft** [comment]
I can confirm this issue is still present in 1.14.4
	jei-1.14.4-6.0.0.10.jar
Forge .45

I was had disconnected from the server and could not reconnect due to the forge bug that doesn't let you reconnect to a server half of the time, and I thought to myself...what if I swap out textures packs, so I disabled the programmer pack and clicked save and it crashed.

https://gist.github.com/ProsperCraft/61172a49735a3058b79a4ce7202e1749

**Comment by mezz** [comment]
I haven't been able to reproduce this bug in single player. 
Does it only happen when connected to a server?

**Comment by ProsperCraft** [comment]
No, not only server, I made a new BoP single player world, exited, then disabled the programmer resource pack and after a long time, about 3 mins it crashed-

https://gist.github.com/ProsperCraft/29435f20f0206417c5244da81cd9ff2b

[debug.log](https://github.com/mezz/JustEnoughItems/files/3514104/debug.log)
[latest.log](https://github.com/mezz/JustEnoughItems/files/3514105/latest.log)


Modpack- https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by mezz** [comment]
Thanks for the info.
I think this is caused by a conflict with another mod. Can you please narrow down the mod list to find out which other mod or mods is causing this issue with JEI?
