### ISSUE TITLE
[JEI 4.15.0.268] NPE in InputHandler when loading world

### ISSUE THREAD

**Issue by pkrasimirov** [mezz/JustEnoughItems#1651]
Crash happened when connecting to server (multiplayer).  Second attempt connected ok and game started just fine.  I decided to report anyway.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  RandomPatches (randompatches-1.12.2-1.15.1.0.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 7/27/19 8:43 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events

	at mezz.jei.input.InputHandler.onGuiMouseEvent(InputHandler.java:86)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1521_InputHandler_onGuiMouseEvent_Pre.invoke(.dynamic)

	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)

	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)

	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)

	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)

	at net.minecraft.client.main.Main.main(SourceFile:123)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)



A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.input.InputHandler.onGuiMouseEvent(InputHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1521_InputHandler_onGuiMouseEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiDisconnected
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
[skip]
```
Perhaps a race condition, I was too quick to click around with the mouse the first time.

FTB Ultimate Reloaded

**Comment by pkrasimirov** [comment]
It happened again today.  Meanwhile FTB Ultimate Reloaded 1.8.0 was released and I'm using it.
```
[20:37:27] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 59%
[20:37:32] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 60%
[20:37:37] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 62%
[20:37:42] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 63%
[20:37:47] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 64%
[20:37:52] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 66%
[20:37:57] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 67%
[20:38:02] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 68%
[20:38:07] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 70%
[20:38:12] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 71%
[20:38:17] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 72%
[20:38:22] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 74%
[20:38:27] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 75%
[20:38:28] [Session-Validator/INFO] [ReAuth]: Session validation successful
[20:38:35] [Client thread/INFO] [minecraft/GuiConnecting]: Connecting to <server>, 25565
[20:38:35] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 75%
[20:38:35] [Server Connector #1/ERROR] [minecraft/GuiConnecting]: Couldn't connect to server
java.lang.NullPointerException: group
	at io.netty.bootstrap.AbstractBootstrap.group(AbstractBootstrap.java:84) ~[netty-all-4.1.9.Final.jar:?]
	at net.minecraft.network.NetworkManager.func_181124_a(NetworkManager.java:332) ~[gw.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting$1.run(GuiConnecting.java:68) [bkr$1.class:?]
[20:38:35] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$MouseInputEvent$Pre@661eb8ed:
java.lang.NullPointerException: null
	at mezz.jei.input.InputHandler.onGuiMouseEvent(InputHandler.java:86) ~[InputHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1527_InputHandler_onGuiMouseEvent_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500) [blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[20:38:35] [Client thread/ERROR] [FML]: Index: 5 Listeners:
[20:38:35] [Client thread/ERROR] [FML]: 0: NORMAL
[20:38:35] [Client thread/ERROR] [FML]: 1: ASM: class vazkii.arl.util.DropInHandler onRightClick(Lnet/minecraftforge/client/event/GuiScreenEvent$MouseInputEvent$Pre;)V
[20:38:35] [Client thread/ERROR] [FML]: 2: ASM: class techreborn.compat.jei.TechRebornJeiPlugin handleMouseClick(Lnet/minecraftforge/client/event/GuiScreenEvent$MouseInputEvent$Pre;)V
[20:38:35] [Client thread/ERROR] [FML]: 3: ASM: at.feldim2425.moreoverlays.itemsearch.GuiHandler@55906720 onGuiClick(Lnet/minecraftforge/client/event/GuiScreenEvent$MouseInputEvent$Pre;)V
[20:38:35] [Client thread/ERROR] [FML]: 4: ASM: net.blay09.mods.craftingtweaks.client.ClientProxy@58d38d11 onGuiMouseEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$MouseInputEvent$Pre;)V
[20:38:35] [Client thread/ERROR] [FML]: 5: ASM: mezz.jei.input.InputHandler@1a25437a onGuiMouseEvent(Lnet/minecraftforge/client/event/GuiScreenEvent$MouseInputEvent$Pre;)V
[20:38:35] [Client thread/ERROR] [FML]: 6: LOW
[20:38:35] [Client thread/ERROR] [FML]: 7: ASM: blusunrize.immersiveengineering.client.ClientEventHandler@5fbf4108 onKey(Lnet/minecraftforge/client/event/GuiScreenEvent$MouseInputEvent$Pre;)V
[20:38:50] [Client thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1772) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at mezz.jei.input.InputHandler.onGuiMouseEvent(InputHandler.java:86) ~[InputHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1527_InputHandler_onGuiMouseEvent_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:500) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759) ~[bib.class:?]
	... 9 more
[20:38:50] [ThaumicJEI Aspect Cache/INFO] [thaumicjei]: ItemStack Aspect checking at 75%
[20:38:50] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]:
```

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by pkrasimirov** [comment]
@mezz, I see your request now.  Here's the crash log: https://gist.github.com/pkrasimirov/be0167310913a1be1fc1316b10fe90c0

**Comment by mezz** [comment]
Thanks.
Based on the log, I think your game is crashing for some other reason, and that causes JEI to crash too.
I have submitted a fix which should be available in a few minutes. That should stop JEI from crashing, and hopefully that will allow you to find out what the underlying issue is.

**Comment by pkrasimirov** [comment]
I cannot reproduce the crash on demand so I cannot confirm if this fix is effective.  Thanks for your mods and work!
