### ISSUE TITLE
Rendering Ingridient

### ISSUE THREAD

**Issue by SleeplessNites** [mezz/JustEnoughItems#1655]
[crash-2019-07-31_23.00.43-client.txt](https://github.com/mezz/JustEnoughItems/files/3452551/crash-2019-07-31_23.00.43-client.txt)

**Comment by mezz** [comment]
Thanks for the report!
```
java.lang.ArrayIndexOutOfBoundsException: -587316
	at net.minecraft.world.ColorizerGrass.func_77480_a(SourceFile:18)
	at com.matez.wildnature.init.WildNatureBlockColors$6.func_186720_a(WildNatureBlockColors.java:80)
	at net.minecraft.client.renderer.color.BlockColors.func_189991_a(BlockColors.java:173)
	at buildcraft.silicon.client.FacadeItemColours.func_186726_a(FacadeItemColours.java:20)
```

This looks like issue with Buildcraft Facades and the WildNature mod. 
Please report it to them here: https://github.com/BuildCraft/BuildCraft/issues
