### ISSUE TITLE
1.14: Trouble setting up dev environment with maven, fails on game startup (no such method error Minecraft.func_71410_x)

### ISSUE THREAD

**Issue by Lothrazar** [mezz/JustEnoughItems#1689]
I am trying to set up JEI integration / plugin on 1.14.4

I am using this maven 
https://dvs1.progwml6.com/files/maven/mezz/jei/jei-1.14.4/6.0.0.10
Like this in the gradle file
https://github.com/Lothrazar/Storage-Network/compare/update114...jeiupdate

Everything compiles, and my IDE says its all fine, for example I an import 
"import mezz.jei.api.recipe.IFocus;" no problem

But when I run it says the following log.

My intuition is because we are on different MCP mappings, is this related?   I'm no good with gradle

```
Generating PackInfo named mod:jei for mod file C:\gradle\caches\modules-2\files-2.1\mezz.jei\jei-1.14.4\6.0.0.10\3948136870b4e79f79ecb4ae1381d9e4a742ca30\jei-1.14.4-6.0.0.10.jar
[21:48:09.596] [Client thread/DEBUG] [ne.mi.fm.ForgeI18n/CORE]: Loading I18N data entries: 0
[21:48:09.793] [Client thread/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: net.minecraft.client.Minecraft.func_71410_x()Lnet/minecraft/client/Minecraft;
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2075/1228125263@3a917e07
java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.func_71410_x()Lnet/minecraft/client/Minecraft;
	at mezz.jei.JustEnoughItems.lambda$null$1(JustEnoughItems.java:30)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:163)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$28(ModLoader.java:238)
	at java.util.HashMap.forEach(Unknown Source)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:209)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:238)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:196)
	at net.minecraft.client.renderer.color.BlockColors.init(BlockColors.java:76)
	at net.minecraft.client.Minecraft.init(Minecraft.java:504)
	at net.minecraft.client.Minecraft.run(Minecraft.java:365)
	at net.minecraft.client.main.Main.main(Main.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:101)
```

**Comment by TehNut** [comment]
You need to `compile fg.deobf("maven:artifact")` now which is noted in JEIs developer wiki

**Comment by mezz** [comment]
TehNut is right, it should solve your issue. 
You can find the wiki page here: https://github.com/mezz/JustEnoughItems/wiki/Getting-Started
