### ISSUE TITLE
Getting this error in my game whenever i try to enable JEI in inventory

### ISSUE THREAD

**Issue by Parabel54** [mezz/JustEnoughItems#1699]
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 8/25/19 8:11 PM
Description: Rendering ingredient

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.ItemRenderer.func_191961_a(Lnet/minecraft/client/renderer/model/IBakedModel;Lnet/minecraft/item/ItemStack;)V from class mezz.jei.render.ItemStackFastRenderer
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:70) ~[?:6.0.0.10] {}
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:35) ~[?:6.0.0.10] {}
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:169) ~[?:6.0.0.10] {}
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:106) ~[?:6.0.0.10] {}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:113) ~[?:6.0.0.10] {}
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:177) ~[?:6.0.0.10] {}
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:79) ~[?:6.0.0.10] {}
	at net.minecraftforge.eventbus.ASMEventHandler_18_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:362) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:356) ~[?:?] {pl:runtimedistcleaner:A}
	at mezz.jei.gui.recipes.RecipesGui.render(RecipesGui.java:191) ~[?:6.0.0.10] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:360) ~[?:?] {}
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:691) ~[?:?] {}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:898) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:886) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.45.jar:28.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$344/600017090.call(Unknown Source) [forge-1.14.4-28.0.45.jar:28.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:244)

-- Ingredient being rendered --
Details:
	Ingredient Mod: Minecraft
	Ingredient Info: 1 stone minecraft:stone
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:244)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:37)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:169)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:106)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:113)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:177)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:79)
	at net.minecraftforge.eventbus.ASMEventHandler_18_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:362)
	at net.minecraft.client.gui.screen.Screen.renderBackground(Screen.java:356)
	at mezz.jei.gui.recipes.RecipesGui.render(RecipesGui.java:191)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:360)
	at sun.reflect.GeneratedMethodAccessor18.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:691)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:898)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:886)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$344/600017090.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- Screen render details --
Details:
	Screen name: mezz.jei.gui.recipes.RecipesGui
	Mouse location: Scaled: (291, 145). Absolute: (1165.000000, 582.000000)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Parable54'/275, l='MpServer', x=-286.55, y=73.00, z=248.04]]
	Chunk stats: Client Chunk Cache: 1089, 756
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-240,64,208), Chunk: (at 0,4,0 in -15,13; contains blocks -240,0,208 to -225,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2721307 game time, 280888 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6623774520 bytes (6316 MB) / 8187281408 bytes (7808 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.45.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.14.4_HD_U_F4_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.45.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.45
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		jei-1.14.4-6.0.0.10.jar Just Enough Items {jei@6.0.0.10 DONE}
		mobcatcher-1.2a.jar Mob Catcher {mobcatcher@1.2a DONE}
		XL-Food-Mod-1.14.4-2.1.0.jar XL Food Mod {xlfoodmod@2.1.0 DONE}
		forge-1.14.4-28.0.45-universal.jar Forge {forge@28.0.45 DONE}
		forge-1.14.4-28.0.45-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.0.45
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 436.02, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Stratum-1024x-master
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
```

**Comment by Ommina** [comment]
Looks like #1668 again.  See, also, https://github.com/sp614x/optifine/issues/2748

**Comment by Bvioto** [comment]
I have experimented the same issue:

[crash-2019-08-26_00.15.35-client.txt](https://github.com/mezz/JustEnoughItems/files/3539515/crash-2019-08-26_00.15.35-client.txt)

JEI (jei-1.14.4-6.0.0.10)
Optifine (preview_OptiFine_1.14.4_HD_U_F4_pre2)
Forge (forge-1.14.4-28.0.55-installer)

I can't remove Optifine because I use shaders and I need them :C 

The game crashes when opening inventory.

**Comment by Ommina** [comment]
Well, yes.  I'm sure it does.  Regrettably, that doesn't make it any less a duplicate, nor any less an issue with optifine, the bug report for which you can follow at the link provided, above.

**Comment by PseudoResonance** [comment]
This crash is caused by OptiFine, not by JEI, and there's nothing that can be done. OptiFine for 1.14.4 with Forge is a pre-release version, and thus is not finished and not ready to be used in gameplay, other than testing.
