### ISSUE TITLE
[1.12.2] When Opening JEI, it crashes.

### ISSUE THREAD

**Issue by rosethenoob** [mezz/JustEnoughItems#1723]
## **Versions:**
JEI 1.12.2-4.15.0.268
Forge 14.23.5.2847
Minecraft 1.12.2
## **Error (Gist):**
[GIST](https://gist.github.com/PrimeBomb/519486b6285c88cb965eb8376375ac7a)
## **Crash Report:**
[CRASH REPORT](https://gist.github.com/PrimeBomb/38c2e98ed7181c5dc9647f4d4056a6aa)
## **Error (Pasted):**
``[12:16:44] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$BackgroundDrawnEvent@102b9b5c:
net.minecraft.util.ReportedException: Rendering ingredient
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:259) ~[ErrorUtil.class:?]
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:34) ~[ItemStackFastRenderer.class:?]
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157) ~[IngredientListBatchRenderer.class:?]
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99) ~[IngredientGrid.class:?]
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97) ~[IngredientGridWithNavigation.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161) ~[IngredientListOverlay.class:?]
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:62) ~[GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1416_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575) [blk.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66) [bmx.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537) ~[buk.class:?]
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21) ~[bve.class:?]
	at com.vicmatskiv.weaponlib.compatibility.CompatibleStaticModelSourceRenderer.func_188616_a(CompatibleStaticModelSourceRenderer.java:107) ~[CompatibleStaticModelSourceRenderer.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106) ~[bzw.class:?]
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:63) ~[ItemStackFastRenderer.class:?]
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32) ~[ItemStackFastRenderer.class:?]
	... 29 more
[12:16:44] [Client thread/ERROR] [FML]: Index: 1 Listeners:
[12:16:44] [Client thread/ERROR] [FML]: 0: NORMAL
[12:16:44] [Client thread/ERROR] [FML]: 1: ASM: mezz.jei.gui.GuiEventHandler@6b987393 onDrawBackgroundEventPost(Lnet/minecraftforge/client/event/GuiScreenEvent$BackgroundDrawnEvent;)V``
## **How to Replicate:**
1. Open JEI
## **Other Information:**
It was working fine earlier, and then as soon as I put it into fullscreen or try to type something into the search bar, it crashes.
## **Addtional Mods:**
![image](https://user-images.githubusercontent.com/37458083/64911539-9d389a80-d6e8-11e9-92b2-be2a8a4954e4.png)
![image](https://user-images.githubusercontent.com/37458083/64911541-a88bc600-d6e8-11e9-918d-9970468016dd.png)

**Comment by TehNut** [comment]
This appears to be a rendering error within the modern warfare mod.

```
-- Ingredient being rendered --
Details:
	Ingredient Mod: Modern Warfare 2.0 Contagion
	Ingredient Info: 1xitem.mw_Kobra@0 mw:kobra
```

**Comment by rosethenoob** [comment]
Sorry for the late comment-
but thank you, it fixed it!

**Comment by jolandepoel** [comment]
I have a similar error, but no Modern Warfare. I've got this:
-- Ingredient being rendered --
  Ingredient Mod: AgriCraft
  Ingredient Info: 1xitem.agricraft:agri_seed@0 agricraft:agri_seed nbt:{agri_analyzed:0b,agri_strength:1b,agri_gain:1b,agri_seed:"resource:jaslumine_plant",agri_growth:1b}

Is that an AgriCraft error?

**Comment by TehNut** [comment]
Yes
