### ISSUE TITLE
JEI crash when loading world in eclipse workspace

### ISSUE THREAD

**Issue by marilatte53** [mezz/JustEnoughItems#1760]
Hello,

I am coding a mod at the moment and want to use JEI when I start the mod in my workspace. At first, I tried to just put it in the mods folder, which throws an exception because the api is missing.
After that I tried to add it to my gradle.build script, which, after some attempts, seemed to work. Minecraft started up correctly and I could see JEI in the mods tab.
However, when I try to load up a world, JEI gives me a ton of NoSuchMethodExceptions. Here is one of them:
[12Okt2019 19:45:55.648] [Client thread/ERROR] [mezz.jei.plugins.vanilla.cooking.fuel.FuelRecipeMaker/]: Failed to check if item is fuel 1 stone minecraft:stone.
java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeHooks.getBurnTime(Lnet/minecraft/item/ItemStack;)I
	at mezz.jei.plugins.vanilla.cooking.fuel.FuelRecipeMaker.getBurnTime(FuelRecipeMaker.java:40) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at mezz.jei.plugins.vanilla.cooking.fuel.FuelRecipeMaker.getFuelRecipes(FuelRecipeMaker.java:30) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at mezz.jei.plugins.vanilla.VanillaPlugin.registerRecipes(VanillaPlugin.java:187) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at mezz.jei.load.PluginLoader.lambda$new$4(PluginLoader.java:117) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:117) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:71) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:126) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:104) ~[jei-1.14.4-6.0.0.18_mapped_snapshot_20190914-1.14.3.jar:6.0.0.18]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:1003) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.handleUpdateRecipes(ClientPlayNetHandler.java:1393) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.processPacket(SUpdateRecipesPacket.java:27) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.processPacket(SUpdateRecipesPacket.java:16) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:19) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:140) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:110) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.drainTasks(ThreadTaskExecutor.java:97) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:893) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:384) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:128) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55) ~[forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?]
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:101) [forge-1.14.4-28.1.1_mapped_snapshot_20190914-1.14.3-recomp.jar:?]
### 

The mod keeps doing this with every single item I think and the only thing i can do is force the game to close.
Sorry for posting the crash here, but I don't want to post the whole report with thousands of exceptions...
Hope you can help me :D

**Comment by TehNut** [comment]
You are using Forge 28.1.1 which is extremely outdated. The version of JEI you're using requires a furnace hook added in 28.1.5 which was released almost a month ago.

**Comment by marilatte53** [comment]
Thank you I already thought that it has something to do with the versions...

The strange thing is that I updated my forge _today_.

However, thanks :D
