### ISSUE TITLE
crash when in creative

### ISSUE THREAD

**Issue by raphd95** [mezz/JustEnoughItems#1767]
when i try to open the inventory on my server in creative, its crash the game put in survival, its work fine 

here my crash log
thanks for your help
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 10/18/19 3:13 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.mrcrayfish.furniture.client.event.CreativeScreenEvents.updateTagButtons(CreativeScreenEvents.java:220) ~[?:7.0.0-pre9-1.14.4] {re:classloading}
	at com.mrcrayfish.furniture.client.event.CreativeScreenEvents.onScreenInit(CreativeScreenEvents.java:98) ~[?:7.0.0-pre9-1.14.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_173_CreativeScreenEvents_onScreenInit_Post.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:334) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:770) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.init(SourceFile:48) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:332) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:770) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1432) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1318) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:866) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.26.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$355/828447060.call(Unknown Source) [forge-1.14.4-28.1.26.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.0.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mrcrayfish.furniture.client.event.CreativeScreenEvents.updateTagButtons(CreativeScreenEvents.java:220)
	at com.mrcrayfish.furniture.client.event.CreativeScreenEvents.onScreenInit(CreativeScreenEvents.java:98)
	at net.minecraftforge.eventbus.ASMEventHandler_173_CreativeScreenEvents_onScreenInit_Post.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:334)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:770)
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.init(SourceFile:48)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:332)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:770)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1432)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['iSiiKz'/166, l='MpServer', x=223.89, y=69.00, z=-127.17]]
	Chunk stats: Client Chunk Cache: 729, 481
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (240,68,-144), Chunk: (at 0,4,0 in 15,-9; contains blocks 240,0,-144 to 255,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 107187053 game time, 26322 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1747)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$355/828447060.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3460272488 bytes (3299 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.26.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.26
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		automessagedisplayer-1.14.4-0.0.1.3.jar AutoMessageDisplayer {automessagedisplayer@1.14.4-0.0.1.3 DONE}
		camera-1.4.8.jar Camera Mod {camera@1.4.8 DONE}
		cfm-7.0.0-pre9-mc1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre9 DONE}
		corpse-1.14.4-1.0.2.jar Corpse {corpse@1.14.4-1.0.2 DONE}
		craftingstation-2.0.4.jar Crafting Station {craftingstation@2.0.4 DONE}
		DeathFinder-v1.0.1-1.14.3.jar Death Finder {deathfinder@1.0.1 DONE}
		exp_bottling-1.14.4-3.jar EXP Bottling {exp_bottling@1.14.4-3 DONE}
		extlights-1.5.jar Extended Lights {extlights@1.5 DONE}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		Glowglass-1.14.4-1.1.jar Glowglass {glowglass@1.1 DONE}
		inventorysorter-1.14.4-16.1.0.jar Simple Inventory Sorter {inventorysorter@16.1.0 DONE}
		jei-1.14.4-6.0.0.18.jar Just Enough Items {jei@6.0.0.18 DONE}
		Lucky-Block-Mod-1.14.4.jar Lucky Block {lucky@7.9.1 DONE}
		metalbarrels-1.3c.jar Metal Barrels {metalbarrels@1.3c DONE}
		music_player-1.14.4-2.0.3.43.jar Music Player {musicplayer@2.0.3.43 DONE}
		practicaltools-1.14.4-1.4.jar Practical Tools {practicaltools@1.14.4-1.4 DONE}
		quickhomes-1.14.4-1.2.4.2.jar QuickHomes {quickhomes@1.2.4.2 DONE}
		quickteleports-1.14.4-1.1.0.jar QuickTeleports {quickteleports@1.1.0 DONE}
		simplylight-0.9.0.jar Simply Light {simplylight@0.9.0 DONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		switchbow-1.5.8.jar Switch-Bow {switchbow@1.5.8 DONE}
		titanium-1.14.4-2.2.0-d9775a7.jar Titanium {titanium@1.14.4-2.2.0-d9775a7 DONE}
		twitchspawn1.14.4-1.3.8.jar TwitchSpawn {twitchspawn@1.3.8 DONE}
		u_team_core-1.14.4-2.7.3.132.jar U Team Core {uteamcore@2.7.3.132 DONE}
		useful_railroads-1.14.4-1.2.0.11.jar Useful Railroads {usefulrailroads@1.2.0.11 DONE}
		worldedit-forge-mc1.14.4-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 DONE}
		forge-1.14.4-28.1.26-universal.jar Forge {forge@28.1.26 DONE}
		forge-1.14.4-28.1.26-client.jar Minecraft {minecraft@1.14.4 DONE}
	Launched Version: 1.14.4-forge-28.1.26
	LWJGL: 3.2.2 build 10
	OpenGL: Quadro P5000/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.02, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Vanilla-Normals-Renewed-1.13-master
	Current Language: English (US)
	CPU: 8x Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
```

**Comment by mezz** [comment]
Thanks for the report!
This crash appears to be from MrCrayfish's Furniture Mod, not JEI.
Please report to them here: 
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues
