### ISSUE TITLE
search thing like"@tr", then crash

### ISSUE THREAD

**Issue by hehuanye** [mezz/JustEnoughItems#1793]
PS: search thing like"@tr", then crash. Then if I open JEI in the game, the game will crash.
1.12.2--4.15.0.268

---- Minecraft Crash Report ----
// You're mean.

Time: 2019-11-08 16:30:09 CST
Description: Exception ticking world

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.remove(HashMap.java:1459)
    at net.minecraft.world.gen.ChunkProviderServer.tick(ChunkProviderServer.java:262)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:207)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by mezz** [comment]
Thanks for the report!
Unfortunately, the crash you have pasted here is unrelated to JEI. Either it is a coincidence, or some mod has an item that is crashing the game in a strange way when it gets rendered.

**Comment by hehuanye** [comment]
thank you dude, I like JEI so much!!!
----- 原始邮件 -----
发件人：James Mitchell <notifications@github.com>
收件人：mezz/JustEnoughItems <JustEnoughItems@noreply.github.com>
抄送人：hehuanye <hehuanye876@sina.com>,  Author <author@noreply.github.com>
主题：Re: [mezz/JustEnoughItems] search thing like"@tr", then crash (#1793)
日期：2019年11月09日 15点56分

Thanks for the report!

Unfortunately, the crash you have pasted here is unrelated to JEI. Either it is a coincidence, or some mod has an item that is crashing the game in a strange way when it gets rendered.

&mdash;
