### ISSUE TITLE
JEI crashing my modpack at startup

### ISSUE THREAD

**Issue by Ethern8ai** [mezz/JustEnoughItems#1815]
Hi, usually i find what the crash is about but this time i have no idea, addes many mods in my modpack and did many changes, i get this crash that specifies that JEI is the reason, i deactivated it (on twitch) and the modpack runs well, could someone give me some lght on the issue?

Thank you

There is the gist, and as i am not sure that i gave the proper link i will add the bit that i think tells the issue:

gist: <script src="https://gist.github.com/Ethern8ai/d9cb7349882cca0845af7e448dd9c639.js"></script>

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at mezz.jei.suffixtree.Node.<init>(Node.java:65)
	at mezz.jei.suffixtree.GeneralizedSuffixTree.update(GeneralizedSuffixTree.java:329)
	at mezz.jei.suffixtree.GeneralizedSuffixTree.put(GeneralizedSuffixTree.java:163)
	at mezz.jei.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:119)
	at mezz.jei.ingredients.IngredientFilter.addIngredients(IngredientFilter.java:103)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:90)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

**Comment by Ethern8ai** [comment]
up, i checked the report link: https://gist.github.com/Ethern8ai/d9cb7349882cca0845af7e448dd9c639.js
do you guys can use that format? or i did something wrong on its upload?

**Comment by Ommina** [comment]
`Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`

You're running out of memory.  Give the pack more RAM.

**Comment by Ethern8ai** [comment]
damn! thank you very much Ommina! feel silly that i missed that, unfortunately that is probably the limit of my crappy laptop.. Have a great day!
