### ISSUE TITLE
OpenGL crash

### ISSUE THREAD

**Issue by melodious1963** [mezz/JustEnoughItems#1899]
I am having issues with OpenGL and JEI, I am on the latest JEI build for minecraft 1.12.2 (deinstalled it atm, because of the aforementioned crashes) and forge 1.12.2-14.23.5.2847

Crash Log (short):
Description: Rendering ingredient

org.lwjgl.opengl.OpenGLException: Cannot use Buffers when Array Buffer Object is enabled
	at org.lwjgl.opengl.GLChecks.ensureArrayVBOdisabled(GLChecks.java:71)
	at org.lwjgl.opengl.GL11.glVertexPointer(GL11.java:2700)
	at net.minecraft.client.renderer.GlStateManager.func_187427_b(SourceFile:770)
	at net.minecraftforge.client.ForgeHooksClient.preDraw(ForgeHooksClient.java:468)
	at net.minecraft.client.renderer.vertex.VertexFormatElement$EnumUsage.preDraw(VertexFormatElement.java:169)
	at net.minecraft.client.renderer.WorldVertexBufferUploader.func_181679_a(WorldVertexBufferUploader.java:31)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:22)
	at net.minecraftforge.client.ForgeHooksClient.drawSegment(ForgeHooksClient.java:755)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:716)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:63)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1817_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiChest.func_73863_a(SourceFile:31)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Crash Report (long) --> https://pastebin.com/MwgY5jXP

I did think it had something to do with an other mod not being able to render, but the reports also mentioned a jungle sapling from minecraft itself...

I also tried to install a newer driver for my GPU (nvidia quadro p1000) but that didn't work.
And no, I do not have optifine installed atm.

**Comment by TehNut** [comment]
```
-- Ingredient being rendered --
Details:
    Mod Name: Industrial Foregoing
    Registry Name: industrialforegoing:black_hole_tank
    Display Name: Black Hole Tank
    String Name: 1xtile.industrialforegoing.black_hole_tank@0
```

**Comment by melodious1963** [comment]
Like I said:

> I did think it had something to do with an other mod not being able to render, but the reports also mentioned a jungle sapling from minecraft itself...

**Comment by melodious1963** [comment]
Here's prove of the sapling one:
`-- Ingredient being rendered --
Details:
	Mod Name: Minecraft
	Registry Name: minecraft:sapling
	Display Name: Acacia Sapling
	String Name: 1xtile.sapling@4
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:271)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:34)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:163)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1853_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

And tinkers construct:
`-- Ingredient being rendered --
Details:
	Mod Name: Tinkers' Construct
	Registry Name: tconstruct:tooltables
	Display Name: Stencil Table
	String Name: 1xtile.tconstruct.tooltables@1
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:271)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:34)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1866_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:66)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
