### ISSUE TITLE
Newest 1.12.2 version crashes

### ISSUE THREAD

**Issue by scrouthtv** [mezz/JustEnoughItems#1962]
I am currently trying to get JEI working with Forge MDK. I am using
```
forge-1.12.2-14.23.5.2854
jei_1.12.2-4.15.0.293
openjdk 1.8.0_242 64-bit
```
the game crashes with 
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: net.minecraft.util.ReportedException: Registering texture
        at net.minecraft.client.renderer.texture.TextureManager.loadTexture(TextureManager.java:95)
        at net.minecraft.client.renderer.texture.TextureManager.loadTickableTexture(TextureManager.java:52)
        at mezz.jei.startup.ProxyCommonClient.init(ProxyCommonClient.java:114)
```
I posted the full crash report under https://gist.github.com/scrouthtv/37a84cb176e1c1cbb8ecf8f698902649 .

What am I missing?
I tried using an older Forge version with FG2, however those aren't supported anymore and never worked on Linux.

**Comment by scrouthtv** [comment]
Still not working on the new versions. How can I fix my problem?

**Comment by clienthax** [comment]
It looks like you are not applying the access transformers from JEI.

**Comment by mezz** [comment]
You can set up JEI in your dev environment by following the gradle guide in the wiki here: https://github.com/mezz/JustEnoughItems/wiki/Getting-Started
