### ISSUE TITLE
While loading up Minecraft 1.12.2 JEI crashed

### ISSUE THREAD

**Issue by Squishybear1** [mezz/JustEnoughItems#1990]
Hello I have been having problems while useing JEI. See for a week now I Have been playing with a couple of small mod including JEI but, recently added 20 new mods and now Minecraft constantly crashes and when I look at the crash report it says JEI is the problem. Here is the crash report 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.12.1.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 6/30/20 9:58 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.regex.Pattern$BnM.optimize(Pattern.java:5408)
	at java.util.regex.Pattern.compile(Pattern.java:1709)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at java.lang.String.replace(String.java:2227)
	at mezz.jei.ingredients.IngredientInformation.getTooltipStrings(IngredientInformation.java:41)
	at mezz.jei.ingredients.IngredientListElement.getTooltipStrings(IngredientListElement.java:123)
	at mezz.jei.ingredients.IngredientFilter$$Lambda$1715/950831729.getStrings(Unknown Source)
	at mezz.jei.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:117)
	at mezz.jei.ingredients.IngredientFilter.addIngredients(IngredientFilter.java:103)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:86)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --

**Comment by Ommina** [comment]
Caused by: java.lang.OutOfMemoryError: Java heap space

The addition of the extra mods has consumed available memory.  Give it more.

**Comment by Squishybear1** [comment]
Do you mean more memory.

**Comment by Ommina** [comment]
Indeed I do.

To be clear, JEI is not at fault here, it is only getting the blame.

**Comment by Squishybear1** [comment]
Thanks, I added more memory and now it works.
