### ISSUE TITLE
i don't know what to do

### ISSUE THREAD

**Issue by ozenry** [mezz/JustEnoughItems#2014]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/15/20 5:49 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: net.minecraft.util.ReportedException: Registering texture
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:95)
	at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:52)
	at mezz.jei.startup.ProxyCommonClient.init(ProxyCommonClient.java:114)
	at mezz.jei.JustEnoughItems.init(JustEnoughItems.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureMap.func_110569_e()V from class mezz.jei.gui.textures.JeiTextureMap
	at mezz.jei.gui.textures.JeiTextureMap.func_110551_a(JeiTextureMap.java:43)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:69)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by ozenry** [comment]
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 260068720 bytes (248 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version         | Source                                | Signature |
	|:----- |:------------------- |:--------------- |:------------------------------------- |:--------- |
	| LCHI  | minecraft           | 1.12.2          | minecraft.jar                         | None      |
	| LCHI  | mcp                 | 9.42            | minecraft.jar                         | None      |
	| LCHI  | FML                 | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar         | None      |
	| LCHI  | forge               | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar         | None      |
	| LCHI  | appliedenergistics2 | rv6-stable-7    | appliedenergistics2-rv6-stable-7.jar  | None      |
	| LCHI  | buildcraftlib       | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | buildcraftcore      | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | buildcraftbuilders  | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | buildcrafttransport | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | buildcraftsilicon   | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | buildcraftcompat    | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | buildcraftenergy    | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | buildcraftfactory   | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | buildcraftrobotics  | 7.99.24.1       | buildcraft-all-7.99.24.1.jar          | None      |
	| LCHI  | ironbackpacks       | 1.12.2-3.0.8-12 | IronBackpacks-1.12.2-3.0.8-12 (1).jar | None      |
	| LCHE  | jei                 | 4.15.0.296      | jei_1.12.2-4.15.0.296.jar             | None      |
	| LCH   | wanionlib           | 1.12.2-2.4      | WanionLib-1.12.2-2.4.jar              | None      |
	| LCH   | xaerominimap        | 1.15.8          | Xaeros_Minimap_1.15.8_Forge_1.12.jar  | None      |
	| LCH   | unidict             | 1.12.2-2.9.6    | UniDict-1.12.2-2.9.6.jar              | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27016' Renderer: 'Radeon RX 5500 XT'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full `fml-client-latest.log` or `latest.log` to https://gist.github.com and link it here.

**Comment by ozenry** [comment]
nvm i think i got it. thank you for your time

**Comment by mezz** [comment]
Glad it's fixed!
@ozenry Please reply with your solution so that other people with this issue can find it and see how to fix this issue.
