### ISSUE TITLE
Broken Recipe Reporting

### ISSUE THREAD

**Issue by Thiana** [mezz/JustEnoughItems#219]
When reporting a broken recipe could you please resolve the ItemStack names to their mod. Seeing something like 'item.itemMaterial' doesnt help pinpoint the offending mod. 

Thanks.

**Comment by mezz** [comment]
Do you have an example error log? I create a lot of these messages and it would help me find the right one to improve.

**Comment by Thiana** [comment]
If you want the full log I can provide that, but I think you just need this bit?

<pre>
[19:59:19] [Client thread/ERROR] [JEI/]: Found a broken recipe: net.minecraftforge.oredict.ShapedOreRecipe@12e694e7
Output ItemStacks: null
Output Fluids: []
Input ItemStacks: [[1xitem.itemMaterial@1], [1xitem.stick@0, 1xtile.bamboo@0, 1xtile.plant_1@5], [1xitem.itemMaterial@1], [1xitem.stick@0, 1xtile.bamboo@0, 1xtile.plant_1@5], null, [1xitem.stick@0, 1xtile.bamboo@0, 1xtile.plant_1@5], [1xitem.itemMaterial@1], [1xitem.stick@0, 1xtile.bamboo@0, 1xtile.plant_1@5], [1xitem.itemMaterial@1]]
Input Fluids: []
java.lang.NullPointerException: Found an itemStack with a null item. This is an error from another mod.
    at mezz.jei.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:313) ~[StackHelper.class:?]
    at mezz.jei.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:306) ~[StackHelper.class:?]
    at mezz.jei.util.RecipeMap.addRecipe(RecipeMap.java:112) ~[RecipeMap.class:?]
    at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:219) ~[RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:139) [RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.addRecipes(RecipeRegistry.java:103) [RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:58) [RecipeRegistry.class:?]
    at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:116) [ModRegistry.class:?]
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:174) [ProxyCommonClient.class:?]
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:130) [ProxyCommonClient.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_512_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraft.world.World.func_72838_d(World.java:1122) [adm.class:?]
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:156) [bdb.class:?]
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2318) [ave.class:?]
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2239) [ave.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:251) [bcy.class:?]
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:76) [gt.class:?]
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13) [gt.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
    at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[19:59:19] [Client thread/ERROR] [JEI/]: Found a broken recipe: net.minecraftforge.oredict.ShapedOreRecipe@203c8c60
Output ItemStacks: null
Output Fluids: []
Input ItemStacks: [[1xitem.itemMaterial@1], [1xitem.stick@0], [1xitem.itemMaterial@1], [1xitem.stick@0], null, [1xitem.stick@0], [1xitem.itemMaterial@1], [1xitem.stick@0], [1xitem.itemMaterial@1]]
Input Fluids: []
java.lang.NullPointerException: Found an itemStack with a null item. This is an error from another mod.
    at mezz.jei.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:313) ~[StackHelper.class:?]
    at mezz.jei.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:306) ~[StackHelper.class:?]
    at mezz.jei.util.RecipeMap.addRecipe(RecipeMap.java:112) ~[RecipeMap.class:?]
    at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:219) ~[RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:139) [RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.addRecipes(RecipeRegistry.java:103) [RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:58) [RecipeRegistry.class:?]
    at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:116) [ModRegistry.class:?]
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:174) [ProxyCommonClient.class:?]
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:130) [ProxyCommonClient.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_512_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraft.world.World.func_72838_d(World.java:1122) [adm.class:?]
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:156) [bdb.class:?]
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2318) [ave.class:?]
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2239) [ave.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:251) [bcy.class:?]
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:76) [gt.class:?]
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13) [gt.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fh$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
    at net.minecraft.util.Util.func_181617_a(SourceFile:44) [g.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1014) [ave.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
</pre>

**Comment by mezz** [comment]
Yeah that's fine, thanks. I'll see what I can do.

**Comment by Thiana** [comment]
Thanks :)

**Comment by mezz** [comment]
Try with this new version, it should give more information:
http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2288836

**Comment by Thiana** [comment]
Works perfectly :) Thanks. _wanders off to EnderIO github_
