### ISSUE TITLE
Ticking Entity Crash With BDLib

### ISSUE THREAD

**Issue by cjburkey01** [mezz/JustEnoughItems#230]
Hi!

When I open a world with BDLib and JEI installed together, I get this crash report:

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/29/16 2:52 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:793)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1962)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)
    at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:156)
    at net.minecraft.world.World.func_72866_a(World.java:1934)
    at net.minecraft.world.World.func_72870_g(World.java:1903)
    at net.minecraft.world.World.func_72939_s(World.java:1737)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1783)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:793)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1962)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)
    at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:156)
    at net.minecraft.world.World.func_72866_a(World.java:1934)
    at net.minecraft.world.World.func_72870_g(World.java:1903)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
    Entity ID: 463
    Entity Name: CJBurkey
    Entity's Exact location: 242.50, 66.00, 243.50
    Entity's Block location: World: (242,66,243), Chunk: (at 2,4,3 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1737)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['CJBurkey'/463, l='MpServer', x=242.50, y=66.00, z=243.50]]
    Chunk stats: MultiplayerChunkCache: 903, 903
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (252,64,252), Chunk: (at 12,4,12 in 15,15; contains blocks 240,0,240 to 255,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 876 game time, 876 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 86 total; [EntityBat['Bat'/128, l='MpServer', x=220.26, y=22.00, z=262.47], EntitySkeleton['Skeleton'/129, l='MpServer', x=213.25, y=34.00, z=311.47], EntityChicken['Chicken'/130, l='MpServer', x=220.50, y=64.00, z=316.72], EntityCow['Cow'/259, l='MpServer', x=321.80, y=72.00, z=287.03], EntityZombie['Zombie'/147, l='MpServer', x=228.18, y=34.00, z=236.53], EntityCreeper['Creeper'/148, l='MpServer', x=235.53, y=15.00, z=245.00], EntityZombie['Zombie'/149, l='MpServer', x=229.50, y=14.00, z=244.41], EntitySpider['Spider'/150, l='MpServer', x=230.33, y=14.00, z=246.73], EntityZombie['Zombie'/151, l='MpServer', x=232.31, y=33.00, z=242.83], EntitySkeleton['Skeleton'/152, l='MpServer', x=239.63, y=28.00, z=260.16], EntityCow['Cow'/153, l='MpServer', x=227.36, y=69.00, z=262.96], EntityCow['Cow'/154, l='MpServer', x=232.53, y=68.00, z=257.60], EntityCow['Cow'/155, l='MpServer', x=225.73, y=69.00, z=264.63], EntityCow['Cow'/156, l='MpServer', x=231.63, y=66.00, z=265.52], EntityCow['Cow'/157, l='MpServer', x=235.60, y=65.00, z=264.85], EntityCow['Cow'/158, l='MpServer', x=225.82, y=69.00, z=260.89], EntityChicken['Chicken'/159, l='MpServer', x=233.17, y=66.00, z=283.85], EntityChicken['Chicken'/160, l='MpServer', x=226.55, y=68.00, z=275.41], EntityCreeper['Creeper'/161, l='MpServer', x=236.56, y=21.00, z=296.27], EntityChicken['Chicken'/162, l='MpServer', x=232.60, y=66.00, z=290.68], EntityChicken['Chicken'/163, l='MpServer', x=228.15, y=65.00, z=302.54], EntityChicken['Chicken'/164, l='MpServer', x=226.15, y=65.00, z=309.50], EntityChicken['Chicken'/168, l='MpServer', x=226.43, y=62.77, z=321.43], EntityCreeper['Creeper'/180, l='MpServer', x=241.50, y=29.00, z=265.50], EntityCow['Cow'/181, l='MpServer', x=242.04, y=66.00, z=269.46], EntityCow['Cow'/182, l='MpServer', x=240.41, y=66.00, z=268.14], EntitySkeleton['Skeleton'/183, l='MpServer', x=243.50, y=26.00, z=274.50], EntityCow['Cow'/184, l='MpServer', x=255.57, y=65.00, z=272.78], EntityCow['Cow'/185, l='MpServer', x=252.58, y=65.00, z=272.50], EntityZombie['Zombie'/197, l='MpServer', x=267.80, y=18.00, z=196.45], EntitySkeleton['Skeleton'/198, l='MpServer', x=269.30, y=24.00, z=200.83], EntityCow['Cow'/199, l='MpServer', x=256.14, y=65.00, z=273.87], EntityCow['Cow'/200, l='MpServer', x=256.85, y=65.00, z=275.12], EntityCreeper['Creeper'/206, l='MpServer', x=272.50, y=24.00, z=197.01], EntitySkeleton['Skeleton'/207, l='MpServer', x=280.50, y=24.00, z=216.50], EntityZombie['Zombie'/208, l='MpServer', x=281.50, y=18.00, z=217.50], EntityZombie['Zombie'/209, l='MpServer', x=286.30, y=48.00, z=233.70], EntitySkeleton['Skeleton'/210, l='MpServer', x=284.50, y=20.00, z=268.50], EntityBat['Bat'/85, l='MpServer', x=170.43, y=49.40, z=217.20], EntityBat['Bat'/86, l='MpServer', x=165.52, y=56.69, z=251.43], EntityChicken['Chicken'/215, l='MpServer', x=292.34, y=63.00, z=206.38], EntityChicken['Chicken'/216, l='MpServer', x=295.50, y=63.00, z=206.50], EntitySkeleton['Skeleton'/89, l='MpServer', x=179.50, y=20.00, z=239.50], EntityChicken['Chicken'/217, l='MpServer', x=293.52, y=63.00, z=209.27], EntityCreeper['Creeper'/90, l='MpServer', x=186.50, y=20.00, z=244.50], EntityChicken['Chicken'/218, l='MpServer', x=292.50, y=63.00, z=209.50], EntityBat['Bat'/219, l='MpServer', x=293.43, y=20.86, z=243.16], EntityChicken['Chicken'/91, l='MpServer', x=189.50, y=64.00, z=291.50], EntitySkeleton['Skeleton'/220, l='MpServer', x=298.50, y=29.00, z=249.50], EntityChicken['Chicken'/92, l='MpServer', x=189.41, y=64.00, z=295.23], EntitySkeleton['Skeleton'/221, l='MpServer', x=295.50, y=48.00, z=243.50], EntityZombie['Zombie'/222, l='MpServer', x=294.24, y=48.00, z=243.48], EntityBat['Bat'/223, l='MpServer', x=298.46, y=48.00, z=247.25], EntityBat['Bat'/224, l='MpServer', x=298.32, y=37.27, z=322.20], EntityCow['Cow'/103, l='MpServer', x=207.48, y=65.00, z=186.65], EntityCow['Cow'/104, l='MpServer', x=206.45, y=65.00, z=185.62], EntityCreeper['Creeper'/232, l='MpServer', x=305.48, y=58.00, z=219.22], EntityBat['Bat'/105, l='MpServer', x=192.68, y=51.00, z=198.25], EntityWitch['Witch'/233, l='MpServer', x=310.50, y=60.00, z=217.50], EntityZombie['Zombie'/106, l='MpServer', x=197.01, y=55.00, z=265.55], EntitySheep['Sheep'/234, l='MpServer', x=309.74, y=64.00, z=231.63], EntityZombie['Zombie'/107, l='MpServer', x=201.71, y=53.00, z=285.49], EntitySheep['Sheep'/235, l='MpServer', x=309.99, y=64.00, z=235.12], EntityChicken['Chicken'/108, l='MpServer', x=193.79, y=64.00, z=293.46], EntitySheep['Sheep'/236, l='MpServer', x=305.08, y=64.00, z=236.42], EntityChicken['Chicken'/109, l='MpServer', x=193.40, y=64.00, z=288.98], EntityChicken['Chicken'/237, l='MpServer', x=319.35, y=64.00, z=233.46], EntitySheep['Sheep'/238, l='MpServer', x=308.57, y=64.00, z=243.14], EntitySkeleton['Skeleton'/239, l='MpServer', x=307.73, y=44.00, z=263.39], EntityBat['Bat'/240, l='MpServer', x=309.75, y=44.81, z=260.45], EntityZombie['Zombie'/241, l='MpServer', x=313.35, y=13.00, z=287.35], EntityCreeper['Creeper'/242, l='MpServer', x=308.50, y=15.00, z=286.50], EntityEnderman['Enderman'/243, l='MpServer', x=316.50, y=49.00, z=272.74], EntityCow['Cow'/244, l='MpServer', x=318.52, y=71.00, z=278.99], EntityCow['Cow'/245, l='MpServer', x=314.15, y=69.00, z=281.52], EntityCow['Cow'/119, l='MpServer', x=212.23, y=64.00, z=195.11], EntityCreeper['Creeper'/247, l='MpServer', x=311.60, y=37.00, z=321.03], EntityCow['Cow'/120, l='MpServer', x=211.60, y=64.00, z=196.85], EntityBat['Bat'/248, l='MpServer', x=312.39, y=39.34, z=324.52], EntityCow['Cow'/121, l='MpServer', x=211.92, y=66.00, z=212.65], EntityCow['Cow'/122, l='MpServer', x=209.11, y=67.00, z=220.48], EntityCow['Cow'/123, l='MpServer', x=215.09, y=66.00, z=219.07], EntityCreeper['Creeper'/124, l='MpServer', x=211.50, y=23.00, z=226.50], EntityCow['Cow'/125, l='MpServer', x=213.50, y=66.00, z=228.55], EntityCreeper['Creeper'/126, l='MpServer', x=221.51, y=13.00, z=244.58], EntityEnderman['Enderman'/127, l='MpServer', x=222.69, y=12.00, z=248.41]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Mac OS X (x86_64) version 10.11.3
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 285681624 bytes (272 MB) / 669609984 bytes (638 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.23 Powered by Forge 12.16.0.1813 5 mods loaded, 5 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1813-1.9.jar) 
    UCHIJAAAA   Forge{12.16.0.1813} [Minecraft Forge] (forge-1.9-12.16.0.1813-1.9.jar) 
    UCHIJAAAA   bdlib{1.11.0.8} [BD Lib] (bdlib-1.11.0.8-mc1.9.jar) 
    UCHIJAAAA   JEI{3.1.2.172} [Just Enough Items] (jei_1.9-3.1.2.172.jar) 
    Loaded coremods (and transformers): 
    List of loaded APIs: 
        * JustEnoughItemsAPI (3.1.0) from jei_1.9-3.1.2.172.jar
    Launched Version: 1.9-forge1.9-12.16.0.1813-1.9
    LWJGL: 2.9.2
    OpenGL: NVIDIA GeForce GT 750M OpenGL Engine GL version 2.1 NVIDIA-10.8.14 310.42.15f01, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz
```

I am using the latest version of Forge, BDLib, and Just Enough Items.

**Comment by NolanSyKinsley** [comment]
Can confirm. Also happens with the mod called Cobble Popper.

**Comment by mezz** [comment]
Thanks for the report!

**Comment by bdew** [comment]
I tried to see if it's something on my side, but the crash happens with just JEI installed, without BDLib.

https://gist.github.com/bdew/96b5cbcd750ca4bd5910978a3a8ac2eb

**Comment by TehNut** [comment]
That is because of the changes to the Forge registry. Try on <1819

**Comment by mezz** [comment]
I'll take a look now.

**Comment by mezz** [comment]
I had no issue with the latest JEI, BDLib, and Forge (as of a few minutes ago).

Please try again with the latest versions, if it does crash then JEI should give a more useful error message this time.
