### ISSUE TITLE
Error | 1.16.5 Latest | NoSuchFieldException

### ISSUE THREAD

**Issue by Kroko1337** [mezz/JustEnoughItems#2379]
java.lang.NoSuchFieldException: MODDED_REMOTE
	at java.lang.Class.getField(Class.java:1703) ~[?:1.8.0_51]
	at sirttas.dpanvil.interaction.jei.JeiLoadDelayer.setup(JeiLoadDelayer.java:27) [?:1.16.4-1.1.6]
	at sirttas.dpanvil.data.network.proxy.ClientProxy.setupClient(ClientProxy.java:29) [?:1.16.4-1.1.6]
	at sirttas.dpanvil.data.network.proxy.ClientProxy$$Lambda$11820/849128132.accept(Unknown Source) [?:1.16.4-1.1.6]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2934/1860010238.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2560/56667145.invoke(Unknown Source) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) [eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) [?:36.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3764/2057389797.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]

**Comment by Ommina** [comment]
> at sirttas.dpanvil.interaction.jei.JeiLoadDelayer.setup(JeiLoadDelayer.java:27) [?:1.16.4-1.1.6]

"dpanvil".  Whatever that is.  Normally I'd check the crash report and see if I can figure out the mod, but, alas.

**Comment by Crazydude323** [comment]
dpanvil is DataPack Anvil. It's to help when you're developing with Datapacks, and it's required by Elemental Craft.

**Comment by mezz** [comment]
Thanks for the report!
Please report this bug to DataPack Anvil: https://github.com/Sirttas/DataPack-Anvil/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
