### ISSUE TITLE
Jei crash when I try to see the craft 

### ISSUE THREAD

**Issue by livehass** [mezz/JustEnoughItems#243]
normaly crash with e-flux mod and neotech mod  

minecraft crash log http://pastebin.com/pfeTZDUr
at elec332.core.client.model.RenderingRegistry$LinkedItemModel.handleItemState(RenderingRegistry.java:185)
    at net.minecraft.client.renderer.ItemModelMesher.func_178089_a(ItemModelMesher.java:55)
    at net.minecraft.client.renderer.entity.RenderItem.func_175042_a(RenderItem.java:344)
    at net.minecraft.client.renderer.entity.RenderItem.func_180450_b(RenderItem.java:395)
    at mezz.jei.gui.ingredients.ItemStackRenderer.draw(ItemStackRenderer.java:35)
    at mezz.jei.gui.ingredients.ItemStackRenderer.draw(ItemStackRenderer.java:16)
    at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:128)
    at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:70)
    at mezz.jei.gui.RecipeLayout.draw(RecipeLayout.java:90)
    at mezz.jei.gui.RecipesGui.func_73863_a(RecipesGui.java:156)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:311)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1104)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

if you can help me I will be grateful :).

**Comment by mezz** [comment]
Thanks for the report!
This is a crash from ElecCore, [please report to them here](https://github.com/Elecs-Mods/ElecCore/issues).
