### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by cmwise1970** [mezz/JustEnoughItems#2476]
-Two of my saves are permanently crashed..after hours of play. right clicking on a chair, bench etc gives a message of "click right shift" to exit, game crashes and cannot log on. 

--- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/29/21, 9:05 PM
Description: Ticking entity

java.lang.NoSuchMethodError: 'void com.mrh0.buildersaddition.entity.SeatEntity.remove(boolean)'
	at com.mrh0.buildersaddition.entity.SeatEntity.m_8119_(SeatEntity.java:43) ~[buildersaddition-1.17.1-20210730b.jar%2352!:1.17.1-20210730b] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:623) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:470) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_143264_(ServerLevel.java:384) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(SourceFile:54) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:818) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:85) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:683) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mrh0.buildersaddition.entity.SeatEntity.m_8119_(SeatEntity.java:43) ~[buildersaddition-1.17.1-20210730b.jar%2352!:1.17.1-20210730b] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:623) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: buildersaddition:seat (com.mrh0.buildersaddition.entity.SeatEntity)
	Entity ID: 100
	Entity Name: entity.buildersaddition.seat
	Entity's Exact location: 1139.50, 73.45, -418.50
	Entity's Block location: World: (1139,73,-419), Section: (at 3,9,13 in 71,4,-27; chunk contains blocks 1136,0,-432 to 1151,255,-417), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:470) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_143264_(ServerLevel.java:384) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(SourceFile:54) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:365) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['CMWISE1970'/88, l='ServerLevel[New World Forge 44 2]', x=1139.50, y=73.58, z=-418.50]]
	Chunk stats: 2836
	Level dimension: minecraft:overworld
	Level spawn location: World: (-96,64,-160), Section: (at 0,0,0 in -6,4,-10; chunk contains blocks -96,0,-160 to -81,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2402786 game time, 2953756 day time
	Level name: New World Forge 44 2
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 146865 (now: false), thunder time: 149303 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:818) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:85) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:683) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.17.1-20210706.113038-srg.jar%2356!:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:831) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 895094400 bytes (853 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 760
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1187
	Graphics card #0 versionInfo: DriverVersion=26.21.14.3086
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.40
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 18754.53
	Virtual memory used (MB): 8526.88
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 1 / 8; [ServerPlayer['CMWISE1970'/88, l='ServerLevel[New World Forge 44 2]', x=1139.50, y=73.58, z=-418.50]]
	Data Packs: vanilla, mod:forge, file/desert-village-1-17.zip, file/fish-up-ores-v1-0-1-e1700.zip, file/starter-bundle-1-17-e1830.zip, file/treecapitator-v2-7-2.zip, mod:easy_villagers (incompatible), mod:guardvillagers (incompatible), mod:xaerominimap (incompatible), mod:buildersaddition (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.0.44-universal.jar                |Forge                         |forge                         |37.0.44             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		easy_villagers-1.17.1-1.0.5.jar                   |Easy Villagers                |easy_villagers                |1.17.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		buildersaddition-1.17.1-20210730b.jar             |Builders Crafts & Addition    |buildersaddition              |1.17.1-20210730b    |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.17.1.1.3.0.jar                   |Guard Villagers               |guardvillagers                |1.2.4               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.16.0_Forge_1.17.1.jar           |Xaero's Minimap               |xaerominimap                  |21.16.0             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 119787b1-305f-41c4-a715-01e62f945091
	FML: 37.0
	Forge: net.minecraftforge:37.0.44Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

For suggestions:
 * Please do not suggest features from NEI. [See this spreadsheet](https://goo.gl/MQ0f3R) before requesting.

**Comment by mezz** [comment]
Thanks for the report!
This is an issue with another mod, please report it to them here and link back to this issue: https://github.com/mrh0/buildersaddition/issues
