### ISSUE TITLE
[1.16.5] JEI versions 7.7.1.119 and higher don't display HOP Graphite recipe from IE

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#2482]
Hello,

The latest releases of JEI do not correctly display the HOP Graphite recipe from Immersive Engineering's Industrial Squeezer. The below screen shot is from a new install with only:

Forge 36.2.4
JEI 7.7.1.121
Immersive Engineering 5.0.3-138
![2021-09-03_13 23 13](https://user-images.githubusercontent.com/51542538/132050730-f51d157c-6273-484a-bafa-724ea1826c2d.png)

Reverting to JEI version 7.7.1.118 (119 and 120 both crash when trying to view this recipe) fixes the problem.

**Comment by ghost** [comment]
Here's a log:

`[04Sep2021 10:30:00.090] [Render thread/ERROR] [mezz.jei.gui.recipes.RecipeLayout/]: Error caught from Recipe Category: blusunrize.immersiveengineering.common.util.compat.jei.squeezer.SqueezerRecipeCategory
java.lang.IllegalArgumentException: FluidStack value must not be empty. net.minecraftforge.fluids.FluidStack@ac05ddd1 minecraft:empty
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:224) ~[jei:7.7.1.121]
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getWildcardId(FluidStackHelper.java:85) ~[jei:7.7.1.121]
	at mezz.jei.plugins.vanilla.ingredients.fluid.FluidStackHelper.getWildcardId(FluidStackHelper.java:26) ~[jei:7.7.1.121]
	at mezz.jei.ingredients.IngredientInformation.getUniqueIdsWithWildcard(IngredientInformation.java:63) ~[jei:7.7.1.121]
	at mezz.jei.ingredients.IngredientBlacklistInternal.isIngredientBlacklistedByApi(IngredientBlacklistInternal.java:24) ~[jei:7.7.1.121]
	at mezz.jei.ingredients.IngredientFilter.isIngredientVisible(IngredientFilter.java:424) ~[jei:7.7.1.121]
	at mezz.jei.ingredients.IngredientFilter.isIngredientVisible(IngredientFilter.java:420) ~[jei:7.7.1.121]
	at mezz.jei.ingredients.IngredientManager.isIngredientVisible(IngredientManager.java:256) ~[jei:7.7.1.121]
	at mezz.jei.gui.ingredients.GuiIngredient.filterOutHidden(GuiIngredient.java:141) ~[jei:7.7.1.121]
	at mezz.jei.gui.ingredients.GuiIngredient.set(GuiIngredient.java:123) ~[jei:7.7.1.121]
	at mezz.jei.gui.ingredients.GuiIngredientGroup.set(GuiIngredientGroup.java:119) ~[jei:7.7.1.121]
	at mezz.jei.gui.ingredients.GuiIngredientGroup.set(GuiIngredientGroup.java:127) ~[jei:7.7.1.121]
	at mezz.jei.gui.ingredients.GuiFluidStackGroup.set(GuiFluidStackGroup.java:13) ~[jei:7.7.1.121]
	at blusunrize.immersiveengineering.common.util.compat.jei.squeezer.SqueezerRecipeCategory.setRecipe(SqueezerRecipeCategory.java:67) ~[immersiveengineering:?]
	at blusunrize.immersiveengineering.common.util.compat.jei.squeezer.SqueezerRecipeCategory.setRecipe(SqueezerRecipeCategory.java:30) ~[immersiveengineering:?]
	at mezz.jei.gui.recipes.RecipeLayout.create(RecipeLayout.java:72) ~[jei:7.7.1.121]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:178) ~[jei:7.7.1.121]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:164) ~[jei:7.7.1.121]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:490) ~[jei:7.7.1.121]
	at mezz.jei.gui.recipes.RecipesGui.onStateChange(RecipesGui.java:542) ~[jei:7.7.1.121]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setState(RecipeGuiLogic.java:107) ~[jei:7.7.1.121]
	at mezz.jei.gui.recipes.RecipeGuiLogic.setFocus(RecipeGuiLogic.java:60) ~[jei:7.7.1.121]
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:425) ~[jei:7.7.1.121]
	at mezz.jei.input.InputHandler.handleFocusKeybinds(InputHandler.java:313) ~[jei:7.7.1.121]
	at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:281) ~[jei:7.7.1.121]
	at mezz.jei.input.InputHandler.onGuiKeyboardEvent(InputHandler.java:123) ~[jei:7.7.1.121]
	at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) ~[jei:7.7.1.121]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onGuiKeyPressedPost(ForgeHooksClient.java:681) ~[forge:?]
	at net.minecraft.client.KeyboardListener.lambda$keyPress$4(KeyboardListener.java:303) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?]
	at net.minecraft.client.KeyboardListener.func_197961_a(KeyboardListener.java:293) ~[?:?]
	at net.minecraft.client.KeyboardListener.func_228003_c_(KeyboardListener.java:391) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?]
	at net.minecraft.client.KeyboardListener.func_228001_b_(KeyboardListener.java:390) ~[?:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:37) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:109) ~[?:?]
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:305) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.4.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]`

**Comment by mezz** [comment]
Thanks for the report!
This appears to be an issue on IE's side, they have a FluidStack with 0 fluid in it.
I will follow the other issue there.
