### ISSUE TITLE
JEI crashes when trying to display recipe on multiplayer (1.10.2)

### ISSUE THREAD

**Issue by QuarkUpParticle** [mezz/JustEnoughItems#2503]
When clicking on an item on the menu or using R or U in the inventory, the client crashes if the item is crafted in a crafting table i believe because it works fine on modded crafting stations. The issue does not happen in singleplayer.

This issue does not resolve by trying other versions of JEI

latest crash-report :
https://gist.github.com/QuarkUpParticle/4bfc495e4a7b960fe502d446422bc30a

**Comment by mezz** [comment]
Thanks for the report!

```
-- Item being rendered --
Details:
	Item Type: com.rwtema.extrautils2.backend.XUItemBlock@76a05822
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:228)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:27)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21)
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:148)
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:156)
	at mezz.jei.gui.recipes.RecipeCategoryCraftingItems.draw(RecipeCategoryCraftingItems.java:115)
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:206)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
```

This seems to be an old issue with ExtraUtilities:
https://github.com/rwtema/Extra-Utilities-2-Source/issues/41
