### ISSUE TITLE
Crash Report in Craft Menu 

### ISSUE THREAD

**Issue by roseteeth** [mezz/JustEnoughItems#2522]
Hello! My game has been crashing with just jei for 1.17.1 (tried both 0.25 & 0.26) and forge 1.17.1 installed and no other mods, only when I open the craft/items menu. Sometimes it crashes if I switch to the vanilla recipie menu and try to switch back to jei, sometimes it crashes if I try to switch at all, and one time it crashed when I was trying to make a forge, one time it crashed instantly upon the menu being opened. I think the crashes occur more frequtenly if I have an item in my inventory.

Upon crashing this error is displayed: The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen
Exit Code: 255

I would appreciate it if you could please look into this, as I would really like to play using this mod. Thank you for all of your work and dedication! :) 

**FULL REPORT:** 
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 12.10.2021, 19:41
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.lambda$gatherTooltipComponents$14(ForgeHooksClient.java:1126) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:520) ~[?:?] {}
	at java.util.stream.IntPipeline.max(IntPipeline.java:483) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.gatherTooltipComponents(ForgeHooksClient.java:1127) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.gatherTooltipComponents(ForgeHooksClient.java:1109) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.renderComponentToolTip(Screen.java:212) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.renderComponentTooltip(Screen.java:204) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.recipebook.RecipeBookPage.m_100417_(RecipeBookPage.java:118) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.recipebook.RecipeBookComponent.m_100361_(RecipeBookComponent.java:289) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_6305_(SourceFile:97) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:392) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:385) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.85.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.lambda$gatherTooltipComponents$14(ForgeHooksClient.java:1126) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.IntPipeline.reduce(IntPipeline.java:520) ~[?:?] {}
	at java.util.stream.IntPipeline.max(IntPipeline.java:483) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.gatherTooltipComponents(ForgeHooksClient.java:1127) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.gatherTooltipComponents(ForgeHooksClient.java:1109) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at net.minecraft.client.gui.screens.Screen.renderComponentToolTip(Screen.java:212) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.renderComponentTooltip(Screen.java:204) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.recipebook.RecipeBookPage.m_100417_(RecipeBookPage.java:118) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.recipebook.RecipeBookComponent.m_100361_(RecipeBookComponent.java:289) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_6305_(SourceFile:97) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:392) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:385) ~[forge-1.17.1-37.0.85-universal.jar%2358!:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.InventoryScreen
	Mouse location: Scaled: (88, 92). Absolute: (177.000000, 184.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Wolfpaw007'/329, l='ClientLevel', x=-0.86, y=69.00, z=-73.76]]
	Chunk stats: 441, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-11,67,-65), Section: (at 5,3,15 in -1,4,-5; chunk contains blocks -16,0,-80 to -1,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1233 game time, 1233 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:364) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2245) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:676) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2354!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.0.85.jar%2322!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, New_Wayukian_Java_1.17.zip

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.4.0-73-generic
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 929286864 bytes (886 MiB) / 1778384896 bytes (1696 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
	Identifier: Intel64 Family 6 Model 61 Stepping 4
	Microarchitecture: Broadwell (Client)
	Frequency (GHz): 2,10
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: HD Graphics 5500
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256,00
	Graphics card #0 deviceId: 0x1616
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5917,27
	Virtual memory used (MB): 4794,62
	Swap memory total (MB): 3998,00
	Swap memory used (MB): 1074,25
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.17.1-forge-37.0.85
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Mesa Intel(R) HD Graphics 5500 (BDW GT2) GL version 4.6 (Core Profile) Mesa 20.2.6, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/New_Wayukian_Java_1.17.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
	Player Count: 1 / 8; [ServerPlayer['Wolfpaw007'/329, l='ServerLevel[New World]', x=-0.86, y=69.00, z=-73.76]]
	Data Packs: vanilla, mod:forge, mod:jei
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.17.1-37.0.85-universal.jar                |Forge                         |forge                         |37.0.85             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		jei-1.17.1-8.1.0.26.jar                           |Just Enough Items             |jei                           |8.1.0.26            |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 0abe72d2-2d15-4f72-b874-39604d4b2eb1
	FML: 37.0
	Forge: net.minecraftforge:37.0.85
```

**Comment by mezz** [comment]
Thanks for the report!
Can you try JEI version 8.2.0.32 (or higher) to see if it fixes this issue for you?
