### ISSUE TITLE
pack works without jei, but crashes when jei is added

### ISSUE THREAD

**Issue by nivanda** [mezz/JustEnoughItems#2605]
My friend made a pack to play on his server, but he didn't add jei. And for me it's almost impossible to play without jei.
Now here is the problem, whenever I add jei to the mod folder, the game just won't run. here is the error:
```
[13/12/2021 15:35:38 PM] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.
[13/12/2021 15:35:38 PM] Checking for updated files!
[13/12/2021 15:35:38 PM] Error trying to delete the directory **USERSDIR**\temp\natives-44832e19414940e794e4170707858d40
[13/12/2021 15:35:38 PM] java.nio.file.AccessDeniedException: **USERSDIR**\temp\natives-44832e19414940e794e4170707858d40\SAPIWrapper_x64.dll
[13/12/2021 15:35:38 PM] 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
[13/12/2021 15:35:38 PM] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[13/12/2021 15:35:38 PM] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[13/12/2021 15:35:38 PM] 	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
[13/12/2021 15:35:38 PM] 	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[13/12/2021 15:35:38 PM] 	at java.nio.file.Files.delete(Files.java:1126)
[13/12/2021 15:35:38 PM] 	at com.atlauncher.utils.walker.DeleteDirVisitor.visitFile(DeleteDirVisitor.java:30)
[13/12/2021 15:35:38 PM] 	at com.atlauncher.utils.walker.DeleteDirVisitor.visitFile(DeleteDirVisitor.java:27)
[13/12/2021 15:35:38 PM] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
[13/12/2021 15:35:38 PM] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
[13/12/2021 15:35:38 PM] 	at com.atlauncher.utils.FileUtils.deleteDirectory(FileUtils.java:62)
[13/12/2021 15:35:38 PM] 	at com.atlauncher.data.Instance.lambda$launch$18(Instance.java:1103)
[13/12/2021 15:35:38 PM] 	at java.lang.Thread.run(Thread.java:748)
[13/12/2021 15:35:38 PM] java.nio.file.AccessDeniedException: **USERSDIR**\temp\natives-44832e19414940e794e4170707858d40\SAPIWrapper_x64.dll
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at com.atlauncher.utils.walker.DeleteDirVisitor.visitFile(DeleteDirVisitor.java:30)
	at com.atlauncher.utils.walker.DeleteDirVisitor.visitFile(DeleteDirVisitor.java:27)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.atlauncher.utils.FileUtils.deleteDirectory(FileUtils.java:62)
	at com.atlauncher.data.Instance.lambda$launch$18(Instance.java:1103)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mezz** [comment]
Thanks for the report!
Strangely, JEI is not involved in that error log. Please try reporting this to ATLauncher and see if they have more info.
