### ISSUE TITLE
JEI 1.16 Latest Beta crashes upon launching previously functional world

### ISSUE THREAD

**Issue by Shoes4Clues** [mezz/JustEnoughItems#2635]
[07:56:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file jei-server.toml of type SERVER for modid jei
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:61) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:104) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:94) ~[forge:?] {re:classloading}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:59) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.3.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.3.jar:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:57) ~[forge:?] {re:classloading}
	... 10 more
[07:56:35] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID d25793a3-7491-4de9-b27a-14e9bbfee643
[07:56:35] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\rednj\Desktop\MultiMC\instances\1.16.51\.minecraft\crash-reports\crash-2022-01-01_07.56.35-server.txt
[07:56:35] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[07:56:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[07:56:35] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[07:56:35] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.server.ServerWorld.func_175723_af()" because "serverworld1" is null
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:538) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:167) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:679) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by mezz** [comment]
Thanks for the report!
Please paste the contents of your `jei-server.toml` file here so I can take a look.
Then try deleting your `jei-server.toml` file, it seems like there is something invalid there that is causing the game to crash.

**Comment by CMAE2** [comment]
I encounter the same error with jei-1.18.1-9.1.2.54, but the file was never generated after clearing the config folder
[crash-2022-01-05_13.45.49-server.txt](https://github.com/mezz/JustEnoughItems/files/7817116/crash-2022-01-05_13.45.49-server.txt)
.

**Comment by mezz** [comment]
Hmm this is a pretty strange error. It looks like it's trying to read an existing file, but the file is not formatted correctly.
Are you sure that you have cleared the correct config folder? If you have multiple instances of modded Minecraft, it may be hiding in a different folder from the one you cleared.

**Comment by CMAE2** [comment]
I wont discount the possibility but I made sure to  only have one and the latest jar and removed the entire config folder, as expected when running the game everything was regenerated but the jei-server.tmol file and there is nothing in the jei folder also created in config, I had of of 1/7/2002/ 10:30 am tested loading the world with jei-1.18.1-9.1.2.61 and gave me this error
[crash-2022-01-07_10.30.44-server.txt](https://github.com/mezz/JustEnoughItems/files/7829770/crash-2022-01-07_10.30.44-server.txt)

**Comment by CMAE2** [comment]
it seams that some ware the code in the mod for creating the default config might have ben disabled by mistake, thus not crating the necessary file, however I do not know how prevalent this error is.

**Comment by Ommina** [comment]
@mezz

I don't know if you continue to follow the Forge repository with any regularity, but there has been some recent mumblings about a race condition causing config corruption.  (See https://github.com/MinecraftForge/MinecraftForge/issues/7963).

May be wholly unrelated to the issue(s) posted here, but seems worth mentioning.

**Comment by CMAE2** [comment]
thanks for showing this to me, But I had the config folder in windows file explorer and watched as the various config files were created fresh and jei-sever.tmol never generated. based on what I had seen (which was little) of this post, this might be a two part problem where something happens in forge and corrupts the file (it went from working to not working in a single day with no changes to the game between the two different loadings times) and the mod itself seams to fail to create the file when given the opportunity, though it dose create the jei-client.tmol. it is possible that whatever changes you and you group made from the 1.18.1 .50 beta of the mod might have caused a compatibility error when triggered resulting and improper configuration when loading any subsequent times thought this dose not explain why it can't recreate the file.

my suggestion is to look at the changes made to fix the gui bug of the .50 version and see if there was something missed the can interfere with forge in the creation and subsequent loading of the sever config file which I can only assume hold information on how the gui should be handled on the server. (I never got the chance to look in the file in question)

please note this is persisting with forge 1.18.1-39.0.10 with jei-1.18.1-9.1.2.61

**Comment by CMAE2** [comment]
question, by any chance dose the jei read and/or write to the fml.tmol file in any way when attempting to load the client or world in any small way? if so this may be the source or lead to the source of the error. just a thought that occurred to me. (I know c++ and python and have encountered similar errors when doing school related projects in those languages..)

**Comment by CMAE2** [comment]
I had foud the file in the sever config folder on the world save( I did not know it existed until today) looked in the file, noting was there, deleted it and loaded the world, now it works, something deleted the contents of the file.

**Comment by CMAE2** [comment]
sorry If I caused wasted effort, still want to know why the contents of the file was cleared

**Comment by Ommina** [comment]
Honestly, if you found the file and it was empty, that is still good to know.

Do you happen to remember if was zero bytes in size?

**Comment by CMAE2** [comment]
No sadly I do not, however, if this was the case my system would not have recognized it, the meta data of the file was there, but the configurations won't in there when opened in notepad. after removing, the file regenerated properly. I can only assume that something in the mod or forge blanked the file leaving it only as an empty tmol file which would take up space as the meta data for its identification and location where valid. like it  said in the console, failed to load not failed to locate, which would occur if the file had nothing extra, it sees the file but it returns nothing as there was nothing to return but null or 0.

**Comment by CMAE2** [comment]
looking back, I think (can't be positive) that it had a size to it somthing K, :| I had just realised I was saying tmol when it is toml 😅

**Comment by CMAE2** [comment]
conformed it was blanked 0K no data. I did a test to see if the file type when empty shows a size and no it was 0K
