### ISSUE TITLE
Crash when crafting create sandpaper

### ISSUE THREAD

**Issue by cpw** [mezz/JustEnoughItems#2636]
Thank you for reporting!

For issues:
 * If the issue seems to affect only one mod, report to them instead of here.
 * Remove NEI and FEI to see if they are causing the issue before reporting.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

It's an odd one. The only change was updating JEI to latest 9.1.2.50. It is confirmed working in the prior version (9.1.1.48). I had two identical crashes, so it seems highly reproducible.

[crash-2022-01-01_14.13.36-client.txt](https://github.com/mezz/JustEnoughItems/files/7798117/crash-2022-01-01_14.13.36-client.txt)

**Comment by PureTryOut** [comment]
I have the same problem but with other mods, Create is not installed here. Happens to multiple persons. Issue is fixed by downgrading to 9.1.1.48.

**Comment by Ommina** [comment]
~~font and ingredient look a teeny bit reversed.~~

~~src/main/java/mezz/jei/gui/TooltipRenderer.java~~

~~(I feel like I should be able to provide a link directly to the code, but I struggling to find a way to do so.  Sorry!)~~

I've very much got myself lost -- so striking this all out for now.  What I was totally convinced of an hour ago I'm now discarding.

**Comment by taj1994** [comment]
Same issue here. Game crashes with 9.1.2.50 installed. Reverted to 9.1.1.48, and no more crashes

**Comment by emmalineautumn** [comment]
I created a fresh install with just JEI 9.1.2.50 and Flywheel 0.5.0a and the crash still exists. Removing one or the other prevents the crash, but both being enabled leads to crashes

**Comment by Potatomonium** [comment]
Getting the same crash since updating to 9.1.2.50.    Flywheel isn't the issue for me as  I don't have it installed

**Comment by muddykat-tech** [comment]
> Same issue here. Game crashes with 9.1.2.50 installed. Reverted to 9.1.1.48, and no more crashes

Had the same issue, it would crash when in a crafting table I used Oak Logs to Wood planks recipe, hovering over the planks would crash the game with the 

Unknown ingredient class: class net.minecraft.client.gui.Font

issue

**Comment by MinuteLicence** [comment]
Same issue here, crafting object at all is causing the crash, Flywheel & create both installed

**Comment by Eelt** [comment]
My mod Voluminous Energy also seems to have a similar crash when users are clicking on the recipe click area on my Block Entity's screens:

```
[02Jan.2022 17:06:45.808] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Unknown ingredient class: class net.minecraft.client.gui.Font
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4279/0x0000000800b773e8@34e91d1d
java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.client.gui.Font
	at TRANSFORMER/jei@9.1.2.50/mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:217)
	at TRANSFORMER/jei@9.1.2.50/mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:199)
	at TRANSFORMER/jei@9.1.2.50/mezz.jei.ingredients.IngredientManager.getIngredientRenderer(IngredientManager.java:122)
	at TRANSFORMER/jei@9.1.2.50/mezz.jei.gui.TooltipRenderer.getFont(TooltipRenderer.java:54)
	at TRANSFORMER/jei@9.1.2.50/mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:35)
	at TRANSFORMER/jei@9.1.2.50/mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:26)
	at TRANSFORMER/jei@9.1.2.50/mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:128)
	at TRANSFORMER/jei@9.1.2.50/mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.9/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:379)
	at TRANSFORMER/forge@39.0.9/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:371)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:886)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.9/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)
```

My mod is compiled against Forge 38.0.16 and JEI 1.18-9.0.0.40 for broader compatibility (with both 1.18 and 1.18.1), but this issue appears to affect JEI 1.18.1-9.1.2.50 only.

To me this looks like JEI is trying to treat `net.minecraft.client.gui.Font` as an ingredient class, which is obviously not the case, hence causing the crash to desktop.

**Comment by mezz** [comment]
Thanks for the report cpw!
This has been fixed in the latest version, which will be released shortly.
dcd7d2b
