### ISSUE TITLE
8.3.1.51 error

### ISSUE THREAD

**Issue by Duelm89HUN** [mezz/JustEnoughItems#2642]
Well, I ran into a problem that fresh mode is going well, doing its thing. However, I also use Voluminous Energy mode, these machines have worked so far. I make a machine, stop the game and quit. I deleted the configuration files and updated back both modes, of course the game was error free.

**Comment by Duelm89HUN** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2022. 01. 02. 13:19
Description: Rendering screen

java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.client.gui.Font
	at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:217) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:199) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.getIngredientRenderer(IngredientManager.java:122) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.getFont(TooltipRenderer.java:58) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:39) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:26) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:141) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:397) ~[forge-1.17.1-37.1.1-universal.jar%2395!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:389) ~[forge-1.17.1-37.1.1-universal.jar%2395!:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.17.1-20210706.113038-srg.jar%2391!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2391!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2391!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2391!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:217) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:199) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.getIngredientRenderer(IngredientManager.java:122) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.getFont(TooltipRenderer.java:58) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:39) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:26) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:141) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) ~[jei-1.17.1-8.3.1.51.jar%2375!:8.3.1.51] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:397) ~[forge-1.17.1-37.1.1-universal.jar%2395!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:389) ~[forge-1.17.1-37.1.1-universal.jar%2395!:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: com.veteam.voluminousenergy.blocks.screens.CrusherScreen
	Mouse location: Scaled: (235, 102). Absolute: (471.000000, 205.000000)
	Screen size: Scaled: (463, 265). Absolute: (925, 530). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Duelm89'/63, l='ClientLevel', x=148.62, y=66.00, z=-295.66]]
	Chunk stats: 625, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (-224,65,-64), Section: (at 0,1,0 in -14,4,-4; chunk contains blocks -224,0,-64 to -209,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 45917 game time, 45917 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:364) ~[client-1.17.1-20210706.113038-srg.jar%2391!:?] {re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:runtimedistcleaner:A,re:mixin,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2245) ~[client-1.17.1-20210706.113038-srg.jar%2391!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:676) ~[client-1.17.1-20210706.113038-srg.jar%2391!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2391!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5175643592 bytes (4935 MiB) / 7180648448 bytes (6848 MiB) up to 7180648448 bytes (6848 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3,10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 1030
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x1d01
	Graphics card #0 versionInfo: DriverVersion=26.21.14.4166
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 22464,55
	Virtual memory used (MB): 13889,19
	Swap memory total (MB): 6142,19
	Swap memory used (MB): 107,32
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx6836M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.17.1-forge-37.1.1
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: GeForce GT 1030/PCIe/SSE2 GL version 3.2.0 NVIDIA 441.66, NVIDIA Corporation
	Window size: 925x530
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, charmonium/journeyman
	Current Language: Magyar (Magyarország)
	CPU: 4x Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
	Player Count: 1 / 8; [ServerPlayer['Duelm89'/63, l='ServerLevel[Teszt]', x=148.62, y=66.00, z=-295.66]]
	Data Packs: vanilla, mod:ambientsounds (incompatible), mod:supermartijn642configlib (incompatible), mod:quarryplus, mod:redstonepen (incompatible), mod:creativecore (incompatible), mod:jei, mod:supermartijn642corelib (incompatible), mod:tesseract, mod:fluidtank, mod:assortedtools (incompatible), mod:assortedcore (incompatible), mod:pipez (incompatible), mod:enchantmentmachine (incompatible), mod:immersiveweapons, mod:patchouli (incompatible), mod:xaerominimap (incompatible), mod:xaeroworldmap (incompatible), mod:travelersbackpack (incompatible), mod:assemblylinemachines, mod:bno (incompatible), mod:wirelessredstone, mod:expandedstorage, mod:solarenergy (incompatible), mod:voluminousenergy (incompatible), mod:electrodynamics (incompatible), mod:chunkloaders, mod:fallingtree (incompatible), mod:ninjaphenix_container_lib, mod:cloth_config (incompatible), mod:forge, mod:duplication_table (incompatible)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		kotori_scala@2.13.6-build-4
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		AmbientSounds_v4.0.4_mc1.17.1.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.17.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.17-17.7.jar            |QuarryPlus                    |quarryplus                    |17.7                |DONE      |Manifest: 1a:13:52:63:6f:dc:0c:ad:7f:8a:64:ac:46:58:8a:0c:90:ea:2c:5d:11:ac:4c:d4:62:85:c7:d1:00:fa:9c:76
		redstonepen-1.17.1-1.0.7.jar                      |Redstone Pen                  |redstonepen                   |1.0.7               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.3.0_mc1.17.1.jar                  |CreativeCore                  |creativecore                  |2.3.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.17.1-8.3.1.51.jar                           |Just Enough Items             |jei                           |8.3.1.51            |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.12-mc1.17.jar          |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.12              |DONE      |Manifest: NOSIGNATURE
		tesseract-1.0.24-mc1.17.jar                       |Tesseract                     |tesseract                     |1.0.24              |DONE      |Manifest: NOSIGNATURE
		LargeFluidTank-17.0.2.jar                         |FluidTank                     |fluidtank                     |17.0.2              |DONE      |Manifest: 1a:13:52:63:6f:dc:0c:ad:7f:8a:64:ac:46:58:8a:0c:90:ea:2c:5d:11:ac:4c:d4:62:85:c7:d1:00:fa:9c:76
		assortedtools-1.17.1-3.0.2.jar                    |Assorted Tools                |assortedtools                 |1.17.1-3.0.2        |DONE      |Manifest: NOSIGNATURE
		assortedcore-1.17.1-2.0.2.jar                     |Assorted Core                 |assortedcore                  |1.17.1-2.0.2        |DONE      |Manifest: NOSIGNATURE
		pipez-1.17.1-1.0.10.jar                           |Pipez                         |pipez                         |1.17.1-1.0.10       |DONE      |Manifest: NOSIGNATURE
		EnchantmentMachine-1.17.1-1.0.7.jar               |Enchantment machine           |enchantmentmachine            |1.0.7               |DONE      |Manifest: NOSIGNATURE
		ImmersiveWeapons-1.17.1-1.12.1.jar                |Immersive Weapons             |immersiveweapons              |1.17.1-1.12.1       |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.17.1-57.jar                           |Patchouli                     |patchouli                     |1.17.1-57           |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_21.23.0_Forge_1.17.1.jar           |Xaero's Minimap               |xaerominimap                  |21.23.0             |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.19.0_Forge_1.17.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.19.0              |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.17.1-6.0.5.jar                |Traveler's Backpack           |travelersbackpack             |6.0.5               |DONE      |Manifest: NOSIGNATURE
		assemblylinemachines-1.17.1-1.3.0.4.jar           |Assembly Line Machines        |assemblylinemachines          |1.17.1-1.3.0.4      |DONE      |Manifest: NOSIGNATURE
		BasicNetherOres-1.17.1-6.0.1.jar                  |Basic Nether Ores             |bno                           |6.0.1               |DONE      |Manifest: NOSIGNATURE
		WirelessRedstone-1.17.1-1.0.0-beta-3.jar          |Wireless Redstone             |wirelessredstone              |1.0.0-beta-3        |DONE      |Manifest: NOSIGNATURE
		expandedstorage-7.3.6+1.17.1.jar                  |Expanded Storage              |expandedstorage               |7.3.6               |DONE      |Manifest: NOSIGNATURE
		solarenergy-1.17.1-0.4.0.1.jar                    |Solar Energy                  |solarenergy                   |0.4.0.1             |DONE      |Manifest: NOSIGNATURE
		VoluminousEnergy-1.17.1-0.2+Alpha+4.jar           |Voluminous Energy             |voluminousenergy              |1.17.1-0.2 Alpha 4  |DONE      |Manifest: NOSIGNATURE
		Electrodynamics-1.17.1-0.5.1-2.jar                |Electrodynamics               |electrodynamics               |1.17.1-0.5.1-2      |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.1.7a-mc1.17.jar                    |Chunk Loaders                 |chunkloaders                  |1.1.7a              |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.17.1-2.14.5.jar                     |FallingTree                   |fallingtree                   |2.14.5              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		ninjaphenix-container-library-1.2.8+1.17.1.jar    |NinjaPhenix's Container Librar|ninjaphenix_container_lib     |1.2.8               |DONE      |Manifest: NOSIGNATURE
		cloth-config-5.2.47-forge.jar                     |Cloth Config v4 API           |cloth_config                  |5.2.47              |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.1.1-universal.jar                 |Forge                         |forge                         |37.1.1              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		DuplicationMod1.17.jar                            |Duplication Table             |duplication_table             |1.0.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e10a799e-1e56-4ac6-8a70-ed4f70cdd147
	FML: 37.1
	Forge: net.minecraftforge:37.1.1

**Comment by Ommina** [comment]
See #2636

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, which will be released shortly.
dcd7d2b
