### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RadekWeather** [mezz/JustEnoughItems#2643]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 02.01.2022, 14:00
Description: Rendering screen

java.lang.IllegalArgumentException: Unknown ingredient class: class net.minecraft.client.gui.Font
	at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:217) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:199) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.getIngredientRenderer(IngredientManager.java:122) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.getFont(TooltipRenderer.java:58) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:39) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:26) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:141) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:397) ~[forge-1.17.1-37.1.1-universal.jar%2368!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:389) ~[forge-1.17.1-37.1.1-universal.jar%2368!:?] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:699) ~[OptiFine_1.17.1_HD_U_H1.jar%2369!:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1274) ~[client-1.17.1-20210706.113038-srg.jar%2364!:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default,re:mixin,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2364!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2364!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2364!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:217) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.getIngredientType(IngredientManager.java:199) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.ingredients.IngredientManager.getIngredientRenderer(IngredientManager.java:122) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.getFont(TooltipRenderer.java:58) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:39) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.TooltipRenderer.drawHoveringText(TooltipRenderer.java:26) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:141) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at mezz.jei.events.EventBusHelper.lambda$registerWeakListener$2(EventBusHelper.java:116) ~[jei-1.17.1-8.3.1.51.jar%2362!:8.3.1.51] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:397) ~[forge-1.17.1-37.1.1-universal.jar%2368!:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:389) ~[forge-1.17.1-37.1.1-universal.jar%2368!:?] {re:classloading}
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:699) ~[OptiFine_1.17.1_HD_U_H1.jar%2369!:?] {re:classloading}
-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.InventoryScreen
	Mouse location: Scaled: (291, 78). Absolute: (1166.000000, 312.000000)
	Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Radek'/85, l='ClientLevel', x=420.88, y=76.00, z=633.43]]
	Chunk stats: 841, 574
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,68,227), Section: (at 0,4,3 in 12,4,14; chunk contains blocks 192,0,224 to 207,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 77688 game time, 65926 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:469) ~[client-1.17.1-20210706.113038-srg.jar%2364!:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2245) ~[client-1.17.1-20210706.113038-srg.jar%2364!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:676) ~[client-1.17.1-20210706.113038-srg.jar%2364!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2364!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 781753720 bytes (745 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3,29
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=27.20.12029.1000
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 1,60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 1,60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 18754,14
	Virtual memory used (MB): 12646,10
	Swap memory total (MB): 2432,00
	Swap memory used (MB): 34,41
	JVM Flags: 14 total; -XX:+UnlockExperimentalVMOptions -XX:-UseParallelGC -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	Launched Version: 1.17.1-forge-37.1.1
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: Radeon RX 580 Series GL version 3.2.14736 Core Profile Forward-Compatible Context 20.9.1 27.20.12029.1000, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: Polski (Polska)
	CPU: 8x Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz
	Player Count: 1 / 8; [ServerPlayer['Radek'/85, l='ServerLevel[Pogodowy test]', x=420.87, y=76.00, z=633.46]]
	Data Packs: vanilla, mod:sereneseasons, mod:forge, mod:clear_skies, mod:hungerstrike (incompatible), mod:jei, mod:configured (incompatible)
	OptiFine Version: OptiFine_1.17.1_HD_U_H1
	OptiFine Build: 20211104-012451
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.14736 Core Profile Forward-Compatible Context 20.9.1 27.20.12029.1000
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SereneSeasons-1.17.1-5.0.0.6-universal.jar        |Serene Seasons                |sereneseasons                 |1.17.1-5.0.0.6      |DONE      |Manifest: NOSIGNATURE
		configured-1.5.0-1.17.1.jar                       |Configured                    |configured                    |1.5.0               |DONE      |Manifest: NOSIGNATURE
		clear-skies-forge-mc117-2.0.89.jar                |Clear Skies                   |clear_skies                   |2.0.89              |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.1.1-universal.jar                 |Forge                         |forge                         |37.1.1              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		jei-1.17.1-8.3.1.51.jar                           |Just Enough Items             |jei                           |8.3.1.51            |DONE      |Manifest: NOSIGNATURE
		HungerStrike-1.17.1-5.0.0.jar                     |Hunger Strike                 |hungerstrike                  |1.17.1-5.0.0        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 7ec52e02-24a3-4d65-9851-83f69c90b42d
	FML: 37.1
	Forge: net.minecraftforge:37.1.1

**Comment by sufilevy** [comment]
Same thing here...

**Comment by ghen-git** [comment]
Hey, I found that switching out for version 9.1.2.48 fixes the issue, hope this helps

**Comment by Vapaman** [comment]
Same thing in 1.18.1, no optifine installed
[crash-2022-01-02_23.34.34-client.txt](https://github.com/mezz/JustEnoughItems/files/7799823/crash-2022-01-02_23.34.34-client.txt)

**Comment by Ommina** [comment]
See #2636

**Comment by Kiryonn** [comment]
same i crash when i try to craft planks from the crafting table. for some reasons it's okay with the player inventory. does not crash with tools too somehow (stone and wooden pickaxe).

**Comment by mezz** [comment]
Thanks for the report!
This has been fixed in the latest version, which will be released shortly.
dcd7d2b

**Comment by RadekWeather** [comment]
Thank you for your help :)
