### ISSUE TITLE
When I die, sometimes my bookmarks in the JEI disappear.

### ISSUE THREAD

**Issue by DrSigma4164** [mezz/JustEnoughItems#2692]
When I die (I don't quite understand if this is the reason) my bookmarks on the left in the initiator disappear. I've attached a log so you can better understand why this is happening. Let me know if you need anything else.
[Gits](https://gist.github.com/260b998a49e3b2e0bd5b3e36ea1982f0.git)

**Comment by mezz** [comment]
Thanks for the report!
Looking at the log, it seems like some other mod is messing with JEI's bookmarks and is probably causing the issue:
```
[10:12:32] [main/WARN]: Could not modify JEI bookmark list: 
java.lang.NullPointerException: null
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:1.8.0_51]
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:1.8.0_51]
	at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_51]
	at io.github.noeppi_noeppi.mods.bongo.compat.JeiIntegration.getBookmarkList(JeiIntegration.java:63) ~[?:1.16.5-1.3.0]
	at io.github.noeppi_noeppi.mods.bongo.compat.JeiIntegration.setBookmarks(JeiIntegration.java:40) [?:1.16.5-1.3.0]
	at io.github.noeppi_noeppi.mods.bongo.Bongo.updateClient(Bongo.java:80) [?:1.16.5-1.3.0]
	at io.github.noeppi_noeppi.mods.bongo.network.BongoUpdateHandler.lambda$handle$0(BongoUpdateHandler.java:11) [?:1.16.5-1.3.0]
	at io.github.noeppi_noeppi.mods.bongo.network.BongoUpdateHandler$$Lambda$38051/748563207.run(Unknown Source) [?:1.16.5-1.3.0]
```
Please report this bug to https://www.curseforge.com/minecraft/mc-mods/bongo and see if they know anything more.
