### ISSUE TITLE
Breaking change in ICustomCraftingCategoryExtension behavior with recipes with no output set

### ISSUE THREAD

**Issue by Hubry** [mezz/JustEnoughItems#2722]
```
[18:50:08] [Render thread/ERROR]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: Botania botania:dynamic/composite_lens class vazkii.botania.common.crafting.recipe.CompositeLensRecipe

java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4586) ~[?:?]
	at mezz.jei.plugins.vanilla.crafting.CraftingRecipeCategory.legacySetRecipe(CraftingRecipeCategory.java:100) ~[jei-1.18.1-9.3.3.95.jar%23124!/:9.3.3.95]
	at mezz.jei.plugins.vanilla.crafting.CraftingRecipeCategory.setRecipe(CraftingRecipeCategory.java:87) ~[jei-1.18.1-9.3.3.95.jar%23124!/:9.3.3.95]
[a few lines omitted]
	at mezz.jei.plugins.vanilla.VanillaPlugin.registerRecipes(VanillaPlugin.java:213) ~[jei-1.18.1-9.3.3.95.jar%23124!/:9.3.3.95]
```

https://github.com/mezz/JustEnoughItems/blob/7c1852965af182647f82c86ba47741ae71237ac3/src/main/java/mezz/jei/plugins/vanilla/crafting/CraftingRecipeCategory.java#L100

This gets hit even if a recipe declares an extension that sets the outputs itself using the old APIs but has an empty output in the recipe, eg. [Botania's custom recipe extensions](https://github.com/VazkiiMods/Botania/tree/45c84d0eed8f42280fab71441446dc174b1901c6/Forge/src/main/java/vazkii/botania/client/integration/jei/crafting). (Builds aren't out on CF yet, only on [Jared's jenkins](https://ci.blamejared.com/job/Violet%20Moon/job/Botania/job/1.18.x/) right now).

While I probably should update our JEI integration, this is still a breaking change.

**Comment by mezz** [comment]
Thanks for the report!
I think it doesn't matter how weird or broken the existing behavior is, the backward compatibility is supposed to support it.
This has been fixed in version 9.4.1.98
