### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by BraveCaperCat** [mezz/JustEnoughItems#2746]
### Steps to Reproduce the Crash

1. Launch minecraft

### Extra Notes (Optional)

No crash log: how?

### Crash Report

No crash log

**Comment by BraveCaperCat** [comment]
Crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  ThermalMJLoadingPlugin (Thermal MJ-1.0.0.jar)
  Fermion ASM Service (Fermion-1.0.2+hotfix.testless.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 3/7/22 6:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap.newNode(HashMap.java:1734)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at net.minecraft.nbt.NBTTagCompound.func_74782_a(NBTTagCompound.java:86)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:24)
	at net.minecraft.nbt.NBTTagCompound.func_74737_b(NBTTagCompound.java:452)
	at net.minecraft.item.ItemStack.func_77946_l(ItemStack.java:401)
	at mezz.jei.plugins.vanilla.anvil.AnvilRecipeMaker.getBookEnchantmentRecipes(AnvilRecipeMaker.java:91)
	at mezz.jei.plugins.vanilla.anvil.AnvilRecipeMaker.getBookEnchantmentRecipes(AnvilRecipeMaker.java:68)
	at mezz.jei.plugins.vanilla.anvil.AnvilRecipeMaker.getAnvilRecipes(AnvilRecipeMaker.java:51)
	at mezz.jei.plugins.vanilla.VanillaPlugin.register(VanillaPlugin.java:170)
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:213)
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:77)
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136)
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 629171424 bytes (600 MB) / 3817865216 bytes (3641 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 137 mods loaded, 137 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                            | Version               | Source                                            | Signature                                |
	|:------ |:----------------------------- |:--------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                     | 1.12.2                | minecraft.jar                                     | None                                     |
	| LCHIJA | mcp                           | 9.42                  | minecraft.jar                                     | None                                     |
	| LCHIJA | FML                           | 8.0.99.99             | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                         | 14.23.5.2859          | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | fermion.asm.service           | 1.0.2+hotfix          | minecraft.jar                                     | None                                     |
	| LCHIJA | fermion.asm                   | 1.0.2+hotfix          | minecraft.jar                                     | None                                     |
	| LCHIJA | bcrf.asm                      | 1.0.0                 | minecraft.jar                                     | None                                     |
	| LCHIJA | antiqueatlas                  | 4.6.3                 | antiqueatlas-1.12.2-4.6.3.jar                     | None                                     |
	| LCHIJA | crafttweaker                  | 4.1.20                | CraftTweaker2-1.12-4.1.20.674.jar                 | None                                     |
	| LCHIJA | aactadapter                   | 1.12.2-0.1.0          | aactadapter-1.12.2-0.1.0.jar                      | None                                     |
	| LCHIJA | buildcraftlib                 | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJA | buildcraftcore                | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJA | buildcraftfactory             | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJA | buildcrafttransport           | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJA | buildcraftsilicon             | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJA | additionalpipes               | 6.0.0.8               | additionalpipes-6.0.0.8.jar                       | None                                     |
	| LCHIJA | antiqueatlasoverlay           | 1.2                   | antiqueatlas-1.12.2-4.6.3.jar                     | None                                     |
	| LCHIJA | bdsandm                       | 0.0.24                | BarrelsDrumsStorageAndMore-0.0.24.jar             | None                                     |
	| LCHIJA | charset                       | 0.5.6.6               | Charset-Lib-0.5.6.6.jar                           | None                                     |
	| LCHIJE | jei                           | 4.16.1.301            | jei_1.12.2-4.16.1.301.jar                         | None                                     |
	| LCHIJ  | base                          | 3.14.0                | base-1.12.2-3.14.0.jar                            | None                                     |
	| LCHIJ  | betterstorage                 | 3.0.0.3               | BetterStorageToo-1.12.2-3.0.0.3.jar               | None                                     |
	| LCHIJ  | bookshelf                     | 2.3.590               | Bookshelf-1.12.2-2.3.590.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ  | buildcraftbuilders            | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJ  | buildcraftenergy              | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJ  | ic2                           | 2.8.170-ex112         | industrialcraft-2-2.8.170-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJ  | forestry                      | 5.8.2.387             | forestry_1.12.2-5.8.2.387.jar                     | None                                     |
	| LCHIJ  | buildcraftcompat              | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJ  | buildcraftrobotics            | 7.99.24.8             | buildcraft-all-7.99.24.8.jar                      | None                                     |
	| LCHIJ  | fermion                       | 1.0.2+hotfix.testless | Fermion-1.0.2+hotfix.testless.jar                 | cc2bf3016f756771230cdc4fac0ec50efdf8d212 |
	| LCHIJ  | bcrf                          | 1.5.4                 | buildcraft-rf-1.5.4.jar                           | None                                     |
	| LCHIJ  | chameleon                     | 1.12-4.1.3            | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LCHIJ  | ctm                           | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                         | None                                     |
	| LCHIJ  | chisel                        | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                      | None                                     |
	| LCHIJ  | chiselsandbits                | 14.33                 | chiselsandbits-14.33.jar                          | None                                     |
	| LCHIJ  | codechickenlib                | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ  | redstoneflux                  | 2.1.1                 | RedstoneFlux-1.12-2.1.1.1-universal.jar           | None                                     |
	| LCHIJ  | cofhcore                      | 4.6.6                 | CoFHCore-1.12.2-4.6.6.1-universal.jar             | None                                     |
	| LCHIJ  | cofhworld                     | 1.4.0                 | CoFHWorld-1.12.2-1.4.0.1-universal.jar            | None                                     |
	| LCHIJ  | endercore                     | 1.12.2-0.5.76         | EnderCore-1.12.2-0.5.76.jar                       | None                                     |
	| LCHIJ  | thermalfoundation             | 2.6.7                 | ThermalFoundation-1.12.2-2.6.7.1-universal.jar    | None                                     |
	| LCHIJ  | thermalexpansion              | 5.5.7                 | ThermalExpansion-1.12.2-5.5.7.1-universal.jar     | None                                     |
	| LCHIJ  | enderio                       | 5.3.70                | EnderIO-base-1.12.2-5.3.70.jar                    | None                                     |
	| LCHIJ  | enderiointegrationtic         | 5.3.70                | EnderIO-integration-tic-1.12.2-5.3.70.jar         | None                                     |
	| LCHIJ  | mantle                        | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LCHIJ  | tconstruct                    | 1.12.2-2.13.0.183     | TConstruct-1.12.2-2.13.0.183.jar                  | None                                     |
	| LCHIJ  | contenttweaker                | 1.12.2-4.10.0         | ContentTweaker-1.12.2-4.10.0.jar                  | None                                     |
	| LCHIJ  | ctgui                         | 1.0.0                 | CraftTweaker2-1.12-4.1.20.674.jar                 | None                                     |
	| LCHIJ  | crafttweakerjei               | 2.0.3                 | CraftTweaker2-1.12-4.1.20.674.jar                 | None                                     |
	| LCHIJ  | crafttweakerutils             | 0.7                   | crafttweakerutils-0.7.jar                         | None                                     |
	| LCHIJ  | ctintegration                 | 1.8.0                 | ctintegration-1.8.0.jar                           | None                                     |
	| LCHIJ  | cucumber                      | 1.1.3                 | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
	| LCHIJ  | diamond                       | 2.4a                  | diamond-2.4a.jar                                  | None                                     |
	| LCHIJ  | enderiobase                   | 5.3.70                | EnderIO-base-1.12.2-5.3.70.jar                    | None                                     |
	| LCHIJ  | enderioconduits               | 5.3.70                | EnderIO-conduits-1.12.2-5.3.70.jar                | None                                     |
	| LCHIJ  | enderiopowertools             | 5.3.70                | EnderIO-conduits-1.12.2-5.3.70.jar                | None                                     |
	| LCHIJ  | mekanism                      | 1.12.2-9.8.3.390      | Mekanism-1.12.2-9.8.3.390.jar                     | None                                     |
	| LCHIJ  | gasconduits                   | 5.3.70                | EnderIO-conduits-mekanism-1.12.2-5.3.70.jar       | None                                     |
	| LCHIJ  | refinedstorage                | 1.6.16                | refinedstorage-1.6.16.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJ  | enderioconduitsrefinedstorage | 5.3.70                | EnderIO-conduits-refinedstorage-1.12.2-5.3.70.jar | None                                     |
	| LCHIJ  | enderioendergy                | 5.3.70                | EnderIO-endergy-1.12.2-5.3.70.jar                 | None                                     |
	| LCHIJ  | enderiointegrationforestry    | 5.3.70                | EnderIO-integration-forestry-1.12.2-5.3.70.jar    | None                                     |
	| LCHIJ  | enderiointegrationticlate     | 5.3.70                | EnderIO-integration-tic-1.12.2-5.3.70.jar         | None                                     |
	| LCHIJ  | enderiomachines               | 5.3.70                | EnderIO-machines-1.12.2-5.3.70.jar                | None                                     |
	| LCHIJ  | enderiozoo                    | 5.3.70                | EnderIO-zoo-1.12.2-5.3.70.jar                     | None                                     |
	| LCHIJ  | enderstorage                  | 2.4.6.137             | EnderStorage-1.12.2-2.4.6.137-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJ  | fcl                           | 1.12.73               | FCL-1.12.73.jar                                   | None                                     |
	| LCHIJ  | frl                           | 1.0                   | FCL-1.12.73.jar                                   | None                                     |
	| LCHIJ  | tmt                           | 1.14                  | FCL-1.12.73.jar                                   | None                                     |
	| LCHIJ  | forgelin                      | 1.8.4                 | Forgelin-1.8.4.jar                                | None                                     |
	| LCHIJ  | fvtm                          | 3.7.62                | FVTM-3.7.62.jar                                   | None                                     |
	| LCHIJ  | gamestages                    | 2.0.123               | GameStages-1.12.2-2.0.123.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ  | mcjtylib_ng                   | 3.5.4                 | mcjtylib-1.12-3.5.4.jar                           | None                                     |
	| LCHIJ  | immcraft                      | 1.6.0                 | immcraft-1.12-1.6.0.jar                           | None                                     |
	| LCHIJ  | immersiveengineering          | 0.12-98               | ImmersiveEngineering-0.12-98.jar                  | None                                     |
	| LCHIJ  | immersive_energy              | 0.5.5                 | Immersive Energy-1.12.2-0.5.5.jar                 | None                                     |
	| LCHIJ  | immersivecables               | 1.3.2                 | ImmersiveCables-1.12.2-1.3.2.jar                  | None                                     |
	| LCHIJ  | immersivepetroleum            | 1.1.10                | immersivepetroleum-1.12.2-1.1.10.jar              | None                                     |
	| LCHIJ  | immersiveposts                | 0.2.1                 | ImmersivePosts-0.2.1.jar                          | 0ba8738eadcf158e7fe1452255a73a022fb15feb |
	| LCHIJ  | teslacorelib                  | 1.0.18                | tesla-core-lib-1.12.2-1.0.18.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ  | industrialforegoing           | 1.12.2-1.12.2         | industrialforegoing-1.12.2-1.12.13-237.jar        | None                                     |
	| LCHIJ  | ironbackpacks                 | 1.12.2-3.0.8-12       | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
	| LCHIJ  | ironbackpacksredone           | 4.0.0                 | IronBackpacks-1.12.2-4.0.0.jar                    | None                                     |
	| LCHIJ  | ironchest                     | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
	| LCHIJ  | ironjetpacks                  | 1.1.0                 | IronJetpacks-1.12-2-1.1.0.jar                     | None                                     |
	| LCHIJ  | irontanks                     | 1.12.2-2.1.0-beta.18  | irontanks-1.12.2-2.1.0-beta.18.jar                | None                                     |
	| LCHIJ  | jeresources                   | 0.9.2.60              | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
	| LCHIJ  | jeroreintegration             | 1.1.0                 | JEROreIntegration-1.12.2-1.1.0.jar                | None                                     |
	| LCHIJ  | journeymap                    | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                       | None                                     |
	| LCHIJ  | journeymapdefaults            | 1.12-0.0.2            | journeymapdefaults-1.0.jar                        | None                                     |
	| LCHIJ  | limelib                       | 1.7.12                | limelib-1.12.2-1.7.12.jar                         | None                                     |
	| LCHIJ  | immersivetech                 | 1.9.100               | MCTImmersiveTechnology-1.12.2-1.9.100.jar         | None                                     |
	| LCHIJ  | mekanismfluxified             | 1.0.0                 | mekanismfluxified-1.12.2-1.0.0.jar                | None                                     |
	| LCHIJ  | modroadworksreborn            | 0.0.3                 | modroadworksreborn-0.0.3.jar                      | None                                     |
	| LCHIJ  | mysticalagriculture           | 1.7.5                 | MysticalAgriculture-1.12.2-1.7.5.jar              | None                                     |
	| LCHIJ  | mysticalagradditions          | 1.3.2                 | MysticalAgradditions-1.12.2-1.3.2.jar             | None                                     |
	| LCHIJ  | mysticaladaptations           | 1.8.7                 | MysticalAdaptations-1.12.2-1.8.7.jar              | None                                     |
	| LCHIJ  | mysticalcreations             | 1.6.1                 | MysticalCreations-1.12.2-1.6.1.jar                | None                                     |
	| LCHIJ  | nevokacore                    | 1.0.2                 | nevoka-core-1.0.2.jar                             | None                                     |
	| LCHIJ  | nuclearcraft                  | 2o.5.5                | NuclearCraft-2o.5.5-1.12.2.jar                    | None                                     |
	| LCHIJ  | plp                           | 1.0                   | PLP_0.14.jar                                      | None                                     |
	| LCHIJ  | projecte                      | 1.12.2-PE1.4.1        | ProjectE-1.12.2-PE1.4.1.jar                       | None                                     |
	| LCHIJ  | playerstorage                 | 1.3.12                | projectstorage-1.12.2-1.3.jar                     | None                                     |
	| LCHIJ  | qmd                           | 1.0.4                 | QMD-1.0.4-1.12.2.jar                              | None                                     |
	| LCHIJ  | questionablyimmersive         | @VERSION@             | questionablyimmersive-1.12.2-0.1.0.jar            | None                                     |
	| LCHIJ  | reactor_turbines              | 1.2.2                 | reactor_turbines-1.2.2.jar                        | None                                     |
	| LCHIJ  | reborncore                    | 3.19.5                | RebornCore-1.12.2-3.19.5-universal.jar            | None                                     |
	| LCHIJ  | rebornstorage                 | 1.0.0                 | RebornStorage-1.12.2-3.3.4.1.jar                  | None                                     |
	| LCHIJ  | refined_avaritia              | 2.6                   | refined_avaritia-1.12.2-2.6.jar                   | None                                     |
	| LCHIJ  | refinedexchange               | 2.1.1                 | refinedexchange-2.1.1.jar                         | None                                     |
	| LCHIJ  | refinedrelocation             | 4.2.37                | RefinedRelocation_1.12.2-4.2.37.jar               | None                                     |
	| LCHIJ  | refinedstorageaddons          | 0.4.5                 | refinedstorageaddons-0.4.5.jar                    | None                                     |
	| LCHIJ  | refinedstoragerequestify      | ${version}            | refinedstoragerequestify-1.12.2-1.0.2-3.jar       | None                                     |
	| LCHIJ  | refstoragefluxified           | 1.0.0                 | refstoragefluxified-1.12.2-1.0.0.jar              | None                                     |
	| LCHIJ  | rslargepatterns               | 1.12.2-1.0.0.0        | RSLargePatterns-1.12.2-1.0.0.1.jar                | None                                     |
	| LCHIJ  | silentlib                     | 3.0.13                | SilentLib-1.12.2-3.0.14+168.jar                   | None                                     |
	| LCHIJ  | silentgear                    | 0.6.5                 | SilentGear-1.12.2-0.6.7+76.jar                    | None                                     |
	| LCHIJ  | silentgems                    | 2.8.18                | SilentsGems-1.12.2-2.8.22+327.jar                 | None                                     |
	| LCHIJ  | sgextraparts                  | 1.4.5                 | SGExtraParts-1.12.2-1.4.5-43.jar                  | None                                     |
	| LCHIJ  | silentgemstic                 | 0.1.1                 | SilentsGems-TiC-1.12.2-0.1.1-5.jar                | None                                     |
	| LCHIJ  | ssc                           | 0.0.1.1               | SimpleStorageCrates-0.0.1.1-MC1.12.2.jar          | None                                     |
	| LCHIJ  | stellarfluidconduits          | 1.12.2-1.0.0          | stellarfluidconduit-1.12.2-1.0.3.jar              | None                                     |
	| LCHIJ  | stevescarts                   | 2.4.32.137            | StevesCarts-1.12.2-2.4.32.137.jar                 | None                                     |
	| LCHIJ  | storagedrawers                | 5.2.2                 | StorageDrawers-1.12.2-5.4.2.jar                   | None                                     |
	| LCHIJ  | storagedrawersextra           | @VERSION@             | StorageDrawersExtras-1.12-3.1.0.jar               | None                                     |
	| LCHIJ  | storagetech                   | 6.0                   | StorageTech R6.0.jar                              | None                                     |
	| LCHIJ  | thermal_mj                    | 1.0.0                 | Thermal MJ-1.0.0.jar                              | None                                     |
	| LCHIJ  | thermalcultivation            | 0.3.6                 | ThermalCultivation-1.12.2-0.3.6.1-universal.jar   | None                                     |
	| LCHIJ  | thermaldynamics               | 2.5.6                 | ThermalDynamics-1.12.2-2.5.6.1-universal.jar      | None                                     |
	| LCHIJ  | thermalinnovation             | 0.3.6                 | ThermalInnovation-1.12.2-0.3.6.1-universal.jar    | None                                     |
	| LCHIJ  | thermallogistics              | 0.3-43                | thermallogistics-0.3-43.jar                       | None                                     |
	| LCHIJ  | thermalsolars                 | 1.12.2 V1.9.5         | thermalsolars-1.12.2-1.9.5.jar                    | None                                     |
	| LCHIJ  | thermaltinkering              | 1.0                   | ThermalTinkering-1.12.2-2.0.1.jar                 | None                                     |
	| LCHIJ  | industrialwires               | 1.7-39                | IndustrialWires-1.7-39.jar                        | None                                     |
	| LCHIJ  | morerefinedstorage            | 1.1.10                | morerefinedstorage-1.2.01.jar                     | None                                     |
	| LCHIJ  | fluidcows                     | 1.1.22                | FluidCows-1.1.22.jar                              | None                                     |
	| LCHIJ  | teslacorelib_registries       | 1.0.18                | tesla-core-lib-1.12.2-1.0.18.jar                  | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ThermalMJLoadingPlugin (Thermal MJ-1.0.0.jar)
  
Fermion ASM Service (Fermion-1.0.2+hotfix.testless.jar)
  net.thesilkminer.mc.fermion.asm.common.FermionTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 461.79' Renderer: 'GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/micha/curseforge/minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	
	FVTM Addons: 
	| plp  | Cam's Powerline Pack  | 1.0    | ...s\micha\curseforge\minecraft\Instances\Nucular\mods\PLP_0.14.jar|
	| fvtm | FVTM [Internal Addon] | 3.7.62 | ...icha\curseforge\minecraft\Instances\Nucular\mods\FVTM-3.7.62.jar|

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.19.5
		Runtime Debofucsation 1
		Invalid fingerprint detected for RebornCore!
		RenderEngine: 0

**Comment by BraveCaperCat** [comment]
Wait at the top......

Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

......RAM
