### ISSUE TITLE
not showing recipes for items [Bug]: 

### ISSUE THREAD

**Issue by ydocerytnicm** [mezz/JustEnoughItems#2861]
### Steps to Reproduce the Bug

log into server, press E to pull up inventory and try to click on an item in jei interface and nothing appears. 

### Expected Behavior

following these steps should show the recipe for the item I am clicking on. 

### Actual Behavior

nothing happens

### Mod Pack URL (Optional)

https://www.feed-the-beast.com/modpack/95_ftb_presents_direwolf20_1_18

### Mod Pack Version (Optional)

1.5.1

### latest.log

https://gist.github.com/ydocerytnicm/69a8f792cddadc644603f146906778d6

**Comment by Xplodin** [comment]
Im also encountering this
![image](https://user-images.githubusercontent.com/13007677/174756671-cdaba741-d2aa-42a1-9acd-b57b0b1220c5.png)

With JEI addons it only shows the addons recipes

**Comment by mezz** [comment]
Thanks for the report!
I see this issue in the logs:
```
[19Jun2022 14:04:00.734] [Render thread/ERROR] [mezz.jei.forge.startup.StartEventObserver/]: A Screen is opening but JEI hasn't started yet.
Normally, JEI is started after ClientPlayerNetworkEvent.LoggedInEvent, TagsUpdatedEvent, and RecipesUpdatedEvent.
Something has caused one or more of these events to fail, so JEI is starting very late.
```

earlier in the log, I find the cause:
```
[19Jun2022 14:03:38.698] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: L??d%tconstruct:specialized_station_repair)tconstruct:armor/re
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:35) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_130281_(FriendlyByteBuf.java:518) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_133647_(ClientboundUpdateRecipesPacket.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_178371_(FriendlyByteBuf.java:119) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_178366_(FriendlyByteBuf.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.<init>(ClientboundUpdateRecipesPacket.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraft.network.ConnectionProtocol$PacketSet.m_178327_(ConnectionProtocol.java:419) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraft.network.ConnectionProtocol.m_178321_(ConnectionProtocol.java:471) ~[client-1.18.2-20220404.173914-srg.jar%23312!/:?]
	at net.minecraftforge.network.filters.VanillaPacketSplitter.onClientPacket(VanillaPacketSplitter.java:146) ~[forge-1.18.2-40.1.47-universal.jar%23317!/:?]
```

I'm not sure which mod is breaking this `ClientboundUpdateRecipesPacket`, but definitely something is corrupting the packet. Please try removing mods to find what is causing it.
