### ISSUE TITLE
[Crash]: JEI 11.0.0.206

### ISSUE THREAD

**Issue by Dreandor** [mezz/JustEnoughItems#2862]
### Steps to Reproduce the Crash

Install Fabric for 1.19 and start

### Extra Notes (Optional)

Error from the fabric Loader 0.14.8:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'Just Enough Items' (jei) 11.0.0.206 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Crash Report

https://gist.github.com/Dreandor/07f1c2014b0606732533878506c95af3

**Comment by mezz** [comment]
Thanks for the report!
Have you installed Fabric API? Maybe you have Fabric Loader but don't have Fabric API.
