### ISSUE TITLE
[Bug]: JEI Causing server issues in the newest update 

### ISSUE THREAD

**Issue by Zelioth** [mezz/JustEnoughItems#3018]
### Steps to Reproduce the Bug

Have two servers, both servers are updated with client. when joining the server the client crashes and gives long Crash Report

### Expected Behavior

To work correctly 

### Actual Behavior

Crashes on E

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/friends-united

### Mod Pack Version (Optional)

2.2.1

### latest.log

https://gist.github.com/Zelioth/d71c4bb9dfea439657312b703323ce5a

**Comment by mezz** [comment]
Thanks for the report!
It looks like you included the crash report, but could you also paste the latest.log as a gist here as well?

**Comment by Zelioth** [comment]
https://gist.github.com/Zelioth/83417d5b82f0f002a19b15b0cae61e80

I believe this is the one that generated with the crash report. if not it was one with the exact same crash

**Comment by Zelioth** [comment]
So strange occurrence but if you open your client/game join our server/a server it works fine. If you disconnect and reconnect without restarting the client you get instant kicked from the server with a crash report stating that JEI is at fault. 

Crash report and log as follows
[crash-2022-10-16_09.33.35-client.txt](https://github.com/mezz/JustEnoughItems/files/9794886/crash-2022-10-16_09.33.35-client.txt)


[latest.log](https://github.com/mezz/JustEnoughItems/files/9794888/latest.log)
[debug.log](https://github.com/mezz/JustEnoughItems/files/9794891/debug.log)

**Comment by mezz** [comment]
Thank you for the log, I found a couple things I will need to look into:
```
[16Oct2022 09:30:45.494] [Render thread/INFO] [mezz.jei.common.load.PluginCaller/]: Registering recipes: jei:minecraft ...
[16Oct2022 09:30:47.567] [Render thread/ERROR] [mezz.jei.common.load.PluginCaller/]: Caught an error from mod plugin: class mezz.jei.common.plugins.vanilla.VanillaPlugin jei:minecraft
	at mezz.jei.common.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:111) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.plugins.vanilla.VanillaRecipeFactory.createBrewingRecipe(VanillaRecipeFactory.java:56) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.platform.BrewingRecipeMaker.addModdedBrewingRecipes(BrewingRecipeMaker.java:63) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.platform.BrewingRecipeMaker.getBrewingRecipes(BrewingRecipeMaker.java:41) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.platform.RecipeHelper.getBrewingRecipes(RecipeHelper.java:55) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.plugins.vanilla.VanillaPlugin.registerRecipes(VanillaPlugin.java:254) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.load.PluginLoader.lambda$createRecipeManager$9(PluginLoader.java:187) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.load.PluginLoader.createRecipeManager(PluginLoader.java:187) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:87) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
```
and
```
[16Oct2022 09:33:08.056] [Render thread/INFO] [mezz.jei.common.util.LoggedTimer/]: Starting JEI...
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.common.util.ErrorUtil.checkNotNull(ErrorUtil.java:123)
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:66)
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90)
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137)
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100)
	at mezz.jei.common.util.ErrorUtil.checkNotNull(ErrorUtil.java:123) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:66) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
[16Oct2022 09:33:13.049] [Render thread/ERROR] [mezz.jei.forge.startup.StartEventObserver/]: A Screen is opening but JEI hasn't started yet.
Normally, JEI is started after ClientPlayerNetworkEvent.LoggedInEvent, TagsUpdatedEvent, and RecipesUpdatedEvent.
Something has caused one or more of these events to fail, so JEI is starting very late.
[16Oct2022 09:33:13.049] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from ENABLED to DISABLED
[16Oct2022 09:33:13.049] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from DISABLED to ENABLED
[16Oct2022 09:33:13.049] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from ENABLED to JEI_STARTED
[16Oct2022 09:33:13.049] [Render thread/INFO] [mezz.jei.common.util.LoggedTimer/]: Starting JEI...
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.common.util.ErrorUtil.checkNotNull(ErrorUtil.java:123)
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:66)
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90)
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137)
	at TRANSFORMER/jei@11.3.0.271/mezz.jei.forge.startup.StartEventObserver.lambda$register$3(StartEventObserver.java:78)
	at mezz.jei.common.util.ErrorUtil.checkNotNull(ErrorUtil.java:123) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:66) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.StartEventObserver.lambda$register$3(StartEventObserver.java:78) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
[16Oct2022 09:33:13.134] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[16Oct2022 09:33:13.134] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from ENABLED to DISABLED
	at mezz.jei.common.util.ErrorUtil.checkNotNull(ErrorUtil.java:123) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:66) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.forge.startup.StartEventObserver.lambda$register$3(StartEventObserver.java:78) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271]
	at mezz.jei.common.util.ErrorUtil.checkNotNull(ErrorUtil.java:123) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:66) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.lambda$register$3(StartEventObserver.java:78) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.common.util.ErrorUtil.checkNotNull(ErrorUtil.java:123) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:66) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.lambda$register$3(StartEventObserver.java:78) ~[jei-1.19.2-forge-11.3.0.271.jar%23356!/:11.3.0.271] {re:classloading}
		jeimultiblocks-1.19.2-0.0.3.jar                   |Just Enough Immersive Multiblo|jeimultiblocks                |0.0.3               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.3.0.271.jar                   |Just Enough Items             |jei                           |11.3.0.271          |DONE      |Manifest: NOSIGNATURE
```

**Comment by mezz** [comment]
The latest version of JEI is `11.4.0.274`, and you are running an older one `11.3.0.271`.
Can you try updating JEI and report back with the logs you get?

**Comment by Zelioth** [comment]
I will test tonight or tomorrow and let you know. My apologizes I have been away

**Comment by Zelioth** [comment]
Still causing crashing :02:05.237] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: vanilla plugin must not be null.
	Index: 19
	Listeners:
		0: HIGHEST
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@57abee4d
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@53d60ffa
		4: ASM: net.roguelogix.phosphophyllite.Phosphophyllite@3ea0085d onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		5: ASM: class org.zeith.hammerlib.event.listeners.TagsUpdateListener receiveClientsideTags(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@3b83a8d1
		7: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onTagUpdate(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		8: ASM: class com.ldtteam.blockui.mod.ClientEventSubscriber onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@2e297673
		10: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@26f83c7d
		11: ASM: net.minecraftforge.common.ForgeInternalHandler@5fb99001 tagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@45325e87
		13: ASM: ic2.core.platform.events.IC2EventHandler@554b3876 onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		14: ASM: class net.bdew.lib.recipes.RecipeReloadListener tagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		15: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@63d1a3d0
		16: ASM: me.desht.pneumaticcraft.common.event.MiscEventHandler@5eb375c8 onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		17: ASM: class com.stal111.forbidden_arcanus.common.event.DatapackEvents onTagsUpdate(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		18: ASM: class blusunrize.immersiveengineering.api.crafting.cache.CachedRecipeList onTagsUpdated(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		19: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@6aecb37
		20: ASM: ic2.core.wiki.base.managers.RecipeProvider@5c44c0e0 onClientReloaded(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		21: ASM: shetiphian.endertanks.common.misc.EventHandler@78677f2f tagsUpdatedEvent(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		22: ASM: shetiphian.enderchests.common.misc.EventHandler@50324309 tagsUpdatedEvent(Lnet/minecraftforge/event/TagsUpdatedEvent;)V
		23: LOWEST
		24: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@61d2044b
		25: net.minecraftforge.eventbus.EventBus$$Lambda$4726/0x0000000800e15958@3643a890
java.lang.NullPointerException: vanilla plugin must not be null.
	at TRANSFORMER/jei@11.4.0.274/mezz.jei.common.util.ErrorUtil.checkNotNull(ErrorUtil.java:123)
	at TRANSFORMER/jei@11.4.0.274/mezz.jei.common.startup.JeiStarter.start(JeiStarter.java:66)
	at TRANSFORMER/jei@11.4.0.274/mezz.jei.forge.startup.ClientLifecycleHandler.startJei(ClientLifecycleHandler.java:90)
	at TRANSFORMER/jei@11.4.0.274/mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137)
	at TRANSFORMER/jei@11.4.0.274/mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1321)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.1.47/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by Zelioth** [comment]
Here is the LATEST Log with the NEWEST Verions with all the errors included. 
[latest.log](https://github.com/mezz/JustEnoughItems/files/9883831/latest.log)

**Comment by Zelioth** [comment]
JEI Version 11.4.0.274 just instantly crashes the client when entering GUI of inventory, or really any GUI. 
[latest.log](https://github.com/mezz/JustEnoughItems/files/9891881/latest.log)

**Comment by mezz** [comment]
Thank you for investigating, Zelioth.
Unfortunately I think this is caused by a complex mod interaction that doesn't show itself in the logs.
Can you try removing mods to narrow down which one might be causing an issue with JEI?

**Comment by Zelioth** [comment]
I'll be honest. I don't at the moment and may not till the end of the month. The issue isn't present in JEI version 11.3.0.262 but starts in version 11.3.0.268. and this stands with all the mods I have staying the same or being updated. Did you add support or change anything in that version because it would seem if it was the other mods fault causing the error it would be causing the error in ALL versions not just the latest few.

**Comment by mezz** [comment]
That's a pretty small range of versions, so it might be enough of a clue for me to find something. 
I wont get to this right away either but I'll report here if I find anything.

**Comment by Zelioth** [comment]
Howdy, So I installed the LATEST released version of JEI. and though I haven't been able to fully test it I did want to give you all of these current errors considering some are Vanilla based from the read out.... well from what I understand haha. this was during world gen after all mods were loaded and EVERYTHING in the pack is updated. as for the error above I have not tested to see if it is still present. 
[latest.log](https://github.com/mezz/JustEnoughItems/files/9916028/latest.log)

**Comment by Zelioth** [comment]
So updated to the latest version you have released and so far not having any issues or crashes. could be wrong but seems better. also the vanilla error

Caught an error from mod plugin: class mezz.jei.common.plugins.vanilla.VanillaPlugin jei:minecraft
java.lang.IllegalArgumentException: potionInputs must not be empty.

is still present

**Comment by mezz** [comment]
Thank you for confirming.
I have submitted a fix for the "potionInputs must not be empty" error.
