### ISSUE TITLE
[Crash]: JEI crashing when searching items

### ISSUE THREAD

**Issue by HyperSpeedSoul** [mezz/JustEnoughItems#3036]
### Steps to Reproduce the Crash

Opening the inventory and searching bac.. cause it to crash before I even get to finish the word "Backpack" even happens when scrolling to certain pages

### Mod Pack Version (Optional)

1.19.2

### Extra Notes (Optional)
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2022-11-03 02:09:41
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.1.3-universal.jar%23271!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.1.3-universal.jar%23271!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:604) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.compat1192minus.GameRendererMixin,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.3.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.2-43.1.3-universal.jar%23271!/:?] {re:classloading}
-- MOD awesomedungeonocean --
Details:
	Mod File: /C:/Users/HyperSpeed/curseforge/minecraft/Instances/MineColonies Official/mods/awesomedungeonocean-forge-1.19.2-3.0.0.jar
	Failure message: Mod awesomedungeonocean requires libraryferret 3.0.0 or above
		Currently, libraryferret is not installed
	Mod Version: 3.0.0
	Mod Issue URL: NOT PROVIDED
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.logging.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:58) ~[forge-1.19.2-43.1.3-universal.jar%23271!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:56) ~[forge-1.19.2-43.1.3-universal.jar%23271!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.1.3-universal.jar%23271!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:604) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.compat1192minus.GameRendererMixin,pl:mixin:APP:apoli.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin,pl:mixin:APP:apoli.mixins.json:MinecraftClientMixin,pl:mixin:APP:neat.mixins.json:MinecraftMixin,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:APP:wwoo_forge.mixins.json:QuitMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23266!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.3.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


-- MOD minecolonies --
Details:
	Mod File: /C:/Users/HyperSpeed/curseforge/minecraft/Instances/MineColonies Official/mods/minecolonies-1.19.2-1.0.1093-ALPHA.jar
	Failure message: Mod minecolonies requires structurize 1.19.2-1.0.452-ALPHA or above
		Currently, structurize is not installed
	Mod Version: 1.19.2-1.0.1093-ALPHA
	Mod Issue URL: https://github.com/ldtteam/minecolonies/issues/new/choose
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD minecolonies --
Details:
	Mod File: /C:/Users/HyperSpeed/curseforge/minecraft/Instances/MineColonies Official/mods/minecolonies-1.19.2-1.0.1093-ALPHA.jar
	Failure message: Mod minecolonies requires blockui 1.19-0.0.64-ALPHA or above
		Currently, blockui is not installed
	Mod Version: 1.19.2-1.0.1093-ALPHA
	Mod Issue URL: https://github.com/ldtteam/minecolonies/issues/new/choose
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD delightful --
Details:
	Mod File: /C:/Users/HyperSpeed/curseforge/minecraft/Instances/MineColonies Official/mods/Delightful-1.19-3.1.2.jar
	Failure message: Mod delightful requires farmersdelight 1.19-1.2 or above
		Currently, farmersdelight is not installed
	Mod Version: 3.1.2
	Mod Issue URL: https://github.com/brdle/Delightful/issues
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD cookingforblockheads --
Details:
	Mod File: /C:/Users/HyperSpeed/curseforge/minecraft/Instances/MineColonies Official/mods/cookingforblockheads-forge-1.19.2-13.3.0.jar
	Failure message: Mod cookingforblockheads requires balm 4.3.0 or above
		Currently, balm is not installed
	Mod Version: 13.3.0
	Mod Issue URL: https://github.com/ModdingForBlockheads/CookingForBlockheads/issues
	Exception message: MISSING EXCEPTION MESSAGE

-- MOD waystones --
Details:
	Mod File: /C:/Users/HyperSpeed/curseforge/minecraft/Instances/MineColonies Official/mods/waystones-forge-1.19-11.1.0.jar
	Failure message: Mod waystones requires balm 4.1.0 or above
		Currently, balm is not installed
	Mod Version: 11.1.0
	Mod Issue URL: https://github.com/ModdingForBlockheads/Waystones/issues
	Exception message: MISSING EXCEPTION MESSAGE

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 406679552 bytes (387 MiB) / 947912704 bytes (904 MiB) up to 8791261184 bytes (8384 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 6800 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73bf
	Graphics card #0 versionInfo: DriverVersion=31.0.12019.16007
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 60242.51
	Virtual memory used (MB): 53646.70
	Swap memory total (MB): 27548.41
	Swap memory used (MB): 1660.12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8384m -Xms256m
	OptiFine Version: OptiFine_1.19.2_HD_U_H9
	OptiFine Build: 20220820-230904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 Core Profile Context 22.10.1.221003
	OpenGlRenderer: AMD Radeon RX 6800 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.1.3.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.3.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.1.3.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.1.3.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.3.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.19.2-43.1.3-universal.jar                 |Forge                         |forge                         |43.1.3              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
```
### Crash Report

<script src="https://gist.github.com/HyperSpeedSoul/0b03a488467b3c85c48eeb691c1c8563.js"></script>

**Comment by AndreAugustoDev** [comment]
I am also having the same problem
And it didn't just happen with the mod in the crash report, also with the productive bees and resource chickens, maybe it has some connection to be resource mods?
https://mclo.gs/wFJmKdr

**Comment by ddevoykirito** [comment]
I am having the same issues, and mine was while trying to see if the modpack it's in has any alternative buckets. didn't make it past bu before crash, and crashes when you try to scroll.

https://bytebin.lucko.me/CUtpO3VN6b

**Comment by mezz** [comment]
Thanks for the report!
The crash log you have included is a mod loading error, which happens before the game will even show JEI. Please include the right crash log so that I can look into your issue.


@AndreAugustoAAQ your rendering crash is unrelated, it is from Chickens:
```
-- Item being rendered --
--
18 | Details:
19 | Item Type: chicken_item
20 | Registry Name: chickens:chicken_item
21 | Item Damage: 0
22 | Item NBT: {ChickenType:{id:"chickens:lime_chicken"}}
23 | Item Foil: false
```
Please report it to them here instead: https://github.com/CreeperHost/Chickens/issues


@ddevoykirito your rendering crash is unrelated, it is from Mekanism:
```
-- Ingredient being rendered --
Details:
	Mod Name: Mekanism
	Registry Name: mekanism:hydrogen_bucket
	Display Name: Liquid Hydrogen Bucket
	String Name: 1 hydrogen_bucket
```
Please report it to them here instead: https://github.com/mekanism/Mekanism/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by HyperSpeedSoul** [comment]
Ope sorry for including the wrong report, I just pulled that from the crash report files within the modpack! My apologizes while I look for the right report.

**Comment by AndreAugustoDev** [comment]
@mezz I don't think it's directly related to Chickens, because as I mentioned, I've had this same error with other mods, Productive Bees and Resource Chickens besides the one mentioned, and other people are having the same error in different mods
I believe that the central point where we should investigate is why this crash occurs precisely when we use JEI

EDIT:
Crash report Productive Bees
https://mclo.gs/F1qByya

**Comment by mezz** [comment]
@AndreAugustoAAQ unfortunately this is just showing that multiple mods in your pack have rendering errors that result in crashes.
JEI renders a lot of items, so it is usually the first place that people see render errors from other mods.

I have fielded reports of this type of crash for years, and forwarded them to the right places to get them fixed. What I have found is that most of the time if an item is crashing in JEI it will also crash in the creative menu or in your inventory too. Sometimes a mod will have a very broken item inserted into JEI directly, but that is less common. 

JEI uses the same rendering logic as the rest of the game so it generally doesn't introduce new rendering bugs itself. It used to have more custom rendering to make it more efficient, but it wasn't worth the instability and crashes that people would sometimes get.

**Comment by AndreAugustoDev** [comment]
Well, I believe then that something changed in the JEI in the last month causing the incompatibility, because of the mods I mentioned, only the JEI was updated in the last month
I will check what could be causing these problems by taking a look at the JEI code

UPDATE:
I made an instance with the reported mods, and concluded that the cause of the problems is another mod from the pack
With just them installed everything works perfectly
The log for reference only of successful execution https://mclo.gs/vaFTtAm
I'll start an analysis on the pack to see which mod causes the error and I'll be back soon.

**Comment by AndreAugustoDev** [comment]
CONCLUSION:
In my case the reason for the crash was the Vampirism mod in the latest version at the moment, reverting to the previous version the crash does not occur
`Vampirism 1.19.2 1.9.0-beta.1` => search for something related to the crash mod, in this case Chickens => crash
`Vampirism 1.19.2 1.9.0-alpha+20221022-1224` => works correctly
I will report the issue to Vampirism

**Comment by mezz** [comment]
Thank you for figuring out which mod was causing an issue, it looks like they were able to fix the problem very quickly!
