### ISSUE TITLE
[Crash]: Failed to start the game(1.18.2)

### ISSUE THREAD

**Issue by hxwd94666** [mezz/JustEnoughItems#3116]
### Steps to Reproduce the Crash

Download the plugins required by optifine and fabric through the pcl launcher and start the game.Then the game crash.

### Mod Pack URL (Optional)

No

### Mod Pack Version (Optional)

No

### Extra Notes (Optional)

<img width="593" alt="Screenshot 2023-01-28 010038" src="https://user-images.githubusercontent.com/111326771/215148362-eb5b2b44-e085-47ce-8f60-b5a7c4f75c64.png">
The following is the translation:
Mod injection with name or ID jei failed, causing an error in the game.
This usually means that the Mod has a Bug or is incompatible with the current environment.
You can check the error report to see exactly how the error occurred.
Instead of sending a screenshot of this window, send someone a bug report file to ask for help.
And error reporting:
[00:50:13] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.13
[00:50:13] [main/INFO]: Loading 52 mods:
	- fabric-api 0.67.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric-api
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric-api
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric-api
	- fabric-block-api-v1 1.0.0+ee3621fc60 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric-api
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric-api
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric-api
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric-api
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric-api
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric-api
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric-api
	- fabric-data-generation-api-v1 3.0.2+9fcb91d260 via fabric-api
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric-api
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric-api
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric-api
	- fabric-events-lifecycle-v0 0.2.20+d7c144a860 via fabric-api
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric-api
	- fabric-item-api-v1 1.6.0+d8cf4e5a60 via fabric-api
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric-api
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric-api
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric-api
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric-api
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric-api
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric-api
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric-api
	- fabric-models-v0 0.3.6+d7c144a860 via fabric-api
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric-api
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric-api
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric-api
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric-api
	- fabric-registry-sync-v0 0.9.11+bb2e047760 via fabric-api
	- fabric-renderer-api-v1 0.4.15+ee3621fc60 via fabric-api
	- fabric-renderer-indigo 0.5.5+41a02c8a60 via fabric-api
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.8+ee3621fc60 via fabric-api
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric-api
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric-api
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric-api
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric-api
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric-api
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric-api
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric-api
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric-api
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric-api
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric-api
	- fabricloader 0.14.13
	- java 17
	- jei 10.2.1.1001
	- minecraft 1.18.2
	- mm 2.3 via optifabric
	- optifabric 1.13.16
[00:50:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/54458/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[00:50:13] [main/INFO]: Compatibility level set to JAVA_16
[00:50:13] [main/INFO]: Compatibility level set to JAVA_17
[00:50:15] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.13.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[1.18.2-Fabric%200.14.13-OptiFine_H7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_309 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[1.18.2-Fabric%200.14.13-OptiFine_H7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[1.18.2-Fabric%200.14.13-OptiFine_H7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method beforeCharTypedEvent(Lnet/minecraft/class_364;IILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in jei.mixins.json:KeyboardHandlerMixin from mod jei failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap jei-1.18.2-fabric-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.13.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
	at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25) ~[Optifine-mapped.jar:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:503) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[1.18.2-Fabric%200.14.13-OptiFine_H7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.13.jar:?]
	... 8 more
[latest.log](https://github.com/mezz/JustEnoughItems/files/10521253/latest.log)

### Crash Report

https://github.com/mezz/JustEnoughItems/files/10521253/latest.log

**Comment by mezz** [comment]
Thanks for the report!
Please try removing `optifabric` and see if the issue is resolved.
