### ISSUE TITLE
Crashing after launch

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#315]
I am making a light weight mod pack for minecraft 1.9.4 and would like just enough items and/or just enough resources but when i JEI it crashes after launch.  It doesnt crash when I take it out of the mod pack.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  IC2core (industrialcraft-2-2.5.3-ex19.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/13/16 5:17 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
    at net.minecraft.util.ResourceLocation.func_177516_a(SourceFile:29)
    at net.minecraft.client.renderer.block.model.ModelResourceLocation.func_177517_b(ModelResourceLocation.java:47)
    at net.minecraft.client.renderer.block.model.ModelResourceLocation.<init>(ModelResourceLocation.java:28)
    at net.minecraft.client.renderer.block.model.ModelResourceLocation.<init>(ModelResourceLocation.java:23)
    at ic2.core.model.ModelUtil.getModelLocation(ModelUtil.java:13)
    at ic2.core.block.BlockTileEntity$1.func_178130_a(BlockTileEntity.java:92)
    at net.minecraft.client.renderer.block.statemap.BlockStateMapper.func_188181_b(SourceFile:60)
    at net.minecraft.client.renderer.block.statemap.BlockStateMapper.func_178446_a(SourceFile:31)
    at net.minecraft.client.renderer.BlockModelShapes.func_178124_c(BlockModelShapes.java:145)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:31)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:753)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:332)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.util.ResourceLocation.func_177516_a(SourceFile:29)
    at net.minecraft.client.renderer.block.model.ModelResourceLocation.func_177517_b(ModelResourceLocation.java:47)
    at net.minecraft.client.renderer.block.model.ModelResourceLocation.<init>(ModelResourceLocation.java:28)
    at net.minecraft.client.renderer.block.model.ModelResourceLocation.<init>(ModelResourceLocation.java:23)
    at ic2.core.model.ModelUtil.getModelLocation(ModelUtil.java:13)
    at ic2.core.block.BlockTileEntity$1.func_178130_a(BlockTileEntity.java:92)
    at net.minecraft.client.renderer.block.statemap.BlockStateMapper.func_188181_b(SourceFile:60)
    at net.minecraft.client.renderer.block.statemap.BlockStateMapper.func_178446_a(SourceFile:31)
    at net.minecraft.client.renderer.BlockModelShapes.func_178124_c(BlockModelShapes.java:145)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:31)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:753)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:332)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Mac OS X (x86_64) version 10.11.1
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1276928 bytes (1 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1962 19 mods loaded, 19 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1962.jar) 
    UCHIJA  Forge{12.17.0.1962} [Minecraft Forge](forge-1.9.4-12.17.0.1962.jar) 
    UCHIJA  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJA  BiomesOPlenty{4.1.0.2024} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2024-universal.jar) 
    UCHIJA  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.9.4-alpha-1.0.0a.jar) 
    UCHIJA  JEI{3.4.4.208} [Just Enough Items](jei_1.9.4-3.4.4.208.jar) 
    UCHIJA  BloodMagic{1.9.4-2.0.1-42} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.1-42.jar) 
    UCHIJA  Chameleon{1.9-2.1.4} [Chameleon](Chameleon-1.9-2.1.4.jar) 
    UCHIJA  FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-MC1.9.4-1.2.1.jar) 
    UCHIJA  IC2{2.5.3-ex19} [IndustrialCraft 2](industrialcraft-2-2.5.3-ex19.jar) 
    UCHIJA  forestry{5.0.9.143} [Forestry](forestry_1.9.4-5.0.9.143.jar) 
    UCHIJA  gravestone{1.3.0} [Gravestone](Gravestone Mod 1.3.0.jar) 
    UCHIJA  IronChest{6.0.141.783} [Iron Chest](ironchest-1.9.4-6.0.141.783.jar) 
    UCHIJA  mantle{1.9.4-0.10.1.jenkins142} [Mantle](Mantle-1.9.4-0.10.1.jenkins142.jar) 
    UCHIJA  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4a.jar) 
    UCHIJA  progressiveautomation{1.6.45} [Progressive Automation](ProgressiveAutomation-1.9.4-1.6.45.jar) 
    UCHIJA  StorageDrawers{1.9-3.1.7} [Storage Drawers](StorageDrawers-1.9-3.1.7.jar) 
    UCHIJA  tconstruct{1.9.4-2.3.1.jenkins229} [Tinkers' Construct](TConstruct-1.9.4-2.3.1.jenkins229.jar) 
    Loaded coremods (and transformers): 
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
IC2core (industrialcraft-2-2.5.3-ex19.jar)

```
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)

Launched Version: 1.9.4-forge1.9.4-12.17.0.1962
LWJGL: 2.9.2
OpenGL: NVIDIA GeForce GT 650M OpenGL Engine GL version 2.1 NVIDIA-10.6.47 310.42.05f01, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: net.minecraft.client.Minecraft$15@298e56f6
```

**Comment by TehNut** [comment]
`java.lang.OutOfMemoryError: Java heap space`

You're running out of memory.

**Comment by mezz** [comment]
Thanks for the report!
As far as I know, JEI doesn't use a crazy amount of memory.
Your java arguments show a maximum of 1GB allocated. 2-4GB is recommended for modded Minecraft, I would consider 2GB lightweight.
