### ISSUE TITLE
[Bug]: ItemStack value must not be empty

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#3339]
### Steps to Reproduce the Bug

Play Better MC 1.16.5 Modpack (Latest (v60.5) version)

### Expected Behavior

No problems

### Actual Behavior

Getting ItemStack errors

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc1

### latest.log

https://github.com/mezz/JustEnoughItems/files/13048502/latest.log

**Comment by mezz** [comment]
Thanks for the report!
```
[20Oct2023 01:28:17.890] [ModernFix JEI Reload Thread 1/ERROR] [mezz.jei.recipes.RecipeManagerInternal/]: Found a broken recipe: The Outer End outer_end:sawmill/vertical_azure_planks_from_azure_stems_sawing class com.minecraftabnormals.environmental.common.item.crafting.SawingRecipe
Outputs:
net.minecraft.item.ItemStack: [[4 air minecraft:air]]
Inputs:
net.minecraft.item.ItemStack: [[1 azure_stem outer_end:azure_stem, 1 azure_stripped_stem outer_end:azure_stripped_stem, 1 azure_pith outer_end:azure_pith, 1 azure_stripped_pith outer_end:azure_stripped_pith]]

java.lang.IllegalArgumentException: ItemStack value must not be empty. 4 air minecraft:air
	at mezz.jei.util.ErrorUtil.checkNotEmpty(ErrorUtil.java:206) ~[jei:7.8.0.1009]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:88) ~[jei:7.8.0.1009]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackHelper.getUniqueId(ItemStackHelper.java:28) ~[jei:7.8.0.1009]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:94) ~[jei:7.8.0.1009]
	at mezz.jei.recipes.RecipeMap.addRecipe(RecipeMap.java:75) ~[jei:7.8.0.1009]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipe(RecipeManagerInternal.java:125) ~[jei:7.8.0.1009]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipeTyped(RecipeManagerInternal.java:101) ~[jei:7.8.0.1009]
	at mezz.jei.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:94) ~[jei:7.8.0.1009]
	at mezz.jei.recipes.RecipeManagerInternal.<init>(RecipeManagerInternal.java:86) ~[jei:7.8.0.1009]
	at mezz.jei.load.PluginLoader.getRecipeManager(PluginLoader.java:145) ~[jei:7.8.0.1009]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:74) ~[jei:7.8.0.1009]
	at mezz.jei.startup.ClientLifecycleHandler.md8ceafd$lambda$startJEIAsync$7$0(ClientLifecycleHandler.java:587) ~[jei:7.8.0.1009]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_381]
```

This is JEI showing an error in a recipe from a mod. Please report it to them.
The mod erroring here is [minecraftabnormals' environmental](https://github.com/team-abnormals/environmental/issues)
