### ISSUE TITLE
Help resolving Tooltip error. ive been trying to resolve it for hours but cant am at a loss

### ISSUE THREAD

**Issue by Connorray1234** [mezz/JustEnoughItems#3497]
### Other

[latest.log](https://github.com/mezz/JustEnoughItems/files/15137196/latest.log)
![Screenshot 2024-04-23 211703](https://github.com/mezz/JustEnoughItems/assets/85777151/d8cf9dca-ae83-460b-b882-b73106f69f47)

**Comment by mezz** [comment]
Thanks for the report!
Here's the relevant part of the logs:
```
[14:25:03] [Render thread/ERROR]: Caught an error rendering an Ingredient's tooltip:

-- Ingredient --
Details:
	Name: Passenger Information Display System
	Mod's Name: Minecraft Transit Railway
	Registry Name: mtr:pids_1
	Class Name: class net.minecraft.world.item.ItemStack
	toString Name: 1 pids_1
	Unique Id for JEI (for JEI Blacklist): mtr:pids_1
	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
	Error Info gathered from JEI: 1 pids_1 mtr:pids_1

-- Stack Trace --

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because the return value of "net.minecraft.world.level.block.entity.BlockEntity.m_58900_()" is null
	at TRANSFORMER/botarium@2.3.3/earth.terrarium.botarium.forge.BotariumForge.attachBlockCapabilities(BotariumForge.java:55)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.30/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:623)
	at TRANSFORMER/forge@47.2.30/net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:617)
	at TRANSFORMER/forge@47.2.30/net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:72)
	at TRANSFORMER/forge@47.2.30/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:67)
	at TRANSFORMER/forge@47.2.30/net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:51)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.block.entity.BlockEntity.<init>(BlockEntity.java:33)
	at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.mappings.BlockEntityMapper.<init>(BlockEntityMapper.java:12)
	at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.mappings.BlockEntityClientSerializableMapper.<init>(BlockEntityClientSerializableMapper.java:15)
	at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.data.IPIDS$TileEntityPIDS.<init>(IPIDS.java:31)
	at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.block.BlockPIDSBaseHorizontal$TileEntityBlockPIDSBaseHorizontal.<init>(BlockPIDSBaseHorizontal.java:110)
	at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.block.BlockPIDS1$TileEntityBlockPIDS1.<init>(BlockPIDS1.java:32)
	at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.block.BlockPIDS1.createBlockEntity(BlockPIDS1.java:23)
	at TRANSFORMER/mtr@1.20.1-3.2.2-hotfix-2/mtr.block.BlockPIDSBaseHorizontal.m_5871_(BlockPIDSBaseHorizontal.java:96)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BlockItem.m_7373_(BlockItem.java:200)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:631)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.library.render.ItemStackRenderer.getTooltip(ItemStackRenderer.java:36)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.library.render.ItemStackRenderer.getTooltip(ItemStackRenderer.java:18)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.common.util.SafeIngredientUtil.getTooltip(SafeIngredientUtil.java:56)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.gui.ingredients.IngredientInformationUtil.getTooltipStrings(IngredientInformationUtil.java:31)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.gui.ingredients.ListElementInfo.getTooltipStrings(ListElementInfo.java:110)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.gui.search.ElementPrefixParser.lambda$new$2(ElementPrefixParser.java:41)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.core.search.PrefixInfo.getStrings(PrefixInfo.java:35)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.core.search.PrefixedSearchable.getStrings(PrefixedSearchable.java:20)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.gui.search.ElementSearch.add(ElementSearch.java:62)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.gui.ingredients.IngredientFilter.addIngredient(IngredientFilter.java:102)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.gui.ingredients.IngredientFilter.<init>(IngredientFilter.java:89)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.gui.startup.JeiGuiStarter.start(JeiGuiStarter.java:108)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.forge.plugins.forge.ForgeGuiPlugin.registerRuntime(ForgeGuiPlugin.java:34)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.library.startup.JeiStarter.lambda$start$2(JeiStarter.java:156)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:27)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:156)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137)
	at TRANSFORMER/jei@15.3.0.4/mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.30/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.30/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.2.30/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
```

It looks like this was reported to Minecraft Transit Railway mod here and fixed in version 4.0.0: https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues/794
