### ISSUE TITLE
[Crash]: 1.12.2 Forge Sklauncher 

### ISSUE THREAD

**Issue by GohanModder132** [mezz/JustEnoughItems#3500]
### Steps to Reproduce the Crash

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_23.9.7_Forge_1.12.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.38.4_Forge_1.12.jar)
  SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.8.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/30/24 10:02 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: mezz.jei.startup.ProxyCommonClient
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:102)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:611)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mezz.jei.startup.ProxyCommonClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:85)
	... 37 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.findAndMergeSuperMaps(FMLDeobfuscatingRemapper.java:425)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getMethodMap(FMLDeobfuscatingRemapper.java:402)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.mapMethodName(FMLDeobfuscatingRemapper.java:349)
	at org.objectweb.asm.commons.RemappingMethodAdapter.doVisitMethodInsn(RemappingMethodAdapter.java:156)
	at org.objectweb.asm.commons.RemappingMethodAdapter.visitMethodInsn(RemappingMethodAdapter.java:143)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1496)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1032)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:521)
	at net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:76)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 117602024 bytes (112 MB) / 335544320 bytes (320 MB) up to 4211081216 bytes (4016 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx4007m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version                  | Source                                      | Signature                                |
	|:----- |:------------------ |:------------------------ |:------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft          | 1.12.2                   | minecraft.jar                               | None                                     |
	| LC    | mcp                | 9.42                     | minecraft.jar                               | None                                     |
	| LC    | FML                | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge              | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | xaerominimap_core  | 1.12.2-1.0               | minecraft.jar                               | None                                     |
	| LC    | xaeroworldmap_core | 1.12.2-1.0               | minecraft.jar                               | None                                     |
	| LC    | techguns_core      | 1.12.2-1.0               | minecraft.jar                               | None                                     |
	| LC    | securitycraft      | v1.9.8                   | [1.12.2] SecurityCraft v1.9.8.jar           | None                                     |
	| LC    | aether_legacy      | 1.5.3.2                  | aether-1.12.2-v1.5.3.2.jar                  | None                                     |
	| LC    | ageofweapons       | 0.13.5                   | Age of Weapons 1.12.2  (v.0.13.5).jar       | None                                     |
	| LE    | jei                | 4.16.1.1006              | jei_1.12.2-4.16.1.1006.jar                  | None                                     |
	| L     | appleskin          | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                 | None                                     |
	| L     | falling_tree       | 2.4.0                    | FallingTree-1.12.2-2.4.0.jar                | None                                     |
	| L     | mts                | 22.14.2                  | Immersive Vehicles-1.12.2-22.14.2.jar       | None                                     |
	| L     | ivv                | 2.31.0                   | Immersive Vehicles Vanity-1.12.2-2.31.1.jar | None                                     |
	| L     | inventorytweaks    | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                    | None                                     |
	| L     | techguns           | 2.0.2.0                  | techguns-1.12.2-2.0.2.0_pre3.2.jar          | None                                     |
	| L     | uteamcore          | 2.2.5.226                | u_team_core-1.12.2-2.2.5.226.jar            | None                                     |
	| L     | usefulbackpacks    | 1.5.1.31                 | useful_backpacks-1.12.2-1.5.1.31.jar        | None                                     |
	| L     | xaerominimap       | 23.9.7                   | Xaeros_Minimap_23.9.7_Forge_1.12.jar        | None                                     |
	| L     | xaeroworldmap      | 1.38.4                   | XaerosWorldMap_1.38.4_Forge_1.12.jar        | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
XaeroMinimapPlugin (Xaeros_Minimap_23.9.7_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerMPTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.MinecraftServerTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.38.4_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.EntityPlayerMPTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
  xaero.map.core.transformer.MinecraftServerTransformer
  xaero.map.core.transformer.MinecraftTransformer
SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.8.jar)
  
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
  techguns.core.TechgunsASMTransformer

### Crash Report

https://mclo.gs/N8yFneu

**Comment by GohanModder132** [comment]
How can do for fix it?
