### ISSUE TITLE
[Bug]: jei-1.20.1-forge-15.8.0.10 Creative menu search option doesn't work

### ISSUE THREAD

**Issue by Looxond** [mezz/JustEnoughItems#3597]
### Steps to Reproduce the Bug

Install the latest version, switch to creative mod, go to the search function, type anything

### Expected Behavior

For the items to show up.

Here is an example without JEI
![2024-07-14_17 32 44](https://github.com/user-attachments/assets/9e4f4241-e849-4f41-b7f3-2d0acde04869)

### Actual Behavior

Nothing happens the items don't show up upon being requested.

Here is an example with JEI installed
![2024-07-14_17 36 09](https://github.com/user-attachments/assets/3040d14a-ad37-4a58-9f2f-a9e1866dc774)

### latest.log

https://mclo.gs/9c5pB9m

**Comment by Fyoncle** [comment]
Same issue.

**Comment by LwkySad** [comment]
I 3rd this

**Comment by ghost** [comment]
I 4th this.

**Comment by goldrat1** [comment]
I 5th this. This is the error that shows up in latest.log:
`[Render thread/ERROR]: Error searching
java.lang.invoke.WrongMethodTypeException: expected (IngredientFilter,String)Stream but found (IngredientFilter,String)List
	at java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:523) ~[?:?]
	at java.lang.invoke.Invokers.checkExactType(Invokers.java:532) ~[?:?]
	at org.embeddedt.modernfix.searchtree.JEIBackedSearchTree.searchJEI(JEIBackedSearchTree.java:78) ~[modernfix-forge-5.18.6+mc1.20.1.jar%23418!/:5.18.6+mc1.20.1]
	at org.embeddedt.modernfix.searchtree.JEIBackedSearchTree.m_6293_(JEIBackedSearchTree.java:65) ~[modernfix-forge-5.18.6+mc1.20.1.jar%23418!/:5.18.6+mc1.20.1]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_98630_(CreativeModeInventoryScreen.java:410) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_5534_(CreativeModeInventoryScreen.java:347) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$charTyped$6(KeyboardHandler.java:442) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:437) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.KeyboardHandler.m_90889_(KeyboardHandler.java:440) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.KeyboardHandler.m_167827_(KeyboardHandler.java:466) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.KeyboardHandler.m_90934_(KeyboardHandler.java:465) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:46) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23153!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23141!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1170) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23472!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.3.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]`

**Comment by mezz** [comment]
Thanks for the report!
JEI doesn't edit the creative menu at all, please look into the stack trace and see things like `embeddedt.modernfix`.

Please [report this issue to them here instead](https://github.com/embeddedt/ModernFix/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) and link back to this issue.

**Comment by goldrat1** [comment]
I'll report it to them as well. Neither ModernFix nor JEI causes this issue but when they're both present together, the creative menu breaks.
I ought to mention that this only happens with JEI versions above 15.8.0.9.

**Comment by solorune** [comment]
Hi all, also faced this problem, the fault is solely ModernFix. And also found a solution to this problem, on the official ModernFix page there is an explanation of each mod setting.
Function “mixin.perf.blast_search_trees” I quote 

> “All versions. If REI or JEI are installed, construction of the vanilla search trees for creative searching is disabled, and searching is instead done using these mods' search implementations. This saves several seconds during world loading, and probably also saves some RAM as well” 

thus prevents you from using vanilla search. Just turn this option off
![2024-07-17_03 14 15](https://github.com/user-attachments/assets/97e2b5ba-937e-4c52-ac10-4b43bbfc9beb)

**Comment by mezz** [comment]
Looks like it was reported and fixed here :tada:: https://github.com/embeddedt/ModernFix/issues/438
