### ISSUE TITLE
JEI bug - crash to the desktop when selecting a block

### ISSUE THREAD

**Issue by Venomless** [mezz/JustEnoughItems#360]
Hello!

I'm getting a bug, that when i select a block (recipe or cheat, i does the same) i just shuts down to desktop. I'm using latest version for 1.9.4 and without FEI.

Thanks,
Venomless

PS: here is the crash report:
https://gist.github.com/Venomless/d5617b38cb66344d70f899139e233534

**Comment by Venomless** [comment]
i'm using MultiMC - so i don know if that has some sort of effect on it, but this was red:

[12:53:44] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1710) ~[bcd.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1054) ~[bcd.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369) [bcd.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidUtil.getFluidContained(Lnet/minecraft/item/ItemStack;)Lnet/minecraftforge/fluids/FluidStack;
    at mezz.jei.gui.Focus.getFluidFromItemStack(Focus.java:67) ~[Focus.class:?]
    at mezz.jei.gui.Focus.<init>(Focus.java:43) ~[Focus.class:?]
    at mezz.jei.gui.ingredients.GuiItemStackFastList.getFocusUnderMouse(GuiItemStackFastList.java:77) ~[GuiItemStackFastList.class:?]
    at mezz.jei.gui.ItemListOverlay.getFocusUnderMouse(ItemListOverlay.java:394) ~[ItemListOverlay.class:?]
    at mezz.jei.input.InputHandler.getFocusUnderMouseForClick(InputHandler.java:105) ~[InputHandler.class:?]
    at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:83) ~[InputHandler.class:?]
    at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:61) ~[InputHandler.class:?]
    at mezz.jei.GuiEventHandler.onGuiMouseEvent(GuiEventHandler.java:145) ~[GuiEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_52_GuiEventHandler_onGuiMouseEvent_Pre.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:508) ~[bez.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1697) ~[bcd.class:?]

**Comment by mezz** [comment]
Thanks for the report!
This is caused by an outdated Forge version. Please try with the latest Forge for 1.9.4.

**Comment by Venomless** [comment]
Im using multiMC, and i have multiple mods for MC installed, the are working without problem, so i don't think that's the problem, but i'll try updating it :)

**Comment by Venomless** [comment]
so, i have checked the version, and you were right, it was really the problem with the version, i was just confused with description, because it looked like if it was for 1.10.
thanks again!
Venomless

**Comment by mezz** [comment]
Cool, glad that was it.
