### ISSUE TITLE
[Crash]: fabric wont co-op with JEI

### ISSUE THREAD

**Issue by craftythe443** [mezz/JustEnoughItems#3748]
### Steps to Reproduce the Crash

in 1.20.1 on modrith (and maybe forge) everytime you get JEI on fabic it crashes and wont co-op and it says i have to go in a version that is WAAAAY back and it says this "Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.15.11 with version 0.16.3 or later.
More details:
	 - Mod 'Just Enough Items' (jei) 15.17.0.76 requires version 0.16.3 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.11!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)"
![image_2024-09-07_204710453](https://github.com/user-attachments/assets/6234a2e5-9c94-422b-9a48-e56db7f94809)

### Mod Pack Version (Optional)

1.20.1

### Crash Report

im sorry this is my first time useing git hub and idk what that is, hope this dosent effect the report :(

**Comment by mezz** [comment]
Thanks for the report!
Sorry I do not understand completely, is there a reason you cannot install Fabric 0.16.3 or later?
