### ISSUE TITLE
[Crash]: JEI cheat mode crash after reloading resources

### ISSUE THREAD

**Issue by thelyric27** [mezz/JustEnoughItems#3756]
### Steps to Reproduce the Crash

Mod version: 15.18.0.79 Fabric, sourced from Curseforge
Mod loader: Quilt 0.26.4-beta.7
Minecraft version: 1.20.1

I was checking ore textures from the Excavated Variants mod with some different resource packs for a personal modpack when I started crashing while picking blocks from JEI with cheat mode in creative. When I first load the game, JEI looks and functions as normal, but if I go to the resource packs menu and change something, after reloading all the items in the JEI panel are disorganized, and without fail trying to pick one crashes the game. It doesn't seem to matter what item it is either. It crashes with errors such as 

"[Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseReleased event handler"

and

"java.lang.IndexOutOfBoundsException: Index 54 out of bounds for length 54"

### Mod Pack URL (Optional)

[Private, mod list within log]

### Extra Notes (Optional)

Now that I know exactly what causes it I can avoid the crash on my own and it shouldn't cause issues while me and my friends play, but when I was trying to find out why I was crashing I came across [this other unresolved issue](https://github.com/mezz/JustEnoughItems/issues/2880#issue-1298780793) and it seemed similar, also happening on the fabric version when picking up an item in cheat mode.

### Crash Report

https://mclo.gs/JKC1uQF

**Comment by mezz** [comment]
Thanks for the report!
You have many mods that alter the game in your mod list. Please try narrowing the issue down by seeing if this happens with JEI alone, and then try removing mods to figure out which one is causing a problem.
Also, JEI is built against Fabric so please try testing with it to make sure there isn't a problem coming from Quark.

**Comment by PUrE-elF** [comment]
@thelyric27 Is it going like this ?
![1429259](https://github.com/user-attachments/assets/f943f2af-7281-4116-a634-4ef57329d163)

**Comment by ShadoHax** [comment]
bumping, this seems to be the same issue as mentioned in #3859 based on crash logs

if you happen to have a need for cheat mode in creative mode, the below fix works (tested fabric 1.20.1)
> a temporary fix for this issue is available by changing the `GiveMode` flag within the `[cheat_mode]` section inside the `jei-client.ini` file from `MOUSE_PICKUP` to `INVENTORY` (`..\.minecraft\config\jei\jei-client.ini`)

**Comment by Trung0246** [comment]
Also bumping since I got this crash very frequently even with not doing any texture changes and just simply joining the world. This bug for me is not reliable in term of reproducing since the crash happens randomly even with a couple minutes ago when everything was fine when picking up items from JEI menu successfully then suddenly crash by simply just wait it out, doing nothing and picking items again.

```log
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2025-03-21 01:37:34
Description: mouseReleased event handler

java.lang.IndexOutOfBoundsException: Index 54 out of bounds for length 54
	at java.base@23.0.2/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base@23.0.2/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base@23.0.2/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base@23.0.2/java.util.Objects.checkIndex(Objects.java:365)
	at java.base@23.0.2/java.util.ArrayList.get(ArrayList.java:428)
	at knot//MC//net.minecraft.util.collection.DefaultedList.get(DefaultedList.java:47)
	at knot//MC//net.minecraft.screen.ScreenHandler.updateTrackedSlot(ScreenHandler.java:214)
	at knot//MC//net.minecraft.screen.ScreenHandler.sendContentUpdates(ScreenHandler.java:176)
	at knot//mezz.jei.common.util.ServerCommandUtil.mousePickupItemStack(ServerCommandUtil.java:153)
	at knot//mezz.jei.gui.util.CommandUtil.giveStack(CommandUtil.java:44)
	at knot//mezz.jei.gui.input.handlers.FocusInputHandler.lambda$handleGive$2(FocusInputHandler.java:119)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:490)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$7$1FlatMap.test(ReferencePipeline.java:307)
	at java.base@23.0.2/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$7$1FlatMap.test(ReferencePipeline.java:307)
	at java.base@23.0.2/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base@23.0.2/java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:397)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base@23.0.2/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base@23.0.2/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:677)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:292)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base@23.0.2/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1686)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base@23.0.2/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base@23.0.2/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:677)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:292)
	at java.base@23.0.2/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base@23.0.2/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:687)
	at knot//mezz.jei.gui.input.handlers.FocusInputHandler.handleGive(FocusInputHandler.java:125)
	at knot//mezz.jei.gui.input.handlers.FocusInputHandler.handleUserInput(FocusInputHandler.java:67)
	at knot//mezz.jei.gui.input.handlers.SameElementInputHandler.handleUserInput(SameElementInputHandler.java:25)
	at knot//mezz.jei.gui.input.handlers.UserInputRouter.lambda$handleExecuteClick$2(UserInputRouter.java:93)
	at java.base@23.0.2/java.util.Optional.flatMap(Optional.java:289)
	at knot//mezz.jei.gui.input.handlers.UserInputRouter.handleExecuteClick(UserInputRouter.java:93)
	at knot//mezz.jei.gui.input.handlers.UserInputRouter.handleUserInput(UserInputRouter.java:37)
	at knot//mezz.jei.gui.input.ClientInputHandler.onGuiMouseReleased(ClientInputHandler.java:86)
	at knot//mezz.jei.fabric.startup.EventRegistration.lambda$allowMouseRelease$2(EventRegistration.java:71)
	at java.base@23.0.2/java.util.Optional.map(Optional.java:260)
	at knot//mezz.jei.fabric.startup.EventRegistration.allowMouseRelease(EventRegistration.java:71)
	at knot//net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAllowMouseReleaseEvent$28(ScreenEventFactory.java:160)
	at knot//MC//net.minecraft.client.Mouse.handler$fko000$fabric-screen-api-v1$beforeMouseReleasedEvent(Mouse.java:5593)
	at knot//MC//net.minecraft.client.Mouse.method_1605(Mouse.java:109)
	at knot//MC//net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:431)
	at knot//MC//net.minecraft.client.Mouse.onMouseButton(Mouse.java:109)
	at knot//MC//net.minecraft.client.Mouse.method_22686(Mouse.java:196)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:108)
	at knot//MC//net.minecraft.client.Mouse.redirect$oci001$viafabricplus$storeEvent(Mouse.java:13057)
	at knot//MC//net.minecraft.client.Mouse.method_22684(Mouse.java:196)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at knot//imgui.glfw.ImGuiImplGlfw.mouseButtonCallback(ImGuiImplGlfw.java:124)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at knot//MC//net.minecraft.client.util.Window.swapBuffers(Window.java:303)
	at knot//MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1307)
	at knot//MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base@23.0.2/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base@23.0.2/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base@23.0.2/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base@23.0.2/java.util.Objects.checkIndex(Objects.java:365)
	at java.base@23.0.2/java.util.ArrayList.get(ArrayList.java:428)
	at knot//MC//net.minecraft.util.collection.DefaultedList.get(DefaultedList.java:47)
	at knot//MC//net.minecraft.screen.ScreenHandler.updateTrackedSlot(ScreenHandler.java:214)
	at knot//MC//net.minecraft.screen.ScreenHandler.sendContentUpdates(ScreenHandler.java:176)
	at knot//mezz.jei.common.util.ServerCommandUtil.mousePickupItemStack(ServerCommandUtil.java:153)
	at knot//mezz.jei.gui.util.CommandUtil.giveStack(CommandUtil.java:44)
	at knot//mezz.jei.gui.input.handlers.FocusInputHandler.lambda$handleGive$2(FocusInputHandler.java:119)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:490)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$7$1FlatMap.test(ReferencePipeline.java:307)
	at java.base@23.0.2/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$7$1FlatMap.test(ReferencePipeline.java:307)
	at java.base@23.0.2/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base@23.0.2/java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:397)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base@23.0.2/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base@23.0.2/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:677)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:292)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
	at java.base@23.0.2/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1686)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base@23.0.2/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base@23.0.2/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:677)
	at java.base@23.0.2/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:292)
	at java.base@23.0.2/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:147)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:588)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base@23.0.2/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base@23.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base@23.0.2/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:687)
	at knot//mezz.jei.gui.input.handlers.FocusInputHandler.handleGive(FocusInputHandler.java:125)
	at knot//mezz.jei.gui.input.handlers.FocusInputHandler.handleUserInput(FocusInputHandler.java:67)
	at knot//mezz.jei.gui.input.handlers.SameElementInputHandler.handleUserInput(SameElementInputHandler.java:25)
	at knot//mezz.jei.gui.input.handlers.UserInputRouter.lambda$handleExecuteClick$2(UserInputRouter.java:93)
	at java.base@23.0.2/java.util.Optional.flatMap(Optional.java:289)
	at knot//mezz.jei.gui.input.handlers.UserInputRouter.handleExecuteClick(UserInputRouter.java:93)
	at knot//mezz.jei.gui.input.handlers.UserInputRouter.handleUserInput(UserInputRouter.java:37)
	at knot//mezz.jei.gui.input.ClientInputHandler.onGuiMouseReleased(ClientInputHandler.java:86)
	at knot//mezz.jei.fabric.startup.EventRegistration.lambda$allowMouseRelease$2(EventRegistration.java:71)
	at java.base@23.0.2/java.util.Optional.map(Optional.java:260)
	at knot//mezz.jei.fabric.startup.EventRegistration.allowMouseRelease(EventRegistration.java:71)
	at knot//net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAllowMouseReleaseEvent$28(ScreenEventFactory.java:160)
	at knot//MC//net.minecraft.client.Mouse.handler$fko000$fabric-screen-api-v1$beforeMouseReleasedEvent(Mouse.java:5593)
	at knot//MC//net.minecraft.client.Mouse.method_1605(Mouse.java:109)
	at knot//MC//net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:431)
	at knot//MC//net.minecraft.client.Mouse.onMouseButton(Mouse.java:109)
	at knot//MC//net.minecraft.client.Mouse.method_22686(Mouse.java:196)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:108)
	at knot//MC//net.minecraft.client.Mouse.redirect$oci001$viafabricplus$storeEvent(Mouse.java:13057)
	at knot//MC//net.minecraft.client.Mouse.method_22684(Mouse.java:196)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at knot//imgui.glfw.ImGuiImplGlfw.mouseButtonCallback(ImGuiImplGlfw.java:124)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
Mixins in Stacktrace:
	imgui.glfw.ImGuiImplGlfw:
		foundry.veil.mixin.client.imgui.ImGuiImplGlfwMixin (veil.mixins.json)
	com.mojang.blaze3d.systems.RenderSystem:
		net.irisshaders.iris.mixin.MixinGlStateManager (mixins.iris.json)
		opekope2.optigui.mixin.RenderSystemMixin (optigui.mixins.json)
		me.ramidzkh.fabrishot.mixins.RenderSystemMixin (mixins.fabrishot.json)
		net.irisshaders.iris.mixin.statelisteners.MixinRenderSystem (mixins.iris.json)
		net.irisshaders.iris.mixin.MixinRenderSystem (mixins.iris.json)
		net.caffeinemc.mods.sodium.mixin.workarounds.event_loop.RenderSystemMixin (sodium-common.mixins.json)
		foundry.veil.mixin.client.pipeline.RenderSystemMixin (veil.mixins.json)
		io.github.foundationgames.animatica.mixin.RenderSystemMixin (animatica.mixins.json)
		io.wispforest.owo.mixin.ui.RenderSystemMixin (owo.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.hud_batching.compat.MixinRenderSystem (immediatelyfast-common.mixins.json)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_481
Stacktrace:
	at knot//MC//net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:431)
	at knot//MC//net.minecraft.client.Mouse.onMouseButton(Mouse.java:109)
	at knot//MC//net.minecraft.client.Mouse.method_22686(Mouse.java:196)
	at knot//MC//net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:108)
	at knot//MC//net.minecraft.client.Mouse.redirect$oci001$viafabricplus$storeEvent(Mouse.java:13057)
	at knot//MC//net.minecraft.client.Mouse.method_22684(Mouse.java:196)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
	at knot//imgui.glfw.ImGuiImplGlfw.mouseButtonCallback(ImGuiImplGlfw.java:124)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at knot//MC//net.minecraft.client.util.Window.swapBuffers(Window.java:303)
	at knot//MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1307)
	at knot//MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Mixins in Stacktrace:
	imgui.glfw.ImGuiImplGlfw:
		foundry.veil.mixin.client.imgui.ImGuiImplGlfwMixin (veil.mixins.json)
	com.mojang.blaze3d.systems.RenderSystem:
		net.irisshaders.iris.mixin.MixinGlStateManager (mixins.iris.json)
		opekope2.optigui.mixin.RenderSystemMixin (optigui.mixins.json)
		me.ramidzkh.fabrishot.mixins.RenderSystemMixin (mixins.fabrishot.json)
		net.irisshaders.iris.mixin.statelisteners.MixinRenderSystem (mixins.iris.json)
		net.irisshaders.iris.mixin.MixinRenderSystem (mixins.iris.json)
		net.caffeinemc.mods.sodium.mixin.workarounds.event_loop.RenderSystemMixin (sodium-common.mixins.json)
		foundry.veil.mixin.client.pipeline.RenderSystemMixin (veil.mixins.json)
		io.github.foundationgames.animatica.mixin.RenderSystemMixin (animatica.mixins.json)
		io.wispforest.owo.mixin.ui.RenderSystemMixin (owo.mixins.json)
		net.raphimc.immediatelyfast.injection.mixins.hud_batching.compat.MixinRenderSystem (immediatelyfast-common.mixins.json)
	net.minecraft.client.main.Main:
		de.florianmichael.viafabricplus.injection.mixin.base.MixinMain (viafabricplus.mixins.json)
		dev.kir.cubeswithoutborders.client.mixin.MainMixin (cubes-without-borders.mixins.json)
		foundry.veil.mixin.debug.RenderDocker (veil.mixins.json)

-- Uptime --
Details:
	JVM uptime: 514.391s
	Wall uptime: 491.810s
	High-res time: 458.588s
	Client ticks: 5220 ticks / 261.000s
Stacktrace:
	at knot//MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2501)
	at knot//MC//net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:949)
	at knot//MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:902)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		de.florianmichael.viafabricplus.injection.mixin.base.MixinMain (viafabricplus.mixins.json)
		dev.kir.cubeswithoutborders.client.mixin.MainMixin (cubes-without-borders.mixins.json)
		foundry.veil.mixin.debug.RenderDocker (veil.mixins.json)
```
