### ISSUE TITLE
[Bug]: When I downloaded the newest version of JEI into my modpack, it broke the creative mode search.

### ISSUE THREAD

**Issue by Untrustedlife** [mezz/JustEnoughItems#3776]
### Steps to Reproduce the Bug

Go to creative mode -> try searching for an item, but nothing comes up, even with single-letter searches

### Expected Behavior

Searches in creative mode work.

### Actual Behavior

It never actually finds anything.

### Mod Pack URL (Optional)

https://www.curseforge.com/minecraft/modpacks/uls-zsurvival-craft

### Mod Pack Version (Optional)

1.40 (But i also downgraded jei so it works again)

### Extra Notes (Optional)

I dont have a latest log right now as that woudl require re-updating the mod and im currently working.
I did see an actual error though, wish i had saved it.
If no one else is having this issue just deelte the ticket.

Also, downgrading JEI to the version released on july 18th fixes the issue.
11.6.0.1024 is the version that works.

**Comment by mezz** [comment]
Thanks for the report!

I'm not able to reproduce this issue with just JEI installed.
It seems like another mod is conflicting with JEI or causing an issue here.
Please try to see if this bug happens with JEI alone, and then try removing mods to figure out which one is causing a problem.

If you find that there is only one other mod causing an issue, please report it to them and link back here.
Otherwise if you still can't figure it out, please paste your new crash log and client logs here, and I can help debug or find the right place to report to.

**Comment by Untrustedlife** [comment]
I updated again and tested and heres the error im getting,

> java.lang.invoke.WrongMethodTypeException: expected (IngredientFilter,String)Stream but found (IngredientFilter,String)List
	at java.lang.invoke.Invokers.newWrongMethodTypeException(Invokers.java:523) ~[?:?]
	at java.lang.invoke.Invokers.checkExactType(Invokers.java:532) ~[?:?]
	at org.embeddedt.modernfix.searchtree.JEIBackedSearchTree.searchJEI(JEIBackedSearchTree.java:78) ~[modernfix-forge-5.18.0+mc1.19.2.jar%23421!/:5.18.0+mc1.19.2]
	at org.embeddedt.modernfix.searchtree.JEIBackedSearchTree.m_6293_(JEIBackedSearchTree.java:65) ~[modernfix-forge-5.18.0+mc1.19.2.jar%23421!/:5.18.0+mc1.19.2]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_98630_(CreativeModeInventoryScreen.java:379) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.m_7933_(CreativeModeInventoryScreen.java:319) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$4(KeyboardHandler.java:353) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.KeyboardHandler.m_90893_(KeyboardHandler.java:343) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.KeyboardHandler.m_167831_(KeyboardHandler.java:442) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.KeyboardHandler.m_90938_(KeyboardHandler.java:441) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%23136!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%23144!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23493!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

[latest.log](https://github.com/user-attachments/files/17176648/latest.log)

I think it must be Modernfix causing the issue.

Edit:
testing after disabling that in modernfix's config fixes the issue.
Closing Ticket

**Comment by Untrustedlife** [comment]
It was an issue with modernfix's JEI integration.

**Comment by Kherosen** [comment]
> It was an issue with modernfix's JEI integration.

OMG i had literally the same issue... Fabuously optimized had installed modernfix... seems like modernfix was outdated. Updating it has solved the issue
