### ISSUE TITLE
JEI crash when searching fot tinker construct items

### ISSUE THREAD

**Issue by jonabrv1965** [mezz/JustEnoughItems#379]
Hi, im gettig crash whe looking for TC items, I´m using the latest verion of JEI(Java and tc... here an excerpt of the crash log : 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CodeChickenCorePlugin (CodeChickenCore-1.9.4-2.0.4.71-universal.jar)
  IC2core (industrialcraft-2-2.6.30-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.46-beta.jar)
  CCCDeobfPlugin (unknown)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  CCLCorePlugin (CodeChickenLib-1.9.4-2.1.2.42-universal.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 8/7/16 5:20 PM
Description: Updating screen events

java.lang.NullPointerException: ItemStack returned null IBakedModel from RenderItem.getItemModelWithOverrides(stack, null, null). 1xtile.tconstruct.toolforge@0 tconstruct:toolforge nbt:{textureBlock:{id:"techreborn:techreborn.storage",Count:1b,Damage:14s}}
    at mezz.jei.gui.ingredients.GuiItemStackFastList.set(GuiItemStackFastList.java:61)
    at mezz.jei.gui.ItemListOverlay.updateLayout(ItemListOverlay.java:247)
    at mezz.jei.gui.ItemListOverlay.onKeyPressed(ItemListOverlay.java:510)
    at mezz.jei.input.InputHandler.handleKeyDown(InputHandler.java:208)
    at mezz.jei.input.InputHandler.handleKeyEvent(InputHandler.java:198)
    at mezz.jei.GuiEventHandler.onGuiKeyboardEvent(GuiEventHandler.java:133)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_250_GuiEventHandler_onGuiKeyboardEvent_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

https://gist.github.com/jonabrv1965/aa20454e9673e2efd9998e0830a6c088

When reporting:
- If you use ForeverEnoughItems, please remove it and try again or [report here instead](https://github.com/elix-x/Forever-Enough-Items/issues).  
- Please do not suggest features from NEI. [NotEnoughWidgets will have those features.](https://github.com/TheCBProject/NotEnoughItems/issues/6)
- Try the [latest version](http://minecraft.curseforge.com/projects/just-enough-items-jei/files), it may have fixed the issue already.
- If you crashed, please paste the crash log to https://gist.github.com/ and link it here.

**Comment by TehNut** [comment]
This is caused by TechReborn. Update it.
