### ISSUE TITLE
game crashes and say jei failed to start

### ISSUE THREAD

**Issue by ingydav** [mezz/JustEnoughItems#403]
hi every time i load minecraft its saying jei failed to open, i'm new to modded minecraft so don't know if its something i've done, i have tried several versions and it keeps crashing

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  llibrary (llibrary-1.5.1-1.10.2.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  CCLCorePlugin (CodeChickenLib-1.9.4-2.1.2.42-universal.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 8/21/16 10:37 AM
XRay version: 31
Description: JEI failed to start:

com.google.common.util.concurrent.ExecutionError: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
    at mezz.jei.ItemFilter.<init>(ItemFilter.java:43)
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:185)
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:142)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_450_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraft.world.World.func_72838_d(World.java:1127)
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:251)
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451)
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(SourceFile:45)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
    at cofh.api.energy.ItemEnergyContainer.getEnergyStored(ItemEnergyContainer.java:98)
    at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.func_77624_a(ItemEnergy.java:72)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:610)
    at mezz.jei.util.ItemStackElement.<init>(ItemStackElement.java:76)
    at mezz.jei.util.ItemStackElement.create(ItemStackElement.java:44)
    at mezz.jei.ItemFilter.createBaseList(ItemFilter.java:84)
    at mezz.jei.ItemFilter.access$100(ItemFilter.java:30)
    at mezz.jei.ItemFilter$ItemFilterCacheLoader.load(ItemFilter.java:119)
    at mezz.jei.ItemFilter$ItemFilterCacheLoader.load(ItemFilter.java:109)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
    ... 30 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Mac OS X (x86_64) version 10.11.6
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2335273336 bytes (2227 MB) / 4281597952 bytes (4083 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
    FML: Minecraft 1.10.2 MCP 9.32 Powered by Forge 12.18.1.2053 Optifine OptiFine_1.10.2_HD_U_C1 93 mods loaded, 93 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2053.jar) 
    UCHIJAAAA   Forge{12.18.1.2053} [Minecraft Forge] (forge-1.10.2-12.18.1.2053.jar) 
    UCHIJAAAA   cei{1.3} [Chunk Edge Indicator] (1.10-chunkedgeindicator-1.3.jar) 
    UCHIJAAAA   actuallyadditions{1.10.2-r60} [Actually Additions] (ActuallyAdditions-1.10.2-r60.jar) 
    UCHIJAAAA   cxlibrary{1.2.2} [CXLibrary] (cxlibrary-1.10.2-1.2.2.jar) 
    UCHIJAAAA   advInv{1.2.0} [Advanced Inventory] (advInv-1.10-1.2.0-2.jar) 
    UCHIJAAAA   JEI{3.9.0.244} [Just Enough Items] (jei_1.10.2-3.9.0.244.jar) 
    UCHIJAAAA   AppleCore{1.3.5} [AppleCore] (AppleCore-mc1.10.2-1.3.5.jar) 
    UCHIJAAAA   armorplus{1.9.4-3.1.10.0} [ArmorPlus] (ArmorPlus1.9.4-3.1.10.0.jar) 
    UCHIJAAAA   mcmultipart{1.2.0} [MCMultiPart] (MCMultiPart-1.2.0-universal.jar) 
    UCHIJAAAA   bagelsmore{1.0.1} [Bagelsmore: The Return] (Bagelsmore-1.9.4-1.0.1.jar) 
    UCHIJAAAA   basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0-2.jar) 
    UCHIJAAAA   baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10-2.jar) 
    UCHIJAAAA   betteragriculture{0.16} [Better Agriculture] (BetterAgriculture_(MC-1.10)-0.16.jar) 
    UCHIJAAAA   BiomesOPlenty{5.0.0.2067} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2067-universal-2.jar) 
    UCHIJAAAA   bookshelfapi{3.2.2} [Bookshelf] (Bookshelf-API-1.10.2-3.2.2.jar) 
    UCHIJAAAA   Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312-2.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   chancecubes{1.10-2.2.1.120} [Chance Cubes] (ChanceCubes-1.10-2.2.1.120.jar) 
    UCHIJAAAA   ChestTransporter{2.5.1} [Chest Transporter] (ChestTransporter-1.10.2-2.5.1.jar) 
    UCHIJAAAA   cookingforblockheads{3.1.26} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.1.26.jar) 
    UCHIJAAAA   counter_guns{1.0.1} [Counter Guns] (CounterGuns-1.10.2-1.0.1.jar) 
    UCHIJAAAA   craftingcraft{4.1.6} [CraftingCraft] (CraftingCraft_1.10.2-4.1.6.jar) 
    UCHIJAAAA   cyclopscore{0.7.5} [Cyclops Core] (CyclopsCore-1.9.4-0.7.5.jar) 
    UCHIJAAAA   dldungeonsjdg{1.8.13} [Doomlike Dungeons] (DoomlikeDungeons-1.8.13-MC1.10.jar) 
    UCHIJAAAA   druidry{2016.8.10-1.9.4} [�2Druidry] (druidry(2016.8.10.2)(1.9.9).jar) 
    UCHIJAAAA   EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
    UCHIJAAAA   endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
    UCHIJAAAA   enderutilities{0.6.5} [Ender Utilities] (enderutilities-1.10.2-0.6.5.jar) 
    UCHIJAAAA   evilcraft{0.10.8} [EvilCraft] (EvilCraft-1.10.2-0.10.8.jar) 
    UCHIJAAAA   excore{1.6.1} [EXCore] (Excore-1.6.1-1.10.2.jar) 
    UCHIJAAAA   expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.8.jar) 
    UCHIJAAAA   golems{6.01} [Extra Golems] (ExtraGolems[1.10]-6.01.jar) 
    UCHIJAAAA   feldinshomesteadmod{1.0.1.2} [Feldins Homestead Mod] (FeldinsHomesteadMod-1.0.1.2.jar) 
    UCHIJAAAA   forestry{5.2.8.236} [Forestry] (forestry_1.10.2-5.2.8.236.jar) 
    UCHIJAAAA   substratum{1.7.0.0} [Substratum] (Substratum-1.10.2-1.7.0.0.jar) 
    UCHIJAAAA   foundry{2.1.0.1} [Foundry] (Foundry-1.10.2-2.1.0.1.jar) 
    UCHIJAAAA   glowniummod{1.0.0} [Glownium (Craftable Glowstone)] (glownium (craftable glowstone) [1.0.0].jar) 
    UCHIJAAAA   godweapons{4.5_1.9.4} [Gods' Weapons] (godweapons - 4.5_1.9.4.jar) 
    UCHIJAAAA   grapple_hooks{1.0.8} [Grapple Hooks] (Grapple-Hooks-1.10.2-1.0.8.jar) 
    UCHIJAAAA   gravestone{1.5.5} [Gravestone] (GraveStone Mod 1.5.5.jar) 
    UCHIJAAAA   InventoryPets{1.4.8.1} [Inventory Pets] (inventorypets-1.10-1.4.8.1-2.jar) 
    UCHIJAAAA   IrishLuck{0.1.3} [Irish Luck] (IrishLuck-0.1.3-MC[1.9.4-1.10-1.10.2].jar) 
    UCHIJAAAA   IronChest{7.0.7.795} [Iron Chest] (ironchest-1.10.2-7.0.7.795.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.10.2-2.1.jar) 
    UCHIJAAAA   llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.10.2.jar) 
    UCHIJAAAA   llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
    UCHIJAAAA   LunatriusCore{1.1.2.36} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
    UCHIJAAAA   malisiscore{1.9.4-4.1.1} [MalisisCore] (malisiscore-1.9.4-4.1.1.jar) 
    UCHIJAAAA   malisisdoors{1.9.4-5.0.3} [MalisisDoors] (malisisdoors-1.9.4-5.0.3.jar) 
    UCHIJAAAA   mantle{1.10.2-0.10.4.jenkins163} [Mantle] (Mantle-1.10.2-0.10.4.jar) 
    UCHIJAAAA   RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
    UCHIJAAAA   MCA{1.10.2-5.2.2} [Minecraft Comes Alive] (MCA-1.10.2-5.2.2-universal.jar) 
    UCHIJAAAA   minemenu{1.4.4} [MineMenu] (MineMenu-1.10.X-1.4.4.B9-universal.jar) 
    UCHIJAAAA   shetiphiancore{3.3.0} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.0.jar) 
    UCHIJAAAA   multibeds{1.2.0} [Multi-Beds] (multibeds-1.10.0-1.2.0.jar) 
    UCHIJAAAA   ninjagear{1.10.2-0.0.3} [NinjaGear] (ninjagear-0.0.3.jar) 
    UCHIJAAAA   recipehandler{0.5} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.5(1.10.2).jar) 
    UCHIJAAAA   orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
    UCHIJAAAA   packingtape{0.5.2} [Packing Tape] (PackingTape-1.9.4-0.5.2.jar) 
    UCHIJAAAA   getalltheseeds{1.9.4-1.10.2a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds! 1.9.4-1.10.2a.jar) 
    UCHIJAAAA   harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2b.jar) 
    UCHIJAAAA   simplerecipes{1.9.4-1.10.2a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.9.4-1.10.2a.jar) 
    UCHIJAAAA   samsapples{1.1.5} [Power Apples] (PowerApples-1.10.2-1.1.5.jar) 
    UCHIJAAAA   prefab{1.1.1.0} [Prefab] (prefab-1.1.1.0.jar) 
    UCHIJAAAA   reap{1.3.0} [Reap Mod] (ReapMod 1.3.0.jar) 
    UCHIJAAAA   reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-57.jar) 
    UCHIJAAAA   ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
    UCHIJAAAA   corerm{1.2e-1.9.4} [RikMuld's Core] (RikMuldsCore_1.2e-1.10.2.jar) 
    UCHIJAAAA   Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJAAAA   roughMobs{1.0} [Rough Mobs] (roughMobs1.0.7-1.10.2.jar) 
    UCHIJAAAA   sccraftingrunes{1.1} [SeriousCreeper's Crafting Runes] (sccraftingrunes-1.1.jar) 
    UCHIJAAAA   SilentLib{1.0.12} [Silent Lib] (SilentLib-1.9.4-1.0.12-20.jar) 
    UCHIJAAAA   SilentGems{2.0.20} [Silent's Gems] (SilentsGems-1.10-2.0.20-48.jar) 
    UCHIJAAAA   SimpleUpgrades{2.0.8} [SimpleUpgrades] (simpleupgrades-1.9.4-2.0.8-release.jar) 
    UCHIJAAAA   Souls{1.1.0} [Souls] (Souls-1.10.2-1.1.0.jar) 
    UCHIJAAAA   soulshardstow{1.10.2-2.6.2-42} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.2-42.jar) 
    UCHIJAAAA   staircraftmod{5.0} [Staircraft] (Staircraftmod v5.0 - MC1.9.4 Forge.jar) 
    UCHIJAAAA   StorageDrawers{1.9.4-3.2.1} [Storage Drawers] (StorageDrawers-1.9.4-3.2.1.jar) 
    UCHIJAAAA   tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
    UCHIJAAAA   taiga{${version}} [Tinkers Alloying Addon] (taiga-1.10.2-1.1.2.jar) 
    UCHIJAAAA   techbackpack{1.1a} [Tech Backpack] (techbackpack-1.1a-1.10.jar) 
    UCHIJAAAA   thedragoncore{1.1.0} [TheDragonCore] (thedragoncore-1.1.0.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4-2.jar) 
    UCHIJAAAA   tinker_io{release 2.3.3} [Tinker I/O] (tinker_io-1.10.2-release 2.3.3.jar) 
    UCHIJAAAA   TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3-2.jar) 
    UCHIJAAAA   waterstrainer{1.2.1} [Water Strainer] (WaterStrainer-1.9.4-1.2.1.jar) 
    UCHIJAAAA   weaponcaseloot{4.0.1} [WeaponCaseLoot] (weaponcaseloot-1.10.2-4.0.1.jar) 
    UCHIJAAAA   worldedit{6.1.3} [WorldEdit] (worldedit-forge-mc1.9.4-6.1.3-dist.jar) 
    UCHIJAAAA   XaeroMinimap{1.10} [Xaero's Minimap] (Xaeros_Minimap_1.10_Forge_1.10.2-4.jar) 
    Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  squeek.applecore.asm.TransformerModuleHandler
llibrary (llibrary-1.5.1-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.9.4-2.1.2.42-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - WailaIntegration (Enabled/Not Forced)

    OptiFine Version: OptiFine_1.10.2_HD_U_C1
    Render Distance Chunks: 8
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 2.1 INTEL-10.14.73
    OpenGlRenderer: Intel(R) HD Graphics 6000
    OpenGlVendor: Intel Inc.
    CpuCount: 4 
```

**Comment by TehNut** [comment]
#366

**Comment by mezz** [comment]
Thanks for the report!
This is an ActuallyAdditions issue, it looks like you have the latest version so please report it to them: https://github.com/Ellpeck/ActuallyAdditions/issues
