### ISSUE TITLE
Game crashes when joining the server. 

### ISSUE THREAD

**Issue by paustin123** [mezz/JustEnoughItems#426]
Thank you for reporting!

When reporting:
- If you use ForeverEnoughItems, please remove it and try again or [report here instead](https://github.com/elix-x/Forever-Enough-Items/issues).  
- Please do not suggest features from NEI. [See this spreadsheet for the mods with those features.](https://goo.gl/MQ0f3R)
- Try the [latest version](http://minecraft.curseforge.com/projects/just-enough-items-jei/files), it may have fixed the issue already.
- If you crashed, please paste the crash log to https://gist.github.com/ and link it here.

**Comment by paustin123** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  GenderLoadingPlugin ([1.10.2]Gender-1.2.5.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 9/14/16 10:21 PM
Description: JEI failed to start:

com.google.common.util.concurrent.ExecutionError: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
    at mezz.jei.ItemFilter.<init>(ItemFilter.java:43)
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:185)
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:142)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_244_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraft.world.World.func_72838_d(World.java:1129)
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:253)
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451)
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(SourceFile:45)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77990_d from class cofh.api.energy.ItemEnergyContainer
    at cofh.api.energy.ItemEnergyContainer.getEnergyStored(ItemEnergyContainer.java:98)
    at de.ellpeck.actuallyadditions.mod.items.base.ItemEnergy.func_77624_a(ItemEnergy.java:72)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:614)
    at mezz.jei.util.ItemStackElement.<init>(ItemStackElement.java:76)
    at mezz.jei.util.ItemStackElement.create(ItemStackElement.java:44)
    at mezz.jei.ItemFilter.createBaseList(ItemFilter.java:84)
    at mezz.jei.ItemFilter.access$100(ItemFilter.java:30)
    at mezz.jei.ItemFilter$ItemFilterCacheLoader.load(ItemFilter.java:119)
    at mezz.jei.ItemFilter$ItemFilterCacheLoader.load(ItemFilter.java:109)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
    ... 30 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 994366600 bytes (948 MB) / 1968943104 bytes (1877 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2081 Optifine OptiFine_1.10.2_HD_U_C3 40 mods loaded, 40 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2081.jar) 
    UCHIJA  Forge{12.18.1.2081} [Minecraft Forge](forge-1.10.2-12.18.1.2081.jar) 
    UCHIJA  gender{1.2.5} [Gender]([1.10.2]Gender-1.2.5.jar) 
    UCHIJA  bettercombatmod{1.3.5} [Better Combat]([MC 1.10.X] BetterCombatMod 1.3.5.jar) 
    UCHIJA  actuallyadditions{1.10.2-r62} [Actually Additions](ActuallyAdditions-1.10.2-r62.jar) 
    UCHIJA  thedragoncore{1.1.0} [TheDragonCore](thedragoncore-1.1.0.jar) 
    UCHIJA  armorplus{1.10.2-6.0.9.2} [ArmorPlus](armorplus-1.10.2-6.0.9.2.jar) 
    UCHIJA  backpack{3.0.1} [Backpack](backpack-3.0.1-1.10.2.jar) 
    UCHIJA  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJA  BiomesOPlenty{5.0.0.2085} [Biomes O' Plenty](BiomesOPlenty-1.10.2-5.0.0.2085-universal.jar) 
    UCHIJA  bookshelf{1.4.0.291} [Bookshelf](Bookshelf-1.10.2-1.4.0.291.jar) 
    UCHIJA  ChestTransporter{2.5.2} [Chest Transporter](ChestTransporter-1.10.2-2.5.2.jar) 
    UCHIJA  DynamicLights{1.4.3} [Dynamic Lights](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.10.2.jar) 
    UCHIJA  DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.10.2.jar) 
    UCHIJA  excore{1.6.2} [EXCore](Excore-1.6.2-1.10.2.jar) 
    UCHIJA  hopperducts{1.4.8} [Hopper Ducts](hopperducts-mc1.9.4-1.4.8.jar) 
    UCHIJA  mantle{1.10.2-1.0.0.jenkins170} [Mantle](Mantle-1.10.2-1.0.0.jar) 
    UCHIJA  tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct](TConstruct-1.10.2-2.4.0.jar) 
    UCHIJA  immersiveengineering{${version}} [Immersive Engineering](ImmersiveEngineering-0.10-40.jar) 
    UCHIJA  InfernalMobs{1.7.1} [Infernal Mobs](InfernalMobs-1.10.jar) 
    UCHIJA  InventoryPets{1.4.8.1} [Inventory Pets](inventorypets-1.10-1.4.8.1.jar) 
    UCHIJA  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJA  JEI{3.9.3.253} [Just Enough Items](jei_1.10.2-3.9.3.253.jar) 
    UCHIJA  journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJA  levels{r4.1.3} [Levels](Levels-1.10.2-r4.1.3.jar) 
    UCHIJA  RadixCore{1.10.2-2.1.3} [RadixCore](RadixCore-1.10.2-2.1.3-universal.jar) 
    UCHIJA  MCA{1.10.2-5.2.3} [Minecraft Comes Alive](MCA-1.10.2-5.2.3-universal.jar) 
    UCHIJA  progressiveautomation{1.6.51} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.51.jar) 
    UCHIJA  redstonepaste{1.7.4} [Redstone Paste](redstonepaste-mc1.9.4-1.7.4.jar) 
    UCHIJA  icse{1.1.0.0} [I Can See Everything](Wawla-1.10.2-2.3.0.203.jar) 
    UCHIJA  wawla{2.3.0.202} [What Are We Looking At](Wawla-1.10.2-2.3.0.203.jar) 
    Loaded coremods (and transformers): 
GenderLoadingPlugin ([1.10.2]Gender-1.2.5.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13447 Compatibility Profile Context 16.300.2511.1001' Renderer: 'AMD Radeon R7 200 Series'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)

```
OptiFine Version: OptiFine_1.10.2_HD_U_C3
Render Distance Chunks: 20
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.13447 Compatibility Profile Context 16.300.2511.1001
OpenGlRenderer: AMD Radeon R7 200 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 8
```

**Comment by TehNut** [comment]
#366

**Comment by paustin123** [comment]
Ah okay. I was browsing and didn't see that. Thank you.

**Comment by mezz** [comment]
I just submitted this issue to ActuallyAdditions.
