### ISSUE TITLE
Game crashes when loading with TSON craft

### ISSUE THREAD

**Issue by theredghostwolf** [mezz/JustEnoughItems#455]
Caused by: java.lang.ClassNotFoundException: com.Cobbs.cavecraft.Utilities.JEI.compactorRecipe
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 29 more

[crash-2016-09-26_15.22.50-client.txt](https://github.com/mezz/JustEnoughItems/files/493184/crash-2016-09-26_15.22.50-client.txt)
https://gist.github.com/mezz/2b95628e236cdaf266e7b70253d540f5

not sure if this is a TSON craft problem or if JEI is causing it reporting it on both ends.

thank you for fixing this.

**Comment by mezz** [comment]
Thanks for the report!
This looks like a TSON craft problem, they were referencing a class internal to JEI that no longer exists.
Looks like it was reported already: https://minecraft.curseforge.com/projects/tson-craft/issues/8
