### ISSUE TITLE
Crash with Endergizer

### ISSUE THREAD

**Issue by ChaosCron1** [mezz/JustEnoughItems#460]
java.lang.NoClassDefFoundError: net/shadowfacts/endergizer/compat/jei/BatteryRecipeWrapper
    at net.shadowfacts.endergizer.compat.jei.ERecipeHandler.getRecipeWrapper(ERecipeHandler.kt:21)
    at net.shadowfacts.endergizer.compat.jei.ERecipeHandler.getRecipeWrapper(ERecipeHandler.kt:11)
    at mezz.jei.util.ErrorUtil.getInfoFromBrokenRecipe(ErrorUtil.java:30)
    at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:212)
    at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:167)
    at mezz.jei.RecipeRegistry.addRecipes(RecipeRegistry.java:151)
    at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:85)
    at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:185)
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:198)
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:142)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_515_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraft.world.World.func_72838_d(World.java:1129)
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:253)
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451)
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(SourceFile:45)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by shadowfacts** [comment]
Oops, I'm using `VanillaRecipeWrapper`. I'll try and fix that later tonight...

**Comment by mezz** [comment]
Thanks for the report!
This is an issue on Endergizer's side. To help shadowfacts remember you can post the issue here: https://github.com/shadowfacts/Endergizer/issues
