### ISSUE TITLE
CTD when entering a world

### ISSUE THREAD

**Issue by robaimes** [mezz/JustEnoughItems#500]
MC crashes when I am attempting to join a world. I have tried 2 existing worlds and creating 2 new worlds. Each time has replicated the exact same issue regardless.
- **[Crash report](https://gist.github.com/iamomicron/012c99a5c66506ccb25dffd29bd8f81d)**
- Have tried multiple versions of JEI:
  - `jei_1.10.2-3.12.2.291`
  - `jei_1.10.2-3.12.5.297`
  - `jei_1.10.2-3.12.5.298`
- Have tried the two latest versions of Forge:
  - `1.10.2-12.18.1.2094`
  - `1.10.2-12.18.1.2095`

I am fairly certain this is a cross-mod compatibility issue, but the stacktrace is not overly helpful in debugging what it may be.

**Comment by mezz** [comment]
Thanks for the report!
Please link your full client log, I need some more information to find out what is going wrong.

**Comment by CitiesXL2815** [comment]
might be ender io this all started from updating ender io, it was fine yesterday last night no crash. it's probably guest if it's ender io

**Comment by robaimes** [comment]
Sure thing: https://dl.dropboxusercontent.com/u/76791645/Downloads/fml-client-latest.log

Provided a download instead, as it's a little long.

**Comment by robaimes** [comment]
Welp, @CitiesXL2815 solved it. Seems like removing EnderIO / EnderCore solved the issue for now.

**Comment by mezz** [comment]
I think JEI is suppressing an earlier crash without logging it.
I built a new version of JEI with a better log. Can you run it and paste the client log here again?
JEI 3.12.5.299
https://dvs1.progwml6.com/jenkins/job/JustEnoughItems/

With your help we can fix this issue and ones like it for the future.

**Comment by robaimes** [comment]
Sure thing.

Crash log remained the same, but here's the [forge log](https://dl.dropboxusercontent.com/u/76791645/Downloads/fml-client-latest-2.log).

**Comment by mezz** [comment]
Ok, perfect! Here's the underlying crash that causes the issue:

```
[05:26:34] [Client thread/ERROR] [JEI/]: Error registering ingredients.
java.lang.NoClassDefFoundError: net/darkhax/tesla/capability/TeslaCapabilities
    at sonar.core.network.sync.SyncItemEnergyStorage.hasCapability(SyncItemEnergyStorage.java:53) ~[SyncItemEnergyStorage.class:?]
    at net.minecraftforge.common.capabilities.CapabilityDispatcher.hasCapability(CapabilityDispatcher.java:93) ~[CapabilityDispatcher.class:?]
    at net.minecraft.item.ItemStack.hasCapability(ItemStack.java:1039) ~[adz.class:?]
    at mezz.jei.SubtypeRegistry.getSubtypeInfo(SubtypeRegistry.java:66) ~[SubtypeRegistry.class:?]
    at mezz.jei.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:376) ~[StackHelper.class:?]
    at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory.addItemStack(ItemStackListFactory.java:101) ~[ItemStackListFactory.class:?]
    at mezz.jei.plugins.vanilla.ingredients.ItemStackListFactory.create(ItemStackListFactory.java:43) ~[ItemStackListFactory.class:?]
    at mezz.jei.plugins.vanilla.VanillaPlugin.registerIngredients(VanillaPlugin.java:91) [VanillaPlugin.class:?]
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:159) [ProxyCommonClient.class:?]
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:120) [ProxyCommonClient.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_725_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic) [?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
    at net.minecraft.world.World.func_72838_d(World.java:1129) [aid.class:?]
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196) [bln.class:?]
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359) [bcx.class:?]
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276) [bll.class:?]
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76) [gw.class:?]
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13) [gw.class:?]
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
    at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
    ... 33 more
```

Please report this to Sonar Core: https://github.com/SonarSonic/Sonar-Core/issues
They should have a better idea of how to fix it.

In the meantime I'll write some checks to make sure a crash like this is just logged and doesn't kill JEI entirely.

**Comment by mezz** [comment]
JEI version 3.12.5.300 (done building in a few minutes) should keep running and just log a descriptive error log for the broken ItemStack. Please let me know if it doesn't work.

**Comment by CitiesXL2815** [comment]
sure thing mezz

**Comment by robaimes** [comment]
Awesome, thanks for the quick response. I did notice that after looking myself too, and found [this commit](https://github.com/SonarSonic/Sonar-Core/commit/0d305a2a4ea5baaa2b845d318d818e8f962bc1d2) which may or may not have fixed it, but the build is not public.

Reported the issue over [here](https://github.com/SonarSonic/Sonar-Core/issues/12) none the less.

**Comment by CitiesXL2815** [comment]
mezz i got rid of sonar core and it still crashed same log, i'm thinking it might be Ender IO, i'll wait before reporting it to Ender IO

**Comment by mezz** [comment]
I suspect the TeslaAPI is broken, the jar file shows up in the mod list but not in the section for `[bdlib/bdlib]: List of loaded APIs:`.

**Comment by robaimes** [comment]
Strangely enough, [it still crashes](http://pastebin.com/PJinvhaM) when using build 300, although it is a different error.

This crash was also logged in the previous log attached. I do understand that this is a TESLA related issue, however it does mention JEI in the stacktrace, so I'll add it here in case of an error.

As mentioned [here](https://github.com/mezz/JustEnoughItems/issues/500#issuecomment-251582448) this no longer occurs with Ender IO removed. 

```
    at mezz.jei.IngredientRegistry.<init>(IngredientRegistry.java:44)
    at mezz.jei.ModIngredientRegistration.createIngredientRegistry(ModIngredientRegistration.java:67)
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:168)
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:120)
```

The crash log attached is pointing to 'Energy Arsenal' but once removed the same issue occurs with Refined Storage. I suspect this would happen to many others too and is likely a TESLA issue.

**Comment by mezz** [comment]
Well at least this crash report is accurate (shows what's really crashing instead of JEI just blowing up later).
I guess I should protect against crashes there too, why not...? I'll get that out shortly.
Who knows if the game is even going to run once it gets past JEI though haha.

**Comment by CitiesXL2815** [comment]
mezz double check the crash log this time it refined storage after removing sonar core same problem with JEI but with Refined Storage, also energy arsenal disabled due to botania

**Comment by CitiesXL2815** [comment]
Nvm i'm confused i'll wait until it's fixed

**Comment by mezz** [comment]
JEI 301 is out if you want to try again.

**Comment by CitiesXL2815** [comment]
sure

**Comment by CitiesXL2815** [comment]
tesla, Refined Storage and JEI in the crash log again, something doesn't like to work lol

**Comment by mezz** [comment]
Can you link your crash log? My goal is to make sure that JEI doesn't crash unless it reallllyy has to.

**Comment by robaimes** [comment]
Yup. Same as above, except for another mod. (Same CNFE, though) The issue is reported to TESLA repo anyway. Hopefully some news will follow on that issue soon.

[Bug Catcher Omicron wants to battle!](http://pastebin.com/URgD0qz9)

**Comment by CitiesXL2815** [comment]
Here it is https://gist.github.com/9bc78f8ec5acaf7e9e378dd4856e6d39.git

**Comment by mezz** [comment]
Heh it's crashing where I try to log the error. Almost there...

**Comment by DatrixTHLK** [comment]
Getting that same error also. https://gist.github.com/DatrixTHLK/6642f0326625436e0e258969e6f50bb1 I'll take out tesla mod and see if it will work after that. This way we know the true culprit of the crash. If not Tesla then I will take out Ender IO and Endercore.

**Edit 2:07am:** It definitely was Tesla. My game loaded up just fine after taking it out.

**Comment by mezz** [comment]
Yet more error handling added in JEI build 302, if your game does crash it shouldn't involve JEI now.

**Comment by robaimes** [comment]
[I hate to be the bearer of bad news...](http://pastebin.com/rjZBmN8x)

**Comment by mezz** [comment]
Oh, I didn't protect the legacy method... d'oh.

**Comment by CitiesXL2815** [comment]
worked for me haha i'm in mezz looks like you fixed the problem

**Comment by mezz** [comment]
Ok never mind, that particular itemstack is waaay too broken. It's breaking when I call `itemStack.getItemDamage()` which is just... crazy. I can't defend against that haha.

**Comment by mezz** [comment]
Thanks for helping out, everybody.

**Comment by robaimes** [comment]
Understandable. Thanks for all the work regardless, very grateful.

**Comment by CitiesXL2815** [comment]
heads up don't click the button in creative for ender io crash report time for them lol, but thanks for fixing JEI Mezz love it

**Comment by robaimes** [comment]
Don't want to beat a dead horse, but even on the latest JEI (303), JEI appears in stacktraces. http://pastebin.com/fNspqk2h

Obviously we know this specific instance isn't a JEI issue, but still it appears!

**Comment by mezz** [comment]
This itemstack crashes if you touch it at all... I think I need to create an item like this for my testing setup.

**Comment by DatrixTHLK** [comment]
I didn't know this was still having issues. xD

**Comment by AEnterprise** [comment]
the item crashing when you touch it at all is normal if missing api dependencies are not handled properly, as soon as you touch it, java will realise it has imports of classes that don't exist and crash
