### ISSUE TITLE
Unknown ingredient type: class net.minecraft.item.ItemStack

### ISSUE THREAD

**Issue by DanNetwalker** [mezz/JustEnoughItems#518]
Crash on map load:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  StepupfixCore (StepupFix-1.10.2-1.0.0.2.jar)
  ShoulderPlugin (ShoulderSurfing-1.10.2-1.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.0.44-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 10/12/16 2:50 PM
Description: JEI failed to start:

java.lang.IllegalArgumentException: Unknown ingredient type: class net.minecraft.item.ItemStack
    at mezz.jei.IngredientRegistry.getIngredientHelper(IngredientRegistry.java:100)
    at mezz.jei.IngredientRegistry.<init>(IngredientRegistry.java:34)
    at mezz.jei.ModIngredientRegistration.createIngredientRegistry(ModIngredientRegistration.java:67)
    at mezz.jei.JeiStarter.registerIngredients(JeiStarter.java:94)
    at mezz.jei.JeiStarter.startJEI(JeiStarter.java:26)
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:128)
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:114)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_648_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraft.world.World.func_72838_d(World.java:1129)
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196)
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451)
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(SourceFile:45)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1623422680 bytes (1548 MB) / 3687317504 bytes (3516 MB) up to 5700583424 bytes (5436 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6115m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
    FML: MCP 9.32 Powered by Forge 12.18.2.2105 90 mods loaded, 90 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2105.jar) 
    UCHIJAAAA   Forge{12.18.2.2105} [Minecraft Forge] (forge-1.10.2-12.18.2.2105.jar) 
    UCHIJAAAA   Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   Baubles{1.3.BETA8} [Baubles] (Baubles-1.10.2-1.3.BETA8.jar) 
    UCHIJAAAA   Botania{r1.9-330} [Botania] (Botania r1.9-330.jar) 
    UCHIJAAAA   AkashicTome{1.0-4} [Akashic Tome] (AkashicTome-1.0-4.jar) 
    UCHIJAAAA   mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
    UCHIJAAAA   immersiveengineering{0.10-42} [Immersive Engineering] (ImmersiveEngineering-0.10-42.jar) 
    UCHIJAAAA   JEI{3.12.6.304} [Just Enough Items] (jei_1.10.2-3.12.6.304.jar) 
    UCHIJAAAA   appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
    UCHIJAAAA   Psi{r1.0-39} [Psi] (Psi-r1.0-39.jar) 
    UCHIJAAAA   Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
    UCHIJAAAA   AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
    UCHIJAAAA   mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
    UCHIJAAAA   bagelsmore{1.0.1} [Bagelsmore: The Return] (Bagelsmore-1.9.4-1.0.1.jar) 
    UCHIJAAAA   basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
    UCHIJAAAA   baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
    UCHIJAAAA   betterwithmods{0.12.3 Beta hotfix 1} [Better With Mods] (Better With Mods-0.12.3-1.10.2-hotfix1.jar) 
    UCHIJAAAA   BetterHorseHud{1.0} [Better Horse Hud] (BetterHorseHud-[1.9-1.10.2]-1.0.jar) 
    UCHIJAAAA   XaeroBetterPvP{1.10.6} [Better PVP Fair-Play Mod] (BetterPvPFairPlay_1.10.6_Forge_1.10.2.jar) 
    UCHIJAAAA   BiomesOPlenty{5.0.0.2087} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2087-universal.jar) 
    UCHIJAAAA   guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
    UCHIJAAAA   BloodMagic{1.9.4-2.1.0-65} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-65.jar) 
    UCHIJAAAA   brandonscore{2.1.0} [Brandon's Core] (BrandonsCore-1.10.2-2.1.0.44-universal.jar) 
    UCHIJAAAA   cavern{1.1.1} [Cavern] (Cavern_1.10-v1.1.1.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.1-1.10.2.jar) 
    UCHIJAAAA   chisel{MC1.9.4-0.0.6.46} [Chisel] (Chisel-MC1.9.4-0.0.6.46.jar) 
    UCHIJAAAA   claycraft{3.0} [Claycraft] (Claycraftmod v3.0 - MC1.10.2 Forge.jar) 
    UCHIJAAAA   cookingforblockheads{4.2.15} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.15.jar) 
    UCHIJAAAA   crossroads{1.10.2-1.1.6} [Crossroads] (crossroads-1.10.2-1.1.6.jar) 
    UCHIJAAAA   cyclopscore{0.7.7} [Cyclops Core] (CyclopsCore-1.9.4-0.7.7.jar) 
    UCHIJAAAA   dooglamoojuniorarchaeologymod{1.10.2-2.0} [Dooglamoo Jr. Archaeology Mod] (dooglamoojuniorarchaeologymod-1.10.2-2.0.jar) 
    UCHIJAAAA   draconicevolution{2.0.0} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.0.100-universal.jar) 
    UCHIJAAAA   enchiridion{3.1.11} [Enchiridion] (Enchiridion-1.10.2-3.1.11.jar) 
    UCHIJAAAA   evilcraft{0.10.11} [EvilCraft] (EvilCraft-1.10.2-0.10.11.jar) 
    UCHIJAAAA   exnihiloomnia{1.1.0} [Ex Nihilo Omnia] (exnihiloomnia-1.1.0.jar) 
    UCHIJAAAA   expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.9-1.10.2.jar) 
    UCHIJAAAA   extraalchemy{0.3.0.2-release} [Extra Alchemy] (extraalchemy-0.3.0.2-release.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.1.0c.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   ftbl{3.0.0} [FTBLib] (FTBLib-1.10.2-3.0.0.4.jar) 
    UCHIJAAAA   ftbu{3.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.0.0.3.jar) 
    UCHIJAAAA   fw{1.3.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.3.0b.jar) 
    UCHIJAAAA   shadowmc{3.4.5} [ShadowMC] (ShadowMC-1.10.2-3.4.5.jar) 
    UCHIJAAAA   Funnels{1.1.0} [Funnels] (Funnels-1.10.2-1.1.0.jar) 
    UCHIJAAAA   grapplemod{1.10-v7} [Grappling hook mod] (grapplemod-1.10.2-v7.jar) 
    UCHIJAAAA   gravestone{1.5.7} [Gravestone] (GraveStone Mod 1.5.7.jar) 
    UCHIJAAAA   helpfixer{1.0} [HelpFixer] (HelpFixer-1.10.2-1.4.15.jar) 
    UCHIJAAAA   hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
    UCHIJAAAA   ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
    UCHIJAAAA   jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
    UCHIJAAAA   login_shield{1.10.2-11-gb29eaad} [Login Shield] (Login_Shield-1.10.2-11-gb29eaad.jar) 
    UCHIJAAAA   malisiscore{1.9.4-4.1.1} [MalisisCore] (malisiscore-1.9.4-4.1.1.jar) 
    UCHIJAAAA   malisisdoors{1.9.4-5.0.4} [MalisisDoors] (malisisdoors-1.9.4-5.0.4.jar) 
    UCHIJAAAA   testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
    UCHIJAAAA   shetiphiancore{3.3.1} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.1.jar) 
    UCHIJAAAA   terraqueous{1.2.5} [Terraqueous] (terraqueous-1.10.0-1.2.5.jar) 
    UCHIJAAAA   multistorage{1.2.2} [Multi-Storage] (multistorage-1.10.0-1.2.2.jar) 
    UCHIJAAAA   hellbound{1.0} [HellBound] (NetherBound 1.0.jar) 
    UCHIJAAAA   netherbound{1.0} [NetherBound] (NetherBound 1.0.jar) 
    UCHIJAAAA   netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
    UCHIJAAAA   ninjagear{1.10.2-0.0.3} [NinjaGear] (ninjagear-0.0.3.jar) 
    UCHIJAAAA   recipehandler{0.5} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.5(1.10.2).jar) 
    UCHIJAAAA   fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
    UCHIJAAAA   orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
    UCHIJAAAA   harvestcraft{1.9.4-1.10.2e} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2e.jar) 
    UCHIJAAAA   progressiveautomation{1.6.51} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.51.jar) 
    UCHIJAAAA   ReAuth{3.2} [ReAuth] (ReAuth-3.2.jar) 
    UCHIJAAAA   redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
    UCHIJAAAA   xreliquary{1.10.2-1.3.3.568} [Reliquary] (Reliquary-1.10.2-1.3.3.568.jar) 
    UCHIJAAAA   rockhounding_chemistry{v1.00} [Rockhounding: Chemistry] (rockhounding_chemistry-1.10.2-v1.03.jar) 
    UCHIJAAAA   Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJAAAA   shouldersurfing{v1} [Shoulder Surfing] (ShoulderSurfing-1.10.2-1.1.jar) 
    UCHIJAAAA   flammpfeil.slashblade{mc1.9.4-r18} [SlashBlade] (SlashBlade-mc1.9.4-r18.jar) 
    UCHIJAAAA   stacksonstacks{1.1.4} [stacksonstacks] (StacksOnStacks2-1.1.4.jar) 
    UCHIJAAAA   terrainCrystals{1.1.0} [Terrain Crystals] (Terrain Crystals 1.1.0 - 1.10.2.jar) 
    UCHIJAAAA   terrainCrystalsAddons{1.0.2} [Terrain Crystals Addons] (Terrain Crystal Addons 1.0.2.jar) 
    UCHIJAAAA   torcharrowsmod{1.10.2-1} [TorchArrowsMod] (torcharrows-1.10.2-1.jar) 
    UCHIJAAAA   underphangables{1.0.2} [Underp Hangables] (underphangables-1.10.2-1.0.2.jar) 
    UCHIJAAAA   vc{v2.5.0a-mc1.10.2} [ViesCraft] (ViesCraft-2.5.0a-mc1.10.2.jar) 
    UCHIJAAAA   villagebox{0.5.0} [Village Box] (villagebox-1.10.2-0.5.0.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
    UCHIJAAAA   waterstrainer{1.3.0} [Water Strainer] (WaterStrainer-1.9.4-1.3.0.jar) 
    UCHIJAAAA   YeOldeTanks{1.8.0} [Ye Olde Tanks] (YeOldeTanks-1.10.2-1.8.0.jar) 
    UCHIJAAAA   fluidity{6.1.1} [Fluidity] (Fluidity-6.1.1.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  shetiphian.core.asm.ClassTransformer
StepupfixCore (StepupFix-1.10.2-1.0.0.2.jar)

ShoulderPlugin (ShoulderSurfing-1.10.2-1.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)

DepLoader (BrandonsCore-1.10.2-2.1.0.44-universal.jar)

CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 373.06' Renderer: 'GeForce GTX 960M/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - WailaIntegration (Enabled/Not Forced)
```

**Comment by mezz** [comment]
Thanks for the report!
This is caused by a crash earlier on, can you paste your client log to https://gist.github.com and link it here?

**Comment by AdithaD** [comment]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  IC2core (industrialcraft-2-2.6.86-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 10/15/16 9:53 AM
Description: JEI failed to start:

java.lang.IllegalArgumentException: Unknown ingredient type: class net.minecraft.item.ItemStack
    at mezz.jei.IngredientRegistry.getIngredientHelper(IngredientRegistry.java:100)
    at mezz.jei.IngredientRegistry.<init>(IngredientRegistry.java:34)
    at mezz.jei.ModIngredientRegistration.createIngredientRegistry(ModIngredientRegistration.java:67)
    at mezz.jei.JeiStarter.registerIngredients(JeiStarter.java:94)
    at mezz.jei.JeiStarter.startJEI(JeiStarter.java:26)
    at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:128)
    at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:114)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_275_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraft.world.World.func_72838_d(World.java:1129)
    at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:196)
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2451)
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2359)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:276)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
    at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(SourceFile:45)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1442423880 bytes (1375 MB) / 2542350336 bytes (2424 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.2.2099 27 mods loaded, 27 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2099.jar) 
    UCHIJA  Forge{12.18.2.2099} [Minecraft Forge] (forge-1.10.2-12.18.2.2099.jar) 
    UCHIJA  Baubles{1.3.BETA9} [Baubles] (Baubles-1.10.2-1.3.BETA9.jar) 
    UCHIJA  Botania{r1.9-330} [Botania] (Botania r1.9-330.jar) 
    UCHIJA  chiselsandbits{12.4} [Chisels & Bits] (chiselsandbits-12.4.jar) 
    UCHIJA  ElecCore{1.6.326} [ElecCore] (ElecCore-1.10.2-1.6.326.jar) 
    UCHIJA  deepresonance{1.2.9} [DeepResonance] (deepresonance-1.10-1.2.9.jar) 
    UCHIJA  endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
    UCHIJA  shetiphiancore{3.3.1} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.1.jar) 
    UCHIJA  endertanks{1.4.2} [EnderTanks] (endertanks-1.10.0-1.4.2.jar) 
    UCHIJA  EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
    UCHIJA  graves{1.10.2-b28-universal} [Graves Mod] (Graves-1.10.2-b28-universal.jar) 
    UCHIJA  mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
    UCHIJA  tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct] (TConstruct-1.10.2-2.5.5.jar) 
    UCHIJA  immersiveengineering{0.10-44} [Immersive Engineering] (ImmersiveEngineering-0.10-44.jar) 
    UCHIJA  IC2{2.6.86-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.86-ex110.jar) 
    UCHIJA  ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
    UCHIJA  JEI{3.12.7.312} [Just Enough Items] (jei_1.10.2-3.12.7.312.jar) 
    UCHIJA  natura{1.10.2-4.0.0.85} [Natura] (natura-1.10.2-4.0.0.85.jar) 
    UCHIJA  harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
    UCHIJA  rftools{5.53} [RFTools] (rftools-1.10-5.53.jar) 
    UCHIJA  shadowmc{3.4.8} [ShadowMC] (ShadowMC-1.10.2-3.4.8.jar) 
    UCHIJA  valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5d.jar) 
    UCHIJA  simplegenerators{1.10.2-0.10.4e} [Simple Generators] (simplegenerators-1.10.2-0.10.4e.jar) 
    UCHIJA  SleepingBag{1.3.0} [Sleeping Bag] (SleepingBag-1.10.2-1.3.0.jar) 
    UCHIJA  Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
    Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  shetiphian.core.asm.ClassTransformer
IC2core (industrialcraft-2-2.6.86-ex110.jar)

EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 7500/7600 Series'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

    Pulsar/natura loaded Pulses: 
        - NaturaCommons (Enabled/Forced)
        - NaturaOverworld (Enabled/Not Forced)
        - NaturaNether (Enabled/Not Forced)
        - NaturaEntities (Enabled/Not Forced)
        - NaturaOredict (Enabled/Forced)
        - NaturaWorld (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)
```

**Comment by mezz** [comment]
Thanks @indegame but I need more than a crash report.
This is caused by a crash earlier on, can you paste your client log to https://gist.github.com and link it here?

**Comment by AdithaD** [comment]
https://gist.github.com/indegame/80acc71f57b57f6da6c89ae40593f26a

I'm not sure if this is what you mean, but hopefully it is.

**Comment by mezz** [comment]
That's good, thanks. The full log is more useful, but what you included is good enough for this issue.

**Comment by mezz** [comment]
I created a new version that should help.
@indegame please try with [jei_1.10.2-3.12.7.320.jar](https://dvs1.progwml6.com/jenkins/job/JustEnoughItems/) and let me know if it works. If it still crashes, please include the crash log.
