### ISSUE TITLE
Crashing on Load

### ISSUE THREAD

**Issue by Gengi0927** [mezz/JustEnoughItems#520]
Hi, i have been having a problem with the JEI mod, Minecraft crashes before it gets to the title screen, i have pithe crashlog below, please help me fix this issue, thanks!

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.150-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.101-universal.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.3.2.82-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.5 (1).jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 10/12/16 10:20 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: bxl
    at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
    at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
    at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
    at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
    at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)

-- Screen render details --
Details:
    Screen name: net.minecraftforge.fml.client.GuiModsMissing
    Mouse location: Scaled: (252, 199). Absolute: (505, 81)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 234120912 bytes (223 MB) / 475910144 bytes (453 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.0.2003 16 mods loaded, 16 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    U   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    U   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2003-1.10.0.jar) 
    U   Forge{12.18.0.2003} [Minecraft Forge] (forge-1.10.2-12.18.0.2003-1.10.0.jar) 
    U   CodeChickenCore{2.3.2.82} [CodeChicken Core] (minecraft.jar) 
    U   NotEnoughItems{2.1.2.150} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.2.150-universal.jar) 
    U   chiselsandbits{12.4} [Chisels & Bits] (chiselsandbits-12.4.jar) 
    U   lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
    U   drpcore{0.1.6b} [Dark Roleplay Core] (drpcore-0.1.6b (1).jar) 
    U   drpmedieval{0.1.5} [Dark Roleplay Medieval] (drpmedieval-0.1.5.jar) 
    U   JEI{3.12.7.312} [Just Enough Items] (jei_1.10.2-3.12.7.312.jar) 
    U   malisiscore{1.10.2-4.2.5} [MalisisCore] (malisiscore-1.10.2-4.2.5 (1).jar) 
    U   malisisdoors{1.10.2-5.1.3} [MalisisDoors] (malisisdoors-1.10.2-5.1.3.jar) 
    U   mobends{0.22.5} [Mo'Bends] (mobends-0.22.5_for_MC-1.10.2.jar) 
    U   harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f (1).jar) 
    U   icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
    U   wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
    Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.150-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.101-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCCDeobfPlugin (unknown)

CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.3.2.82-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.2.5 (1).jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12422 Compatibility Profile Context 13.152.1.1000' Renderer: 'AMD Radeon HD 8400'
    Launched Version: 1.10.2-forge1.10.2-12.18.0.2003-1.10.0
    LWJGL: 2.9.4
    OpenGL: AMD Radeon HD 8400 GL version 4.2.12422 Compatibility Profile Context 13.152.1.1000, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: Default 3D Models V3.5.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x AMD A6-5200 APU with Radeon(TM) HD Graphics 
```

**Comment by mezz** [comment]
Thanks for the report!
Your crash is this: https://github.com/TheCBProject/NotEnoughItems/issues/22
It has been fixed in the latest NEI here http://chickenbones.net/Pages/links.html

**Comment by Gengi0927** [comment]
Thank you!

**Comment by Gengi0927** [comment]
I apologise, I download the mod you linked to me and the dependencies and the mod did not work, the same problem occured, if you need the this crashlog i will send it.

**Comment by mezz** [comment]
A crash log is always helpful if you crashed, please link it here.

**Comment by Gengi0927** [comment]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.150-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.101-universal.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.3.2.82-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.5 (1).jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 10/12/16 10:45 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: bxl
    at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
    at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
    at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
    at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
    at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:374)

-- Screen render details --
Details:
    Screen name: net.minecraftforge.fml.client.GuiModsMissing
    Mouse location: Scaled: (0, 239). Absolute: (0, 0)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 142038216 bytes (135 MB) / 432783360 bytes (412 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.0.2003 17 mods loaded, 17 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    U   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    U   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.0.2003-1.10.0.jar) 
    U   Forge{12.18.0.2003} [Minecraft Forge] (forge-1.10.2-12.18.0.2003-1.10.0.jar) 
    U   CodeChickenCore{2.3.2.82} [CodeChicken Core] (minecraft.jar) 
    U   NotEnoughItems{2.1.2.150} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.2.150-universal.jar) 
    U   AIC{1.5} [Anti Id Conflict] (AntiIdConflict-1.5-1.10.jar) 
    U   chiselsandbits{12.4} [Chisels & Bits] (chiselsandbits-12.4.jar) 
    U   lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
    U   drpcore{0.1.6b} [Dark Roleplay Core] (drpcore-0.1.6b (1).jar) 
    U   drpmedieval{0.1.5} [Dark Roleplay Medieval] (drpmedieval-0.1.5.jar) 
    U   JEI{3.12.7.312} [Just Enough Items] (jei_1.10.2-3.12.7.312.jar) 
    U   malisiscore{1.10.2-4.2.5} [MalisisCore] (malisiscore-1.10.2-4.2.5 (1).jar) 
    U   malisisdoors{1.10.2-5.1.3} [MalisisDoors] (malisisdoors-1.10.2-5.1.3.jar) 
    U   mobends{0.22.5} [Mo'Bends] (mobends-0.22.5_for_MC-1.10.2.jar) 
    U   harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2f (1).jar) 
    U   icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
    U   wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
    Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.10.2-2.1.2.150-universal.jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.101-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCCDeobfPlugin (unknown)

CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.3.2.82-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.2.5 (1).jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12422 Compatibility Profile Context 13.152.1.1000' Renderer: 'AMD Radeon HD 8400'
    Launched Version: 1.10.2-forge1.10.2-12.18.0.2003-1.10.0
    LWJGL: 2.9.4
    OpenGL: AMD Radeon HD 8400 GL version 4.2.12422 Compatibility Profile Context 13.152.1.1000, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: Default 3D Models V3.5.zip
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x AMD A6-5200 APU with Radeon(TM) HD Graphics 
```

**Comment by mezz** [comment]
It says you still have `NotEnoughItems-1.10.2-2.1.2.150` which is only the recommended version. The latest is `1.10.2-2.1.2.156` so please try updating the mod again.

**Comment by Gengi0927** [comment]
I apologize again, the mod i downloaded was on a different link, and i did not see the second set of links, the "latest" downloads, thank you for your help!

**Comment by mezz** [comment]
I just asked them to update their "recommended" version so it matches the latest. This shouldn't be a problem for much longer. Let me know if it fixed your crash.

**Comment by Gengi0927** [comment]
This did fix the crashing problem, it just says there is a newer version of the chickencore (Version 2.3.3), i should be able to fix this on my own, but if you want you can help! Thanks again!

**Comment by mezz** [comment]
The chickencore mod is available from the same page I linked with NEI, just check the buttons at the top.
Sounds like you should be fine, glad it worked out.

**Comment by Gengi0927** [comment]
Me too, Minecraft is working fine now, i just need to download the excore mod to allow chicken core to work, thanks! 👍 :)

**Comment by Gengi0927** [comment]
One last question, just enough items is requesting forge version 12.18.1.2053, i am currently on version 12.18.1.2011, How do i get version 12.18.1.2053 for forge?

**Comment by mezz** [comment]
Forge is here https://files.minecraftforge.net/

**Comment by Gengi0927** [comment]
I attempted the  download there, is there a specific link, or another way to get that version? ( I clicked Universal, under the Latest tab)

**Comment by mezz** [comment]
This is a nice video showing you How to Install Minecraft Forge
https://www.youtube.com/watch?v=lB3ArN_-3Oc

**Comment by Gengi0927** [comment]
THank you again, im surprised youve been this patient, most people would have given up by now! :)

**Comment by mezz** [comment]
You're welcome. I remember what it was like to do this when I was new.
