### ISSUE TITLE
Dirt screen

### ISSUE THREAD

**Issue by YOYOK9** [mezz/JustEnoughItems#531]
So when I try to connect to my Vanilla Lobby before connecting to the main server I get stuck on a dirt screen while loading in. I tested it with jei 325 and it worked but it doesn't with the 326.

Client log:
https://gist.github.com/YOYOK9/97f031170c6348802e727efe28975ce6

Ps: 326 mekanism crafting recipes work.

**Comment by mezz** [comment]
Thanks for the report!
Can you update your multimc to the dev version, and upload a new client log? The current stable multimc build does not show the mod's name on each line of the log, so it's hard to tell what mod is having errors.

**Comment by YOYOK9** [comment]
Client log with dev multimc and newest version of forge on both client and vinilla lobby. 
https://gist.github.com/YOYOK9/f2385479831f425018547c5f493f49ca

**Comment by mezz** [comment]
Hm looks like MultiMC broke their logging, I tested it myself and reported here: https://github.com/MultiMC/MultiMC5/issues/1692

It looks like some mod is seriously corrupting all your item stacks. Your game is not crashing, it is just taking forever to log all the errors. JEI 325 did not log all these errors, it would just crash and kill the plugin. JEI 326 has the correct behavior, but something is extremely broken with your pack.

My best guess is that it's a coremod problem.

```
[16:55:16] [main/INFO]: Adding new transformation for class com.mrdimka.simplequarry.tile.TilePoweredQuarry
[16:55:16] [main/ERROR]: A critical problem occurred registering the ASM transformer class 
java.lang.ClassNotFoundException: 
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_40]
    at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [launchwrapper-1.12.jar:?]
    at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:46) [forge-1.10.2-12.18.2.2107-universal.jar:?]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:191) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:252) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
    ... 14 more
```

Based on this part, try removing the mrdimka.simplequarry mod. If that does not fix the issue, try removing more mods until it is resolved.

**Comment by YOYOK9** [comment]
Alright Thank you, I will give this a shot. Would you like me to let you know of the results?

**Comment by mezz** [comment]
Yes, please keep me updated.

**Comment by YOYOK9** [comment]
Removed Simple quarry and still having the same issues. I will start removing other mods after my classes.

**Comment by AEnterprise** [comment]
try removing energyarsenal, i see in the log that items for that mod are being registered twice but not other items so there is atleast something broken in that mod

**Comment by YOYOK9** [comment]
Heres a log without the mods: Energy arsenal, Railcraft, Reborncore, Tech Reborn, TConstruct, taiga, Tesla, Tinkers io Tinkers addons.  I noticed a few jei errors in it this time (i think) 
https://gist.github.com/YOYOK9/3001d9b2a512be3ff30739dc5549ab86

**Comment by mezz** [comment]
You still have several coremods, I think you should try removing those:

```
aroma1997.core.coremod.CoreMod
lumien.bloodmoon.asm.LoadingPlugin
codechicken.core.launch.DepLoader
team.chisel.common.asm.ChiselCorePlugin
codechicken.lib.asm.CCLCorePlugin
lumien.hardcoredarkness.asm.LoadingPlugin
invtweaks.forge.asm.FMLPlugin
mekanism.common.launch.LoadingHook
optifine.OptiFineForgeTweaker
net.fybertech.nwr.NWRTweak
shetiphian.core.asm.TweakPlugin
```

**Comment by YOYOK9** [comment]
Ok after removing all the core mods was able to connect.
Heres the log if you want it:
https://gist.github.com/YOYOK9/a6e0c3df45b147f368c6e64c83947d7a

**Comment by mezz** [comment]
Great! You should try to figure out which coremod was causing the problem by adding some back, then we can report the issue to the correct place and make sure it gets fixed.

**Comment by YOYOK9** [comment]
Alright Will let you know what I figure out!

**Comment by YOYOK9** [comment]
After the long progress of adding mods back in it seems to "error" when Techreborn and its core (Reborncore) is in with all the other core mods. 

Thank you so much for your help with this.

**Comment by mezz** [comment]
Glad you figured it out!
Please report to them and link back to here. 
https://github.com/TechReborn/RebornCore/issues

**Comment by modmuss50** [comment]
We don't actually have a core mod (despite the name), Does it happen with just RebornCore? Or just RebornCore and TechReborn. Or does the issue arise when you add JEI with the other two?

**Comment by YOYOK9** [comment]
@modmuss50  I can connect to my lobby when either JEI + all other mods **OR** Techreborn/reborncor + all other mods. But If I do JEI and Tech Reborn + all others it errors out. 

Dont you need reborncore to run techrborn?
