### ISSUE TITLE
Cannot load save with jei_1.10.2-3.13.2.xxx but can load with jei_1.10.2-3.13.1.346

### ISSUE THREAD

**Issue by ircmaan** [mezz/JustEnoughItems#570]
Forge 2120 and 2116
----
Loading
Building terrain
(and nothing - still building terrain)

---
How it is possible? 
Thanx

**Comment by TheQuantumGeneral** [comment]
I think this is a conflict between Tinkers Construct and JEI.
Do you have Tinkers Construct?

**Comment by TheQuantumGeneral** [comment]
I think this is a conflict between Tinkers Construct and JEI.
Do you have Tinkers Construct?

**Comment by TheQuantumGeneral** [comment]
I think this is a conflict between Tinkers Construct and JEI.
Do you have Tinkers Construct?

**Comment by TheQuantumGeneral** [comment]
I think this is a conflict between Tinkers Construct and JEI.
Do you have Tinkers Construct?

**Comment by TheQuantumGeneral** [comment]
I think this is a conflict between Tinkers Construct and JEI.
Do you have Tinkers Construct?

**Comment by TheQuantumGeneral** [comment]
I think this is a conflict between Tinkers Construct and JEI.
Do you have Tinkers Construct?

**Comment by TheQuantumGeneral** [comment]
I think this is a conflict between Tinkers Construct and JEI.
Do you have Tinkers Construct?

**Comment by HarrisFauntleroy** [comment]
I think this is a conflict between Tinkers Construct and JEI.
Do you have Tinkers Construct?

**Comment by ircmaan** [comment]
Yes? I have TiC. I can remember in the log smth like "problem with Slimesword recipe, can not make ****wrapper"

**Comment by AEnterprise** [comment]
@ircmaan can you provide a gist of your log?

**Comment by ircmaan** [comment]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[10:53:52] [Server thread/ERROR] [JEI]: Found a broken recipe: slimeknights.tconstruct.tools.common.TableRecipe@7fafa3fa
Failed to create recipe wrapper

java.lang.NoSuchMethodError: mezz.jei.plugins.vanilla.crafting.ShapedOreRecipeWrapper.<init>(Lnet/minecraftforge/oredict/ShapedOreRecipe;)V
 at slimeknights.tconstruct.plugin.jei.TableRecipeWrapper.<init>(TableRecipeWrapper.java:22) ~[TableRecipeWrapper.class:?]
 at slimeknights.tconstruct.plugin.jei.TableRecipeHandler.getRecipeWrapper(TableRecipeHandler.java:33) ~[TableRecipeHandler.class:?]
 at slimeknights.tconstruct.plugin.jei.TableRecipeHandler.getRecipeWrapper(TableRecipeHandler.java:10) ~[TableRecipeHandler.class:?]
 at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:243) ~[RecipeRegistry.class:?]
 at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:218) [RecipeRegistry.class:?]
 at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:185) [RecipeRegistry.class:?]
 at mezz.jei.RecipeRegistry.addRecipes(RecipeRegistry.java:168) [RecipeRegistry.class:?]
 at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:94) [RecipeRegistry.class:?]
 at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:204) [ModRegistry.class:?]
 at mezz.jei.JeiStarter.start(JeiStarter.java:52) [JeiStarter.class:?]
 at mezz.jei.ProxyCommonClient.restartJEI(ProxyCommonClient.java:128) [ProxyCommonClient.class:?]
 at mezz.jei.JeiHelpers.reload(JeiHelpers.java:87) [JeiHelpers.class:?]
 at minetweaker.mods.jei.JEI$2.handle(JEI.java:69) [JEI$2.class:?]
 at minetweaker.mods.jei.JEI$2.handle(JEI.java:57) [JEI$2.class:?]
 at minetweaker.util.EventList.publish(EventList.java:55) [EventList.class:?]
 at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:688) [MineTweakerImplementationAPI.class:?]
 at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:591) [MineTweakerImplementationAPI.class:?]
 at minetweaker.mc1102.MineTweakerMod.onServerStarting(MineTweakerMod.java:186) [MineTweakerMod.class:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
 at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600) [FMLModContainer.class:?]
 at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
 at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
 at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) [LoadController.class:?]
 at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) [LoadController.class:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
 at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
 at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142) [LoadController.class:?]
 at net.minecraftforge.fml.common.Loader.serverStarting(Loader.java:845) [Loader.class:?]
 at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:292) [FMLCommonHandler.class:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
 at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
 at Reflector.callBoolean(Reflector.java:520) [Reflector.class:?]
 at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:205) [bzl.class:?]
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[10:53:52] [Server thread/ERROR] [JEI]: Found a broken recipe: slimeknights.tconstruct.tools.common.TableRecipe@77feb698
Failed to create recipe wrapper

java.lang.NoSuchMethodError: mezz.jei.plugins.vanilla.crafting.ShapedOreRecipeWrapper.<init>(Lnet/minecraftforge/oredict/ShapedOreRecipe;)V
 at slimeknights.tconstruct.plugin.jei.TableRecipeWrapper.<init>(TableRecipeWrapper.java:22) ~[TableRecipeWrapper.class:?]
 at slimeknights.tconstruct.plugin.jei.TableRecipeHandler.getRecipeWrapper(TableRecipeHandler.java:33) ~[TableRecipeHandler.class:?]
 at slimeknights.tconstruct.plugin.jei.TableRecipeHandler.getRecipeWrapper(TableRecipeHandler.java:10) ~[TableRecipeHandler.class:?]
 at mezz.jei.RecipeRegistry.addRecipeUnchecked(RecipeRegistry.java:243) ~[RecipeRegistry.class:?]
 at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:218) [RecipeRegistry.class:?]
 at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:185) [RecipeRegistry.class:?]
 at mezz.jei.RecipeRegistry.addRecipes(RecipeRegistry.java:168) [RecipeRegistry.class:?]
 at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:94) [RecipeRegistry.class:?]
 at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:204) [ModRegistry.class:?]
 at mezz.jei.JeiStarter.start(JeiStarter.java:52) [JeiStarter.class:?]
 at mezz.jei.ProxyCommonClient.restartJEI(ProxyCommonClient.java:128) [ProxyCommonClient.class:?]
 at mezz.jei.JeiHelpers.reload(JeiHelpers.java:87) [JeiHelpers.class:?]
 at minetweaker.mods.jei.JEI$2.handle(JEI.java:69) [JEI$2.class:?]
 at minetweaker.mods.jei.JEI$2.handle(JEI.java:57) [JEI$2.class:?]
 at minetweaker.util.EventList.publish(EventList.java:55) [EventList.class:?]
 at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:688) [MineTweakerImplementationAPI.class:?]
 at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:591) [MineTweakerImplementationAPI.class:?]
 at minetweaker.mc1102.MineTweakerMod.onServerStarting(MineTweakerMod.java:186) [MineTweakerMod.class:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
 at java.lang.reflect.Method.invoke(Method..

**Comment by TehNut** [comment]
Caused by Tinkers Construct

**Comment by mezz** [comment]
Thanks for the report!
Tinker's broken recipe wrappers should not crash the game. They are just being logged as errors.
Can you upload your entire client log to https://gist.github.com and link it here?

**Comment by ircmaan** [comment]
I have not a crash = I have not a log. For some minutes I will try get a log

**Comment by mezz** [comment]
The log I need is `fml-client-latest.log` in the `logs` folder of your minecraft directory. It should be there even if you haven't crashed.

**Comment by Tsukiumy** [comment]
just to add more info, seems likely that the issue is on minetweaker side, removed it and the problem stoped happening

**Comment by mezz** [comment]
Ok. I fixed the minetweaker issue here: https://github.com/mezz/JustEnoughItems/issues/572
The TiC problem shouldn't crash, but it will mean that their recipes are missing from JEI.

**Comment by ircmaan** [comment]
with jei_1.10.2-3.13.2.353.jar it is load my save! Thanx.
