### ISSUE TITLE
Server Crash with the new verison

### ISSUE THREAD

**Issue by EvilFG** [mezz/JustEnoughItems#586]
I have at my Server Forge Version 12.18.2.2121 but JEI want 12.18.1.2053. 
Why? 

[09:56:31] [Server thread/INFO]: Starting minecraft server version 1.10.2
[09:56:34] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.MissingModsException: Mod JEI (Just Enough Items) requires [Forge@[12.18.1.2053,)]
Missing Mods:
	Forge : [12.18.1.2053,)

	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:273) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:511) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[09:56:34] [Server thread/ERROR]: This crash report has been saved to: /games/ni232084_2/ftproot/minecraftotherpacks/./crash-reports/crash-2016-11-06_09.56.34-server.txt
[09:56:34] [Server thread/INFO]: Stopping server
[09:56:34] [Server thread/INFO]: Saving worlds

**Comment by mezz** [comment]
Thanks for the report!
I need some more information to solve this issue, please paste your full client log to https://gist.github.com and link it here.

**Comment by EvilFG** [comment]
i hope this is the right way. 

https://gist.github.com/EvilFG/51c711c219cc182d7f3ed9b9dc662ac3

**Comment by mezz** [comment]
It looks like you have `Forge{12.18.1.2011}`
You can see a short tutorial on installing Forge so you can be sure you didn't miss a step: 
https://www.youtube.com/watch?v=lB3ArN_-3Oc

**Comment by EvilFG** [comment]
oh my fault sry and thx
