### ISSUE TITLE
Botania, JEI and Crafting Station crash

### ISSUE THREAD

**Issue by LepkoQQ** [mezz/JustEnoughItems#615]
My crafting station was placed beside the petal apothecary from Botania and it recognized the internal slots as a chest in the GUI.

Since I couldn't click to insert or take items from the slots I just assumed it was fine since it respected the isValidItem/canTake methods on those slots.

But then I tried to click the plus sign on a recipe in JEI and since the crafring station wasnt empty it tried to move the items in to the slots of the petal apothecary and since those items should never be in there it crashed the game.

Hopefully a not too confusing screenshot:
![2016-11-16_01 21 05](https://cloud.githubusercontent.com/assets/2662937/20330050/63814c76-ab9c-11e6-8a4b-3036f69ca4cc.png)

Now afaik JEI is at fault but I reported it in all three repos:
https://github.com/SlimeKnights/TinkersConstruct/issues/2570
https://github.com/mezz/JustEnoughItems/issues/615
https://github.com/Vazkii/Botania/issues/2036

```
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.ClassCastException: net.minecraft.item.Item cannot be cast to vazkii.botania.api.recipe.IFlowerComponent
	at vazkii.botania.common.block.tile.TileAltar.func_73660_a(TileAltar.java:263) ~[TileAltar.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
```

Relevant versions:
- Forge{12.18.2.2125} [Minecraft Forge] (forge-1.10.2-12.18.2.2125.jar) 
- mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
- tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
- JEI{3.13.3.372} [Just Enough Items] (jei_1.10.2-3.13.3.372.jar) 
- Botania{r1.9-337} [Botania] (Botania r1.9-337.jar)

**Comment by mezz** [comment]
Thanks for the report!
I'd say this is just a TiC bug. 
1. They add the [+] integration for the Crafting Station to JEI, it should move items to the right slots.
2. They handle interfacing with nearby inventories like the petal apothecary. I assume they correctly handle the petal apothecary in most cases, but the bug in 1 bypasses their normal checks.
