### ISSUE TITLE
JustEnoughItemsAPI loaded from an incompatible classloader

### ISSUE THREAD

**Issue by Choonster** [mezz/JustEnoughItems#627]
I've added the JEI API as a `deobfCompile` dependency and JEI itself as a `runtime` dependency, but when I run Minecraft I receive this error in the log:

```
[14:42:53] [Client thread/WARN] [FML/]: ****************************************
[14:42:53] [Client thread/WARN] [FML/]: * The API JustEnoughItemsAPI from source C:\Users\USER\.gradle\caches\minecraft\deobfedDeps\deobf\mezz\jei\jei_1.10.2\3.13.3.373\jei_1.10.2-3.13.3.373.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:113)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:173)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:231)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:522)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraft.client.Minecraft.startGame(Minecraft.java:477)...
[14:42:53] [Client thread/WARN] [FML/]: ****************************************
```

Despite the strong wording, JEI and other mods that use the API (e.g. Blood Magic) seem to work.

[Full Logs](https://gist.github.com/Choonster/3779faa6c71d29a411b25e5cc60f1bea)
[build.gradle](https://github.com/Choonster/JEITestMod/blob/ffad309529961640afbeef456265e25e73e361d7/build.gradle)

**Comment by mezz** [comment]
Thanks for the report!
I think FML is warning here because there are 2 JEI APIs being loaded at runtime.
The message is not very clear.
I'll get confirmation from cpw to see if there is a way around the warning, or if the warning can be improved.

In any case you can safely ignore it, nothing bad is happening.

**Comment by mezz** [comment]
This check is to detect APIs that are being loaded from coremods (bad).
It just happens to catch APIs that are loaded separately in dev environments.
You can submit a bug report to Forge to see if this can be fixed, but it can be safely ignored.
