### ISSUE TITLE
JEI does not work with Uncomplication

### ISSUE THREAD

**Issue by InsaneJ** [mezz/JustEnoughItems#632]
When using:
* Forge 12.18.2.2139
* Uncomplication-1.10.2-0.2.0.2
* jei_1.10.2-3.13.3.373 (or jei_1.10.2-3.13.3.373)
the JEI icon overlay is no longer visible inside a player's inventory screen. JEI recipe lookup and item usage also no longer works.

Here's a client log:
http://paste2.org/Is75xekH

Crossposted here since I do not know if this is a JEI or an Uncomplication issue:
https://bitbucket.org/Aroma1997/uncomplication/issues/23/jei-does-not-work-with-uncomplication-1102

**Comment by mezz** [comment]
Thanks for the report!
This is an Uncomplication issue but I can protect against it in JEI for now.

**Comment by mezz** [comment]
For your report: their `isRecipeValid` crashes:

```
[09:32:50] [Client thread/ERROR]: Exception on load
java.lang.NullPointerException
    at aroma1997.uncomplication.plugin.nei.UncomplicationRecipeWrapper.getInputs(UncomplicationRecipeWrapper.java:41) ~[UncomplicationRecipeWrapper.class:?]
    at aroma1997.uncomplication.plugin.nei.UncomplicationOverrideHandler.isRecipeValid(UncomplicationOverrideHandler.java:53) ~[UncomplicationOverrideHandler.class:?]
    at aroma1997.uncomplication.plugin.nei.UncomplicationOverrideHandler.isRecipeValid(UncomplicationOverrideHandler.java:20) ~[UncomplicationOverrideHandler.class:?]
    at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:213) ~[RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.addRecipe(RecipeRegistry.java:185) ~[RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.addRecipes(RecipeRegistry.java:168) ~[RecipeRegistry.class:?]
    at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:94) ~[RecipeRegistry.class:?]
    at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:204) ~[ModRegistry.class:?]
    at mezz.jei.JeiStarter.start(JeiStarter.java:52) ~[JeiStarter.class:?]
    at mezz.jei.ProxyCommonClient.loadComplete(ProxyCommonClient.java:111) [ProxyCommonClient.class:?]
    at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:53) [JustEnoughItems.class:?]
```

**Comment by mezz** [comment]
Should log an error instead of crashing in JEI 3.13.3.381
