### ISSUE TITLE
JEI + CraftTweaker crash when viewing Smelting tab in recipe view

### ISSUE THREAD

**Issue by Vampsku11** [mezz/JustEnoughItems#681]
Version: forge1.10.2-12.18.3.2185

Only mods in /mods/1/10/2
CraftTweaker-1.10.2-3.0.16.jar
jei_1.10.2-3.13.6.393.jar

Start game (creative, default world type, bonus chest)
E to open inventory
search for coal
view coal recipes
click on Smelting tab in recipe view

Crash text:
```
[20:41:00] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1121) ~[bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.crafting.FurnaceRecipes.func_151397_a(FurnaceRecipes.java:98) ~[afz.class:?]
	at net.minecraft.item.crafting.FurnaceRecipes.func_151398_b(FurnaceRecipes.java:113) ~[afz.class:?]
	at mezz.jei.plugins.vanilla.furnace.SmeltingRecipe.drawInfo(SmeltingRecipe.java:41) ~[SmeltingRecipe.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:120) ~[RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:202) ~[RecipesGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) ~[bnz.class:?]
	... 9 more
```

**Comment by mezz** [comment]
Thanks for the report!
Sorry @Bufhimat this one fell through the cracks. Does it still occur on the latest versions of JEI and Crafttweaker? I have worked with Jared on smelting recipe integration since you reported this.

**Comment by mezz** [comment]
This is most likely fixed, closing.
