### ISSUE TITLE
Crash when searching

### ISSUE THREAD

**Issue by JunkiEDM** [mezz/JustEnoughItems#682]
Whenever I try to type anything in the search bar my game crashes: https://gist.github.com/100photos/e797635a7192e321726b872a4b07e5b4
 Mods:
```
AbyssalCraft-1.10.2-1.9.3.9.jar
ActuallyAdditions-1.10.2-r94.jar
AdvancedRocketry-1.10.2-1.0.4b.jar
agricraft-2.0.0-0.4.0-a5.jar
AgriculturalExpansion[1.9.4][1.10.2]-r1.2.2.jar
AntiIdConflict-1.5-1.10.jar.disabled
AppleCore-mc1.10.2-2.1.0.jar
AppleSkin-mc1.10.2-1.0.4.jar
appliedenergistics2-rv4-alpha-9.jar
armoroverlay-3.2a.jar
Aroma1997Core-1.9.4-1.1.1.1.jar
Aroma1997s-Dimensional-World-1.9.4-1.2.0.4.jar
AromaBackup-1.9.4-1.0.1.1.jar
autopackager-1.6.3.jar
AutoRegLib-1.0-2.jar
Bagginses-1.10.2-3.0.4g.jar
BattleTowers-1.10.2.zip
Baubles-1.10.2-1.3.8.jar
baublesstuff-3.0.2.jar
BBG-1.9.4-5.0.0.jar
bdlib-1.12.2.17-mc1.10.2.jar
BetterAchievements-1.10.2-0.3.2.39.jar
BetterBuildersWands-1.10.2-0.9.3.187+c619800.jar
BetterFps-1.3.2.jar
BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar
BloodMagic-1.9.4-2.1.0-69.jar
Bloodmoon-MC1.10.2-1.5.1.jar
Bookshelf-1.10.2-1.4.3.338.jar
BrandonsCore-1.10.2-2.1.2.76-universal.jar
CanIJoinNow-1.10-1.0-4.jar
Capsule-1.10.2-1.2.0.jar
ChanceCubes-1.10.2-2.3.3.135.jar
Charset-mc1.10.2-0.3.3-fc63183d1db778a2.jar
ChestTransporter-1.10.2-2.5.6.jar
ChickenChunks-1.10.2-2.2.0.52-universal.jar
Chisel-MC1.10.2-0.0.7.7.jar
chiselsandbits-12.9.jar
ChiselsBytes-1.9.4-0.4.jar
CodeChickenCore-1.10.2-2.4.0.100-universal.jar
CodeChickenLib-1.10.2-2.5.0.178-universal.jar
CommonCapabilities-1.9.4-1.2.1.jar
compatlayer-1.10-0.1.6.jar
Correlated-2.0.0-alpha3.jar
CustomMobSpawner 3.10.1.jar
cyberware-1.9.4-1.10.2-beta-0.2.6.jar
Cyclic-1.10.2-1.9.9.jar
CyclopsCore-1.9.4-0.8.2.jar
DarkUtilities-1.10.2-1.1.6.103.jar
davincisvessels-1.10.2-0006-full.jar
Decocraft-2.3.6.1_1.10.2.jar
deepresonance-1.1x-1.4.2.jar
Ding-1.10.2-1.0.1.jar
DoomlikeDungeons-1.8.13-MC1.10.jar
Draconic-Evolution-1.10.2-2.0.4.142-universal.jar
DragonTweaks-1.10.2-1.0.0.1-universal.jar
DrZhark's Mo'Creatures Mod-10.0.6.jar
DynamicSurroundings-1.10.2-3.1.3.0BETA.jar
ElecCore-1.10.2-1.6.360.jar
ElevatorMod[V.1.3.0][MC.1.10.2].jar
EnchantingPlus-1.10.2-4.1.0.115.jar
Enchiridion-1.10.2-3.1.14.jar
EnderCore-1.10.2-0.4.1.61-beta.jar
EnderIO-1.10.2-3.0.1.148_beta.jar
endertanks-1.10.0-1.4.9.jar
enderthing-1.10.2-0.7.1.jar
EnderZoo-1.10-1.2.3.43.jar
EnergySynergy-1.10.2-1.1.0.jar
environmentaltech-1.10.2-0.10.5h.jar
EverlastingAbilities-1.9.4-1.2.3.jar
Excore-1.6.2-1.10.2.jar
extrautils2-1.10.2-1.1.3a.jar
ExtremeReactors-1.10.2-0.4.5.22.jar
FastAsyncWorldEdit-forge110-16.11.25-951a6a8-380-9.12.4.jar
FastLeaveDecay-MC1.10.2-1.2.3.jar
FluxNetworks-1.10.2-1.0.8.jar
foamfix-0.4.2-law.jar
FTBLib-1.10.2-3.2.3.jar
FTBUtilities-1.10.2-3.2.4.jar_temp
generators-0.9.20.18-mc1.10.2.jar
GiacomosFishingNet1.10.2-1.4.4.jar
GlobalGameRules-1.10.2-2.0.jar
GraveStone Mod 1.5.10.jar
griefprevention-1.10.2-2.2.0.173.jar
Guide-API-1.10.2-2.0.2-45.jar
HelpFixer-1.10.2-1.4.15.jar
helpme-5.0.0-0.2.2.jar
iChunUtil-1.10.2-6.1.0.jar
ImmersiveEngineering-0.10-54.jar
industrialcraft-2-2.6.128-ex110.jar
infinitylib-0.4.0.jar
IntegratedDynamics-1.10.2-0.6.5.jar
InventoryTweaks-1.61-58.jar
ironchest-1.10.2-7.0.11.797.jar
IvToolkit-1.2.9.jar
jei_1.10.2-3.13.6.393.jar
journeymap-1.10.2-5.3.2.jar
JustEnoughResources-1.10.2-0.5.8.98.jar
KeepingInventory-1.10.2-2.1.jar
Keys-1.2.1-1-g46a0267.jar
KleeSlabs_1.10.2-3.3.5.jar
Levels-1.10.2-r4.1.3.jar.disabled
LibVulpes-1.10.2-0.1.12-universal.jar
limelib-1.10.2-1.3.5.jar
Login_Shield-1.10.2-19-gd16e7e0.jar
LootBags-1.10.2-2.3.0.jar
Mantle-1.10.2-1.1.3.jar
mcjtylib-1.1x-2.3.1.jar
Mekanism-1.10.2-9.2.1.295.jar
MekanismGenerators-1.10.2-9.2.1.295.jar
MekanismTools-1.10.2-9.2.1.295.jar
MenuMobs-1.10.2-1.14.jar
MineMenu-1.10.X-1.4.4.B9-universal.jar
MineTunes 1.2-9.jar
ModPatcher.jlib
Morph-o-Tool-1.0-12.jar
Morpheus-1.10.2-3.1.13.jar
movingworld-1.10.2-0006-full.jar
mp3spi-1.9.5-1.jar
multistorage-1.10.0-1.2.12.jar
NotEnoughCodecs-0.5.jar
notenoughwands-1.1x-1.5.3.jar
Nucleus-0.15.0-S5-1.10.2-plugin.jar
omlib-1.10.2-3.0.0-37.jar
OpenComputers-MC1.10.2-1.6.1.6.jar
OpenEye-1.10.2-0.8.jar
OpenFM-1.9.4-0.1.0.18.jar
openmodularturrets-1.10.2-3.0.0-42.jar
OreExcavation-1.2.78.jar
Pam's HarvestCraft 1.9.4-1.10.2h.jar
permissionManager-2.5.1-API-5.X-6.X.jar
PiP-1.10.2-6.0.0.jar
PlaceableGunpowder-1.1_1.9.4.jar
Prism-3.0.0-beta2-21-gdae772d.jar
Psi-r1.0-42.jar
quantumflux-1.10.2-2.0.11.jar
QuantumStorage-1.10.2-3.2.16.jar
Quark-r1.1-68.jar
RandomThings-MC1.10.2-3.7.7.jar
ReAuth-3.3.jar
RebornCore-1.10.2-2.8.5.79-universal.jar
RecurrentComplex-1.2.4.jar
redstonepaste-mc1.9.4-1.7.4.jar
refinedstorage-1.2.14.jar
Reliquary-1.10.2-1.3.3.615.jar
RemoteIO-0.0.5-universal.jar
rftools-1.1x-5.75.jar
rftoolsctrl-1.1x-1.6.3.jar
RoguelikeDungeons-1.10.2-1.5.4.jar
Ruins-1.10.2.zip
sampler-1.66.jar
shetiphiancore-1.10.0-3.3.6.jar
SimplyConveyors-1.3.0.jar
SimplyJetpacks2-1.10.2-2.0.3.26.jar
SonarCore-1.10.2-3.1.8.jar
SophisticatedWolves-3.6.3.jar
SpartanShields-1.10.2-1.1c.jar
spongeforge-1.10.2-2171-5.1.0-BETA-2010.jar
storagenetwork-2.0.9.jar
TConstruct-1.10.2-2.6.1.jar
Tesla-1.10.2-1.2.1.49.jar
TeslaArsenal-1.4.jar
teslacoils-0.2.3.0.jar
teslafied-1.10.2-1.1.0.jar
theoneprobe-1.10-1.3.3.jar
TickProfiler-1.10.2.jenkins.10.jar
TinkerToolLeveling-1.10.2-1.0.1.jar
tinker_io-1.10.2-release 2.4.1.jar
topaddons-1.10.2-0.9.0.jar
Torcherino-4.2s.jar
TrashSlot_1.10.2-6.3.7.jar
TreeGrowingSimulator2016-0.0.4.jar
UniDict-1.10.2-2.4.jar
Updatifier-v1.4.0-r4.1.0.jar
valkyrielib-1.10.2-0.10.5e.jar
vorbisspi-1.0.3-1.jar
WanionLib-1.10.2-1.2.jar
Wawla-1.10.2-2.3.1.213.jar
weaponcaseloot-1.10.2-4.0.1.jar
WIRED-1.5.0.jar
worldedit-forge-mc1.10.2-6.1.4-dist.jar
WorldEditCuiFe-v1.0.6-mf-1.10.2-12.18.2.2125.jar
xLib-1.10-r2.0.1.jar
zerocore-1.10.2-0.0.8.2.jar

```

**Comment by mezz** [comment]
Thanks for the report!
Try updating or removing Optifine and report back.

**Comment by JunkiEDM** [comment]
It still happens, but instead of happening when I search, it happens when I go to page 3... (At least I think its that page)

**Comment by mezz** [comment]
Can you post the new crash report?

**Comment by JunkiEDM** [comment]
https://gist.github.com/100photos/ae362637ca0435c3dae13cdbb405d60d

**Comment by JunkiEDM** [comment]
That's odd... the crash only happens if i'm coming from page 5+, it doesnt happen if I go forward from page 1 or 2, or backwards from 4, but if I go back twice from page 5 it crashes

**Comment by JunkiEDM** [comment]
I realize this is probably another mod's fault, especially since this was at the top of the error log: 
<details>
<summary> Log </summary>
<p>
<div class="highlight">
<pre>
[14:24:11] [Client thread/ERROR]: Rendering ingredient crashed: 1xitem.agricraft:agri_nugget@0 agricraft:agri_nugget
java.lang.RuntimeException: ALREADY CONSTRUCTING VERTICES
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.startDrawing(TessellatorBakedQuad.java:79) ~[TessellatorBakedQuad.class:?]
	at com.infinityraider.infinitylib.render.tessellation.TessellatorBakedQuad.onStartDrawingQuadsCall(TessellatorBakedQuad.java:68) ~[TessellatorBakedQuad.class:?]
	at com.infinityraider.infinitylib.render.tessellation.TessellatorAbstractBase.startDrawingQuads(TessellatorAbstractBase.java:88) ~[TessellatorAbstractBase.class:?]
	at com.infinityraider.infinitylib.render.item.BakedInfItemModel.func_188616_a(BakedInfItemModel.java:54) ~[BakedInfItemModel.class:?]
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:128) ~[bsu.class:?]
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112) ~[bsu.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:120) [GuiIngredientFast.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:93) [GuiIngredientFast.class:?]
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:156) [GuiIngredientFastList.class:?]
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305) [ItemListOverlayInternal.class:?]
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:88) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1552_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590) [bft.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73) [bgl.class:?]
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51) [bgw.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [bhc.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
</pre>
</div>
</p>
</details>

**Comment by JunkiEDM** [comment]
It does it for more agricraft stuff too

**Comment by mezz** [comment]
Try disabling JEI and looking in the creative menu, maybe it's just an issue with those items.

**Comment by grydian** [comment]
Fyi I also have been getting this crash and I removed agricraft and now I can search water and it not crash.  So it's definitely something with that mod.

**Comment by mezz** [comment]
Ok. Please report to AgriCraft here so they can fix the bug:  
https://github.com/InfinityRaider/AgriCraft/issues
