### ISSUE TITLE
[1.10.2] Item Recipe Crash - IndexOutOfBoundsException

### ISSUE THREAD

**Issue by everseeking** [mezz/JustEnoughItems#686]
#### Setup
* Sky Factory 3 - `3.0.1` (latest)
* Removed NEI addon
* Updated JEI to latest - `jei_1.10.2-3.14.2.398`

#### Crash
[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0](https://gist.github.com/everseeking/6dcee48f6589ce20fd14d8462c667f30)

#### How to Duplicate
* Clicked on "Crafting Table on a Stick" from Actually Additions
* [Example](http://i.imgur.com/S2J3Azd.gifv)

#### Notes
* Both fullscreen and windowed settings produced crash
* NEI included still crashed
* Tried to remove Foamfix but after allocating 7.5 GB and still getting OutofMemory, I gave up
* Noticed very similar issues in the tracker with EnderIO, and being their fault. Maybe this is Actually Additions but for some reason doesn't get caught in the error stack?

**Comment by mezz** [comment]
Thanks for the report!
I think I fixed this just today, a few hours ago. Please try the very latest version.
edit: never mind I didn't update the 1.10 branch, I'll do that now.

**Comment by mezz** [comment]
Please try with JEI `3.14.2.401` once it's available in a few minutes, it should fix this issue.

**Comment by everseeking** [comment]
* Updated to `jei_1.10.2-3.14.2.401.jar`
* Crash has stopped but [no recipe is showing](http://i.imgur.com/PrdTia3.gifv)

I have no idea if JEI is to blame now for the missing recipe or if something in the modpack has actually been trying to hide it all this time.

#### Notes
* After adding the NEI jar back to the modpack (while sticking to JEI itempanel/search), same outcome as above
* When enabling NEI itempanel/search, [the recipe now shows](http://i.imgur.com/Zo3P0wL.gifv).

**Comment by mezz** [comment]
The remaining bug is from moar signs:
```
[Client thread/ERROR] [JEI]: Error caught from Recipe Category: mezz.jei.plugins.vanilla.crafting.CraftingRecipeCategory
java.lang.ClassCastException: gory_moon.moarsigns.integration.jei.crafting.MoarSignsRecipeWrapper cannot be cast to mezz.jei.api.recipe.wrapper.ICraftingRecipeWrapper
	at mezz.jei.plugins.vanilla.crafting.CraftingRecipeCategory.setRecipe(CraftingRecipeCategory.java:20) ~[CraftingRecipeCategory.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.<init>(RecipeLayout.java:78) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipeGuiLogic.getRecipeLayouts(RecipeGuiLogic.java:217) [RecipeGuiLogic.class:?]
	at mezz.jei.gui.recipes.RecipesGui.updateLayout(RecipesGui.java:433) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.func_73866_w_(RecipesGui.java:156) [RecipesGui.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:495) [bft.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:965) [bcx.class:?]
	at mezz.jei.gui.recipes.RecipesGui.open(RecipesGui.java:316) [RecipesGui.class:?]
	at mezz.jei.gui.recipes.RecipesGui.show(RecipesGui.java:339) [RecipesGui.class:?]
	at mezz.jei.input.InputHandler.handleMouseClickedFocus(InputHandler.java:147) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseClick(InputHandler.java:83) [InputHandler.class:?]
	at mezz.jei.input.InputHandler.handleMouseEvent(InputHandler.java:60) [InputHandler.class:?]
	at mezz.jei.GuiEventHandler.onGuiMouseEvent(GuiEventHandler.java:140) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1238_GuiEventHandler_onGuiMouseEvent_Pre.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:516) [bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
