### ISSUE TITLE
Minecraft won't log (Crash)

### ISSUE THREAD

**Issue by QueenAmessia** [mezz/JustEnoughItems#693]
So I have the PureBDcraft texture pack installed and it worked just fine, but then I installed JEI and it was all good for a while, and then suddenly it started crashing a little so i quitted the game and then tried to play minecraft but it just crashed with the Mojang thing from the beginning when I tried to log in. Are they not compatible or something? This happened ones and I had to re install everything (including minecraft) which took me hours, and I thought that maybe it was another thing that lagged the game, but now I guess not. I would really appreciate not to do all these again (it was a very frustrating thing to do).
~I have the version 1.11  of minecraft and I'm using a MacBook. I only have JEI and PureBDcraft installed.

---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 1/8/17 9:39 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at net.minecraftforge.common.model.TRSRTransformation.mul(TRSRTransformation.java:265)
	at net.minecraftforge.common.model.TRSRTransformation.<init>(TRSRTransformation.java:83)
	at net.minecraftforge.common.model.TRSRTransformation.<init>(TRSRTransformation.java:95)
	at net.minecraftforge.client.model.IPerspectiveAwareModel$MapWrapper.getTransforms(IPerspectiveAwareModel.java:90)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:532)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:804)
	at net.minecraftforge.client.model.ModelLoader$MultipartModel.bake(ModelLoader.java:1243)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:347)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.common.model.TRSRTransformation.mul(TRSRTransformation.java:265)
	at net.minecraftforge.common.model.TRSRTransformation.<init>(TRSRTransformation.java:83)
	at net.minecraftforge.common.model.TRSRTransformation.<init>(TRSRTransformation.java:95)
	at net.minecraftforge.client.model.IPerspectiveAwareModel$MapWrapper.getTransforms(IPerspectiveAwareModel.java:90)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:532)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:804)
	at net.minecraftforge.client.model.ModelLoader$MultipartModel.bake(ModelLoader.java:1243)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:182)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:347)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:519)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:350)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11
	Operating System: Mac OS X (x86_64) version 10.11.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 384694392 bytes (366 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.35 Powered by Forge 13.19.1.2189 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11-13.19.1.2189.jar) 
	UCHIJA	forge{13.19.1.2189} [Minecraft Forge] (forge-1.11-13.19.1.2189.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJA	jei{4.0.5.201} [Just Enough Items] (jei_1.11-4.0.5.201.jar) 
	Loaded coremods (and transformers): 
	Launched Version: 1.11-forge1.11-13.19.1.2189
	LWJGL: 2.9.2
	OpenGL: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-10.14.73, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: PureBDcraft 128x MC111
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz

**Comment by TehNut** [comment]
You are running out of memory. Increase the amount you have allocated

**Comment by mezz** [comment]
Forge + JEI will take some more memory than Vanilla Minecraft alone.
Make sure you set your max memory higher, the log shows 1GB (`-Xmx1G`). You should try 2G.
