### ISSUE TITLE
Game crashes when any user interface screen is opened.

### ISSUE THREAD

**Issue by Zarepheth** [mezz/JustEnoughItems#707]
Over the past few days, I've been receiving a ton of these errors. They occur when I attempt to open my inventory, or the UI for Everlasting Abilities, or a chest, or the UI for another mod's item. After much trial and error (removing and reloading the game and the world) I found that removing Just Enough Items (JEI) fixed the crashing problem.

- Minecraft 1.11.2
- Forge 13.20.0.2224
- JEI 4.2.3.223+

Thinking back on it a bit, there might be a problem with one of my mods. I had the JEI list filtered to a specific mod's items for a while - long enough to close down the game, add/update mods, and reload the game. The first of these crashes occurred when I cleared the filter. Ever since, the game crashes whenever I attempt to open any the UI for any mod's device. I have no idea which mod might have the problem - I removed all mods add or updated with the past few days and not until JEI was removed did the crashes stop. Restoring all the other mods to the game, but leaving out JEI also allowed the game to work without crashing.

[Full crash log Gist](https://gist.github.com/Zarepheth/d412bb875b5c2ee255b18d5642dc8ff3.js)

Stack Trace:

```
java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:291)
	at net.minecraft.client.shader.Framebuffer.func_178038_a(Framebuffer.java:264)
	at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:229)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1104)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by mezz** [comment]
Thanks for the report!
This looks to be the same as https://github.com/mezz/JustEnoughItems/issues/706

>This is not actually from JEI, it is from an item rendering.
It could be from any mod but Optifine has cause an issue like this in the past, try removing it.

Please follow up on the other issue I linked (I want to keep responses in the same place).
