### ISSUE TITLE
1.11 Error with Anvil Recipes

### ISSUE THREAD

**Issue by kitsushadow** [mezz/JustEnoughItems#783]
## Error 1
When players left click my tools in the JEI menu they get this error

===

-- Head --
Thread: Client thread
Stacktrace:
	at nmd.primal.forgecraft.ToolNBT.getHot(ToolNBT.java:14)
	at nmd.primal.forgecraft.items.tools.CustomAxe$1.apply(CustomAxe.java:51)
	at net.minecraft.client.renderer.block.model.ItemOverride.matchesItemStack(ItemOverride.java:51)
	at net.minecraft.client.renderer.block.model.ItemOverrideList.applyOverride(ItemOverrideList.java:39)
	at net.minecraft.client.renderer.block.model.ItemOverrideList.handleItemState(ItemOverrideList.java:53)
	at net.minecraftforge.client.model.animation.AnimationItemOverrideList.handleItemState(AnimationItemOverrideList.java:85)
	at net.minecraft.client.renderer.RenderItem.getItemModelWithOverrides(RenderItem.java:253)

-- Item being rendered --
Details:
	Item Type: nmd.primal.forgecraft.items.tools.CustomAxe@3b181488
	Item Aux: 0
	Item NBT: {ench:[0:{lvl:1s,id:16s}]}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:355)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:26)
	at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:20)
	at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:126)
	at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:163)
	at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:141)
	at mezz.jei.gui.recipes.RecipesGui.drawScreen(RecipesGui.java:212)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: mezz.jei.gui.recipes.RecipesGui
	Mouse location: Scaled: (358, 129). Absolute: (716, 220)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

===

## Error 2
When player tries to view the anvil recipes for my tools

===

-- Head --
Thread: Client thread
Stacktrace:
    at nmd.primal.forgecraft.ToolNBT.getHot(ToolNBT.java:13)
    at nmd.primal.forgecraft.items.tools.CustomPickaxe$1.func_185085_a(CustomPickaxe.java:58)
    at net.minecraft.client.renderer.block.model.ItemOverride.func_188027_a(SourceFile:39)
    at net.minecraft.client.renderer.block.model.ItemOverrideList.func_188021_a(ItemOverrideList.java:39)
    at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:358)

-- Item being rendered --
Details:
    Item Type: nmd.primal.forgecraft.items.tools.CustomPickaxe@7c94b411
    Item Aux: 0
    Item NBT: {ench:[0:{lvl:4s,id:32s}]}
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:513)
    at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:26)
    at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:20)
    at mezz.jei.gui.ingredients.GuiIngredient.draw(GuiIngredient.java:126)
    at mezz.jei.gui.ingredients.GuiIngredientGroup.draw(GuiIngredientGroup.java:163)
    at mezz.jei.gui.recipes.RecipeLayout.draw(RecipeLayout.java:141)
    at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:212)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at Reflector.callVoid(Reflector.java:530)

===

**Comment by kitsushadow** [comment]
https://github.com/kitsushadow/forgecraft/tree/master/1.11/src/main

My github repo

**Comment by mezz** [comment]
Based on the error information, your tool being clicked has this nbt: 
`Item NBT: {ench:[0:{lvl:4s,id:32s}]}` 
and `ToolNBT.getHot` is trying to do `stack.getSubCompound("tags").getBoolean("hot");` 
Since "tags" doesn't exist it will crash.

The items in JEI come from the creative menu, make sure your items there are valid.

**Comment by kitsushadow** [comment]
I'm quite sure they are, how can i confirm?

**Comment by mezz** [comment]
Note: We debugged this on Discord and it turned out to be an issue with the tool's nbt handling.
