### ISSUE TITLE
BrewingRecipeUtil StackOverflowError

### ISSUE THREAD

**Issue by ghost** [mezz/JustEnoughItems#842]
[13:41:02] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[13:41:02] [Server thread/ERROR] [FML/]: Caught exception from Just Enough Items (jei)
java.lang.StackOverflowError
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:47) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
...

[13:41:02] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)

Caused by: java.lang.StackOverflowError
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:47) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
	at mezz.jei.plugins.vanilla.brewing.BrewingRecipeUtil.getBrewingSteps(BrewingRecipeUtil.java:53) ~[BrewingRecipeUtil.class:?]
...

**Comment by ghost** [comment]
used jei_1.11.2-4.3.4.272.jar with forge 2294, and some other mods.
i took these lines from the fml logs, there was no any crash.

**Comment by way2muchnoise** [comment]
In those other mods, any that change or add potions?

**Comment by ghost** [comment]
yes, reliquary.

**Comment by way2muchnoise** [comment]
Got some version numbers for reliquary, ~~JEI and forge~~  makes finding the interaction issue easier.

EDIT: derp you posted versions for JEI and forge already

**Comment by ghost** [comment]
i'm using reliquary Reliquary-1.11.2-1.3.3.653.jar

**Comment by mezz** [comment]
Thanks, I just changed the code for potions so this is a new bug. I'll test with Reliquary and fix the issue.

**Comment by mezz** [comment]
This doesn't seem to be caused by Reliquary. It uses potions, but they have their own brewing system separate from vanilla. Do you have another mod that adds potions?

**Comment by mezz** [comment]
I pushed an updated version of JEI that should try to avoid this issue.
Please update to JEI 4.3.4.273 and see if it still crashes.

**Comment by ghost** [comment]
yes! it works(.273) thanks for the fix.
