### ISSUE TITLE
i need help my game keeps crashing!!!

### ISSUE THREAD

**Issue by Coolperson2323** [mezz/JustEnoughItems#868]
hey i want this mod bad but it keeps on crashing :( pls help if you know what the problem is
heres the report
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 5/25/17 2:59 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent$MouseInputEvent$Pre
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:733)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:315)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:491)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/GuiScreenEvent$MouseInputEvent$Pre
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetPublicMethods(Class.java:2894)
	at java.lang.Class.getMethods(Class.java:1607)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:60)
	at mezz.jei.ProxyCommonClient.init(ProxyCommonClient.java:60)
	at mezz.jei.JustEnoughItems.init(JustEnoughItems.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.GuiScreenEvent$MouseInputEvent$Pre
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 251240008 bytes (239 MB) / 594817024 bytes (567 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1450.jar) 
	UCHI	Forge{11.14.3.1450} [Minecraft Forge] (forge-1.8-11.14.3.1450.jar) 
	UCHI	securitycraft{v1.7.4.1} [SecurityCraft] ([1.8] SecurityCraft v1.7.4.1.jar) 
	UCHI	fastfood{0.1.1} [Fast Food] ([1.8]Fast Food-0.1.1.jar) 
	UCHI	imsm{1.8} [Instant Massive Structures Mod] ([1.8]InstantMassiveStructuresMod2.jar) 
	UCHI	hnm{1.0.4} [NeighborCraft] ([1.8]NeighborCraft[1.0.4].jar) 
	UCHI	lom{1.8-0.1} [LotsOMobs] (_lom-1.8-0.1.jar) 
	UCHI	adminweapons{2.5} [Admin Weapons] (admin-weapons-mod-1.8.jar) 
	UCHI	animalbikes{1.8} [Animal Bikes] (AnimalBikes_1.8.0.jar) 
	UCHI	ArchitectureCraft{1.0.0} [ArchitectureCraft] (ArchitectureCraft-Mod-1.8.jar) 
	UCHI	babymobs{1.4} [Baby Mobs] (Baby-Mobs-Mod-1.8.jar) 
	UCHI	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.8.x.jar) 
	UCHI	tennox_bacteria{2.4} [Bacteria Mod] (Bacteria-Mod-1.8.jar) 
	UCHI	ctrades{1.3.2} [Custom Trades Mod] (Custom-Trades-Mod-1.8.jar) 
	UCHI	wonderfulwands{1.7.2} [Wonderful Wands] (CyanosWonderfulWands_1.8-1.7.2.jar) 
	UCHI	DamageIndicatorsMod{3.3.2} [Damage Indicators] (Damage-Indicators-Mod-1.8.jar) 
	UCHI	doge{0.5.3} [Doge] (Doge-Mod-1.8.jar) 
	UCHI	doggytalents{v1.9.1a} [Doggy Talents] (Doggy-Talents-Mod-1.8.zip) 
	UCHI	MoCreatures{8.0.1} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-8.0.1.jar) 
	UCHI	emeraldmod{4.0} [EmeraldMod] (EmeraldMod-1.8-V4.0-Forge.jar) 
	UCHI	exoticbirds{1.0} [Exotic Birds] (Exotic Birds 1.8 - 1.0.3b.jar) 
	UCHI	examplemod{1.0} [examplemod] (eyemod-EyeOS2.0-1.8.jar) 
	UCHI	eyemod{2.0} [EyeMod] (eyemod-EyeOS2.0-1.8.jar) 
	UCHI	Fnafmod{1.0.0} [Fnafmod] (FNAFmodfor1.8.jar) 
	UCHI	IronChest{6.0.107.754} [Iron Chest] (Iron-Chests-Mod-1.8.jar) 
	UCHE	JEI{1.8.0.90} [Just Enough Items] (jei_1.8-1.8.0.90.jar) 
	UCHI	lootplusplus{1.7.1_for_1.8} [Loot++] (Loot++-1.7.1_for_1.8.jar) 
	UCHI	MiniBosses{1.2.2} [Mini-Bosses] (Mini-Bosses-Mod-1.8.jar) 
	UCHI	mb{1.0} [Modular Bosses] (Modular-Bosses-Mod-1.8.jar) 
	UCHI	MoreFurnaces{1.3.11} [More Furnaces] (More-Furnaces-Mod-1.8.jar) 
	UCHI	cfm{4.0.1} [MrCrayfish's Furniture Mod] (Mr.Crayfish's Furniture Mod.jar) 
	UCHI	oceancraft{1.5.1} [Oceancraft] (oceancraft-1.5.2 (1).jar) 
	UCHI	pandorasbox{2.1.2} [Pandora's Box] (PandorasBox-2.1.2.jar) 
	UCHI	potioncore{1.3_for_1.8} [Potion Core] (PotionCore-1.3_for_1.8.jar) 
	UCHI	Rediscovered{1.3} [Minecraft Rediscovered Mod] (Rediscovered-1.8-1.3.jar) 
	UCHI	soggytransportation{4.0.0} [SoggyMustache's Transportation] (soggytransportation- 4.5.2 (1.8).jar) 
	UCHI	subway{2.0} [Subway Resturant] (Subway-Mod-1.8.jar) 
	UCHI	TooMuchTNT{3.0} [TooMuchTNT] (Too-Much-TNT-Mod-1.8.jar) 
	UCHI	aziasvendingmachine{Vending Machines Revamped} [Vending Machines Revamped] (VendingMachinesRevamped_Alpha0.0.1_1.8.jar) 
	UCHI	mymod{1.3.5} [Bash Cat's Weapon Arsenal] (Weapon-Arsenal-Mod-1.8.jar) 
	UCHI	weirdthingsmod{1.1 BETA} [Weird Things Mod] (Weird-Things-Mod-1.8.jar) 
	UCHI	XaeroMinimap{1.6.5} [Xaero's Minimap] (xaeros_minimap_v1.6.5_Forge_1.8.jar) 
	UCHI	youtubers{1.7.0} [Youtubers+ Mod] (youtubers-mc1.8-1.7.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.49' Renderer: 'GeForce GTX 950/PCIe/SSE2'

**Comment by mezz** [comment]
Thanks for the report!
Make sure you are using the latest Forge available for 1.8, I think the version you have is too old.

**Comment by mezz** [comment]
Did that work @Coolperson2323 ?
