### ISSUE TITLE
Game crashes just after Forge loading screen

### ISSUE THREAD

**Issue by EpicMario13** [mezz/JustEnoughItems#888]
Title says it all. I have a lot of other mods, so one of those might be conflicting with it, but honestly, I'm too lazy to check.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Mine and Blade: Battlegear2 (1.8.9-MB_Battlegear2-Bullseye-1.0.10.2.jar)
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
ItemPatchingLoader (ItemPhysic Lite 1.3 mc1.8.9.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/9/17 7:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.AbstractMethodError
at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:417)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.AbstractMethodError
at mezz.jei.util.AnnotatedInstanceUtil.getModPlugins(AnnotatedInstanceUtil.java:24)
at mezz.jei.ProxyCommonClient.preInit(ProxyCommonClient.java:54)
at mezz.jei.JustEnoughItems.preInit(JustEnoughItems.java:56)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.8.9
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 135959528 bytes (129 MB) / 327122944 bytes (311 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.19 Powered by Forge 11.15.1.1902 20 mods loaded, 20 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCH mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
UCH FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar)
UCH Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar)
UCH itemphysic{1.3.0} [ItemPhysic] (minecraft.jar)
UCH battlegear2{1.8.9} [Mine & Blade Battlegear 2 - Bullseye] (1.8.9-MB_Battlegear2-Bullseye-1.0.10.2.jar)
UCH antiqueatlas{@VERSION@} [Antique Atlas] (antiqueatlas-1.8.9-4.2.10.jar)
UCH rafradek_blocklauncher{1.4.1} [Block Launcher] (Block-Launcher-Mod-1.8.9.jar)
UCH cfm{4.0.1} [MrCrayfish's Furniture Mod] (cfm-4.0.1-mc1.8.9.jar)
UCH lootablebodies{1.4.0} [DrCyano's Lootable Bodies] (CyanosLootableBodies-1.4.0.jar)
UCH EE{1.0} [Easter Egg Mod 1.8.9 Remake] (EasterEgg Mod 1.8.9.jar)
UCH emeraldmod{4.1} [EmeraldMod] (EmeraldMod-1.8.9-V4.1-Forge.jar)
UCH fakeores{1.5} [Fake Ores 2] (fakeores2v1.5-mc1.8.9.jar)
UCH grapplemod{1.9.4-v7} [Grappling hook mod] (grapplemod-1.8.9-v7.jar)
UCH InventoryPets{1.4.9} [Inventory Pets] (inventorypets-1.8.9-1.4.9.jar)
UCE JEI{2.13.0.52} [Just Enough Items] (jei_1.8.9-2.13.0.52.jar)
UCH mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar)
UCH oceancraft{1.5.3} [Oceancraft] (Oceancraft v1.5.3 (MC 1.8.9).jar)
UCH rftl{1.0} [Rotten Flesh to Leather] (RFTL-1.8.9-1.0.jar)
UCH SlimeCarnage{2.1.1} [Slime Carnage] (SlimeCarnage-2.1.1-mc1.8.9.jar)
UCH tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct] (TConstruct-1.8.9-2.2.1.jar)
Loaded coremods (and transformers):
Mine and Blade: Battlegear2 (1.8.9-MB_Battlegear2-Bullseye-1.0.10.2.jar)
mods.battlegear2.coremod.transformers.EntityPlayerTransformer
mods.battlegear2.coremod.transformers.ModelBipedTransformer
mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
mods.battlegear2.coremod.transformers.ItemRendererTransformer
mods.battlegear2.coremod.transformers.RenderItemTransformer
mods.battlegear2.coremod.transformers.MinecraftTransformer
mods.battlegear2.coremod.transformers.ItemStackTransformer
mods.battlegear2.coremod.transformers.ItemInWorldTransformer
mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
codechicken.lib.asm.ClassHeirachyManager
codechicken.lib.asm.RenderHookTransformer
ItemPatchingLoader (ItemPhysic Lite 1.3 mc1.8.9.jar)
com.creativemd.itemphysic.ItemTransformer
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.78' Renderer: 'GeForce GTX 660 Ti/PCIe/SSE2'
Pulsar/tconstruct loaded Pulses:
- TinkerCommons (Enabled/Forced)
- TinkerWorld (Enabled/Not Forced)
- TinkerTools (Enabled/Not Forced)
- TinkerSmeltery (Enabled/Not Forced)
- TinkerGadgets (Enabled/Not Forced)
- TinkerOredict (Enabled/Forced)
- TinkerIntegration (Enabled/Forced)
- TinkerFluids (Enabled/Forced)
- TinkerMaterials (Enabled/Forced)

**Comment by mezz** [comment]
Thanks for the report!
I pushed a new version that will log a better error, it will tell you which mod plugin is crashing.
It will be on curseforge soon.
